"""
03_build_schema.py — Generate per-artist schema .py files from scraped lyrics.

This produces files like schemas/KL_schema.py containing KL_SCHEMA = {...}
that follow the same format as the original RTJ.py / GD.py, making the
existing Music_Comparison.ipynb code compatible with the full catalog.

It also writes schemas/full_catalog.py which merges all schemas.

Usage
-----
  python 03_build_schema.py                  # build all
  python 03_build_schema.py --artists KL TS  # rebuild specific artists

Note on lyrics source
---------------------
  The schema stores 'lyrics_clean' (section headers stripped) for compatibility
  with the existing MuLan embedding code.  The 07_segment_analysis.py step
  reads the raw lyrics JSON directly (which preserves section headers).
"""

from __future__ import annotations
import os
import sys
import json
import logging
import argparse
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from config import CATALOG, LYRICS_DIR, SCHEMA_DIR
from utils import setup_logging

setup_logging()
logger = logging.getLogger(__name__)


def _escape(s: str) -> str:
    """Triple-quote-safe string escaping for embedding in Python source."""
    return s.replace("\\", "\\\\").replace('"""', r'\"\"\"')


def build_schema_for_artist(artist_code: str) -> tuple[str, list[str], list[str]]:
    """
    Build the Python source string for one artist's schema.

    Returns (python_source, included_ids, missing_ids).
    """
    artist_data  = CATALOG[artist_code]
    artist_name  = artist_data["name"]
    schema_var   = f"{artist_code}_SCHEMA"
    lyrics_dir   = Path(LYRICS_DIR)

    included = []
    missing  = []
    entries  = []

    for song_id, song_meta in artist_data["songs"].items():
        lyrics_path = lyrics_dir / f"{song_id}.json"
        if not lyrics_path.exists():
            missing.append(song_id)
            logger.warning(f"  [{song_id}] No lyrics file — skipping from schema")
            continue

        with open(lyrics_path, encoding="utf-8") as f:
            data = json.load(f)

        lyrics_clean = data.get("lyrics_clean") or data.get("lyrics", "")
        if not lyrics_clean.strip():
            missing.append(song_id)
            logger.warning(f"  [{song_id}] Empty lyrics — skipping from schema")
            continue

        title   = _escape(data.get("title", song_meta["title"]))
        artist  = _escape(data.get("artist", artist_name))
        lyrics  = _escape(lyrics_clean)

        entries.append(
            f'    "{song_id}": {{\n'
            f'        "title":  "{title}",\n'
            f'        "artist": "{artist}",\n'
            f'        "lyrics": """{lyrics}""",\n'
            f'    }},'
        )
        included.append(song_id)

    body = "\n".join(entries)
    source = (
        f'# Auto-generated by 03_build_schema.py — do not edit manually.\n'
        f'# Artist: {artist_name}  |  Code: {artist_code}\n'
        f'# Songs included: {len(included)}  |  Missing: {len(missing)}\n\n'
        f'{schema_var} = {{\n'
        f'{body}\n'
        f'}}\n'
    )
    return source, included, missing


def build_all_schemas(artist_filter: list[str] | None = None) -> dict:
    """
    Build schema .py files for every artist in the catalog.

    Returns a summary dict with included/missing counts.
    """
    schema_dir = Path(SCHEMA_DIR)
    schema_dir.mkdir(parents=True, exist_ok=True)

    summary = {}
    all_entries = {}   # for the full catalog merge

    for artist_code, artist_data in CATALOG.items():
        if artist_filter and artist_code not in artist_filter:
            continue

        logger.info(f"Building schema for {artist_data['name']} ({artist_code})…")
        source, included, missing = build_schema_for_artist(artist_code)

        out_path = schema_dir / f"{artist_code}_schema.py"
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(source)

        logger.info(f"  → {out_path}  ({len(included)} songs, {len(missing)} missing)")
        summary[artist_code] = {"included": included, "missing": missing}

        # Collect for full catalog
        for sid in included:
            all_entries[sid] = artist_code

    # ── Write full_catalog.py ──────────────────────────────────────────────
    catalog_source = build_full_catalog_source(artist_filter)
    catalog_path   = schema_dir / "full_catalog.py"
    with open(catalog_path, "w", encoding="utf-8") as f:
        f.write(catalog_source)
    logger.info(f"\nFull catalog → {catalog_path}")

    # ── Print summary ──────────────────────────────────────────────────────
    total_included = sum(len(v["included"]) for v in summary.values())
    total_missing  = sum(len(v["missing"])  for v in summary.values())
    logger.info(f"\n{'═'*50}")
    logger.info(f"Schema build complete: {total_included} songs included, {total_missing} missing")

    return summary


def build_full_catalog_source(artist_filter: list[str] | None = None) -> str:
    """
    Produce a full_catalog.py that imports all artist schemas and merges them.
    """
    schema_dir   = Path(SCHEMA_DIR)
    import_lines = []
    merge_parts  = []

    for artist_code in CATALOG:
        if artist_filter and artist_code not in artist_filter:
            continue
        schema_path = schema_dir / f"{artist_code}_schema.py"
        if not schema_path.exists():
            continue
        var = f"{artist_code}_SCHEMA"
        import_lines.append(f"from schemas.{artist_code}_schema import {var}")
        merge_parts.append(f"    **{var},")

    imports = "\n".join(import_lines)
    merges  = "\n".join(merge_parts)

    return (
        "# Auto-generated by 03_build_schema.py — do not edit manually.\n"
        "# Merges all artist schemas into a single FULL_CATALOG dict.\n\n"
        f"{imports}\n\n"
        "FULL_CATALOG = {\n"
        f"{merges}\n"
        "}\n"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Build artist schema .py files")
    parser.add_argument("--artists", nargs="*", help="Artist codes (default: all)")
    args = parser.parse_args()

    build_all_schemas(artist_filter=args.artists or None)
