# Auto-generated by 03_build_schema.py — do not edit manually.
# Artist: Childish Gambino  |  Code: CG
# Songs included: 12  |  Missing: 0

CG_SCHEMA = {
    "CG_01": {
        "title":  "Redbone",
        "artist": "Childish Gambino",
        "lyrics": """Daylight
I wake up feelin' like you won't play right
I used to know, but now that shit don't feel right
It made me put away my pride
So long
You made a nigga wait for some, so long
You make it hard for boy like that to go on
I'm wishin' I could make this mine, oh


(If you want it) Yeah
(You can have it) Oh, oh, oh
(If you need it) Ooh
(We can make it, oh)
If you want it
You can have it


But stay woke
Niggas creepin'
They gon' find you
Gon' catch you sleepin', ooh
Now stay woke
Niggas creepin'
Now, don't you close your eyes


Too late
You wanna make it right, but now it's too late
My peanut butter chocolate cake with Kool-Aid
I'm tryin' not to waste my time


(If you want it) Oh
(You can have it) You can have it
(If you need it) You better believe in somethin'
(We can make it, oh)
If you want it
(You can have it) Ahh!


But stay woke (Stay woke)
Niggas creepin' (They be creepin')
They gon' find you (They gon' find you)
Gon' catch you sleepin', ooh (Gon' catch you sleepin', put your hands up now, baby)
Now stay woke
Niggas creepin'
Now, don't you close your eyes
But stay woke (Ooh-ahh)
Niggas creepin' (They gon' find you)
They gon' find you
Gon' catch you sleepin', ooh (Gon' catch you, gon' catch you)
Now stay woke
Niggas creepin'
Now, don't you close your eyes


How'd it get so scandalous?
Oh, how'd it get so scandalous?
Oh, oh, baby, you, how'd it get
How'd it get so scandalous?
How'd it get so scandalous?
But stay woke
But stay woke""",
    },
    "CG_02": {
        "title":  "This Is America",
        "artist": "Childish Gambino",
        "lyrics": """Yeah, yeah, yeah, yeah, yeah
Yeah, yeah, yeah, go, go away
Yeah, yeah, yeah, yeah, yeah
Yeah, yeah, yeah, go, go away
Yeah, yeah, yeah, yeah, yeah
Yeah, yeah, yeah, go, go away
Yeah, yeah, yeah, yeah, yeah
Yeah, yeah, yeah, go, go away


We just wanna party
Party just for you
We just want the money
Money just for you (
Yeah
)
I know you wanna party
Party just for free
Girl, you got me dancin' (Girl, you got me dancin')
Dance and shake the frame (
Yeah
)
We just wanna party (
Yeah
)
Party just for you (
Yeah
)
We just want the money (
Yeah
)
Money just for you (
You
)
I know you wanna party (
Yeah
)
Party just for free (
Yeah
)
Girl, you got me dancin' (Girl, you got me dancin', 
yeah
)
Dance and shake the frame (
Ooh
)


This is America
Don't catch you slippin' now
Don't catch you slippin' now
Look what I'm whippin' now
This is America (
Woo
)
Don't catch you slippin' now
Don't catch you slippin' now
Look what I'm whippin' now


This is America (
Skrrt, skrrt, woo
)
Don't catch you slippin' now (
Ayy
)
Look how I'm livin' now
Police be trippin' now (
Woo
)
Yeah, this is America (
Woo, ayy
)
Guns in my area (
Word
, 
my area
)
I got the strap (Ayy, ayy)
I gotta carry 'em
Yeah, yeah, I'ma go into this (
Ugh
)
Yeah, yeah, this is guerilla (Woo)
Yeah, yeah, I'ma go get the bag
Yeah, yeah, or I'ma get the pad
Yeah, yeah, I'm so cold like, yeah (
Yeah
)
I'm so dope like, yeah (Woo)
We gon' blow like, yeah (
Straight up
, uh)


Ooh-ooh-ooh-ooh-ooh, tell somebody
You go tell somebody
Grandma told me
Get your money, Black man (
Get your— Black man
)
Get your money, Black man (
Get your—Black man
)
Get your money, Black man (
Get your—Black man
)
Get your money, Black man (
Get your—Black man
)
Black man


This is America (
Woo, ayy
)
Don't catch you slippin' now (
Woo, woo, don't catch you slippin' now
)
Don't catch you slippin' now (
Ayy, woah
)
Look what I'm whippin' now (
Slime
)
This is America (
Yeah, yeah
)
Don't catch you slippin' now (
Woah
, 
ayy
)
Don't catch you slippin' now (
Ayy
, 
woo
)
Look what I'm whippin' now (
Ayy
)


Look how I'm geekin' out (
Hey
)
I'm so fitted (
I'm so fitted, woo
)
I'm on Gucci (
I'm on Gucci
)
I'm so pretty (
Yeah, yeah
, 
woo
)
I'm gon' get it (
Ayy, I'm gon' get it
)
Watch me move (
Blaow
)
This a celly (
Ha
)
That's a tool (
Yeah
)
On my Kodak (Woo) Black
Ooh, know that (Yeah, know that, hold on)
Get it (Woo, get it, get it)
Ooh, work it (21)
Hunnid bands, hunnid bands, hunnid bands (
Hunnid bands
)
Contraband, contraband, contraband (
Contraband
)
I got the plug in Oaxaca (
Woah
)
They gonna find you like "blocka" (
Blaow
)


Ooh-ooh-ooh-ooh-ooh, tell somebody
America, I just checked my following list, and
You go tell somebody
You mothafuckas owe me
Grandma told me
Get your money, Black man (
Black man
)
Get your money, Black man (
Black man
)
Get your money, Black man (
Black man
)
Get your money, Black man (
Black man
)
Black man
(
1, 2, 3—get down
)
Ooh-ooh-ooh-ooh-ooh, tell somebody
You go tell somebody
Grandma told me, "Get your money"
Get your money, Black man (
Black man
)
Get your money, Black man (
Black man
)
Get your money, Black man (
Black man
)
Get your money, Black man (
Black man
)
Black man


You just a black man in this world
You just a barcode, ayy
You just a black man in this world
Drivin' expensive foreigns, ayy
You just a big dawg, yeah
I kenneled him in the backyard
No, probably ain't life to a dog
For a big dog""",
    },
    "CG_03": {
        "title":  "3005",
        "artist": "Childish Gambino",
        "lyrics": """No matter what you say or what you do
When I'm alone, I'd rather be with you
Fuck these other niggas
I'll be right by your side 'til 3005, hol' up


Okay, hold up, wait a minute (Minute), all good just a week ago
Crew at my house and we party every weekend, so
On the radio, that's my favorite song
Make me bounce around, like, I don't know, like, I won't be here long
Now, the thrill is gone, got no patience, 'cause I'm not a doctor (No)
Girl, why is you lyin'? (What?) Girl, why you Mufasa?
Yeah, mi casa su casa, gotta strip it like Gaza
Got so high off volcanoes, now the flow is so lava
Yeah, we spit that saliva, iPhone got message from Viber
Either the head is so hydra, or we let bygones be bygones
"My God, you pay for your friends?" (What?) I'll take that as a compliment
Got a house full of homies, why I feel so the opposite?
Incompetent ain't the half of it, Saturdays, we're Young Lavish's
Saddest shit, is I'm bad as it, beans they took from the cabinet (Woah)
Sorry (Sorry), I'm just scared of the future
'Til 3005, I got your back, we can do this, hol' up


No matter what you say or what you do
When I'm alone, I'd rather be with you
Fuck these other niggas
I'll be right by your side 'til 3005, hol' up
(Hol' up) Hol' up, (Hol' up) hol' up
(Hol' up) Hol' up, (Hol' up) hol' up (But you ain't got—, but you ain't got nobody)
(Hol' up) Hol' up, (Hol' up) hol' up
(Hol' up) Hol' up (But you ain't got—, but you ain't got nobody), hol' up
No matter what you say or what you do
When I'm alone, I'd rather be with you (But you ain't got—, but you ain't got nobody)
Fuck these other niggas
I'll be right by your side 'til 3005, hol' up (But you ain't got—, but you ain't got nobody)
(Hol' up) Hol' up, (Hol' up) hol' up
(Hol' up) Hol' up, (Hol' up) hol' up (But you ain't got—, but you ain't got nobody)
(Hol' up) Hol' up, (Hol' up) hol' up
(Hol' up) Hol' up (Hol' up; But you ain't got—, but you ain't got nobody)


I used to care what people thought, but now I care more
Man, nobody out here's got it figured out, so therefore
I've lost all hope of a happy ending
Depending on whether or not it's worth it, so insecure, no one's perfect
We spend it with no shame, we blow that like Coltrane
We in here like Rogaine, or leave it like Cobain
And when I'm long gone, whole crew sing a swan song
'Cause we all just ticking time bombs, got a Lambo like LeBron's mom
And no matter where all of my friends go (Yeah), Emily, Fam, and Lorenzo (Yeah)
All of them people my kinfolk, at least I think so
Can't tell, 'cause when them checks clear, they're not here
'Cause they don't care (They don't care), it's kinda sad
But I'm laughin', whatever happens, assassins are stabbed in the back
Of my cabin, labrador yappin', I'm glad that it happened, I mean it
Between us, I think there's something special (I think there's something special)
And if I lose my mental, just hold my hand even if you don't understand, hol' up


No matter what you say or what you do (No, no)
When I'm alone, I'd rather be with you (You and me)
Fuck these other niggas
I'll be right by your side 'til 3005, hol' up (No-no-no-no, no-no-no)
(Hol' up) Hol' up, (Hol' up) hol' up
(Hol' up) Hol' up, (Hol' up) hol' up (But you ain't got—, but you ain't got nobody)
(Hol' up) Hol' up, (Hol' up) hol' up
(Hol' up) No (But you ain't—), hol' up
No matter what you say or what you do
When I'm alone, I'd rather be with you (But you ain't got nobody)
Fuck these other niggas
I'll be right by your side 'til 3005, hol' up (But you ain't got nobody)
(Hol' up) Hol' up, (Hol' up) hol' up
(Hol' up) Hol' up, (Hol' up) hol' up (But you ain't got nobody)
(Hol' up) Hol' up, (Hol' up) hol' up
(Hol' up) Hol' up (Hol' up; But you ain't got nobody)


Hol' up, hol' up
Hol' up, hol' up (But you ain't got nobody)
Hol' up, hol' up
Hol' up, hol' up (But you ain't got nobody)


Na-na-na
Na-na-na-na-na
We did it (Yay)
Nigga, you so thirsty""",
    },
    "CG_04": {
        "title":  "Sober",
        "artist": "Childish Gambino",
        "lyrics": """And now that it's over, I'll never be sober
I couldn't believe, but now I'm so high
And now that it's over, I'll never be sober
I couldn't believe, but now I'm so high
But now I'm so high
But now I'm so high
But now I'm so high


Girl, what's your problem?
'Cause I know it's hard sometimes, baby just give it some time
Oh honey now girl, we can solve them
If you just give me some time I can open up your mind
If you let it shine, you can free your mind
'Cause I know


And now that it's over, I'll never be sober
I couldn't believe, but now I'm so high
And now that it's over, I'll never be sober
I couldn't believe, but now I'm so high
But now I'm so high
But now I'm so high
But now I'm so high


Girl, if it's done right
Well you know it's got to be, something wonderful to me
Oh honey now girl, give it one night
If you just give it a chance, loving you is not my plan
Cause I know one day you'll see
All the things that we can be
No, no, no...


And now that it's over, I'll never be sober
(I want to be the only one)
I couldn't believe, but now I'm so high
And now that it's over, I'll never be sober
I couldn't believe, but now I'm so high
But now I'm so
(But now I'm so high)
(But now I'm so high)
(But now I'm so high)
(But now I'm so high)
(But now I'm so high)
(But now I'm so high)


And now that it's over, I'll never be sober
I couldn't believe, but now I'm so high
But now I'm so high
But now I'm so high
But now I'm so high
But now I'm so high
But now I'm so high...""",
    },
    "CG_05": {
        "title":  "Sweatpants",
        "artist": "Childish Gambino",
        "lyrics": """Watching haters wonder why Gambino got the game locked (Yeah?)
Half-Thai thickie, all she wanna do is Bangkok (Yeah?)
Got her hair done, French braids, now she A$AP
Bino so insensitive, she askin', "Why you say that?"
I'm chillin' (Yeah), real nigga feelin'
Rich kid asshole, paint me as a villain (Ma!)
Still spitting that cash flow, DJ Khaled
I got a penthouse on both coasts, pH balance
Real nigga, I rep those
Why though? 'Cause I said so
Hip deep in that Pepto, I got five on her like Ben Folds
I got more tail than that PetCo (What?)
You faker than some Sweet'N Low (
Why?
)
Yeah, you got some silverware
But really, are you eating though? (
Yeah
)
Are you eating though? Nigga, are you eating though?
Breakfast, lunch, and dinner's for beginners, you ain't even know
Never catching cases, why they faces look so E-M-O?
Watch a hater hate me, wanna play me like a piano
My architect know Japanese (
Yeah?
)
Your girl, she jockin' these (
Yeah?
)
No hands like soccer teams and y'all fuck boys like Socrates
You niggas ain't coppin' these, niggas ain't lookin' like me (
Nah
)
Nah, I ain't checkin' I.D. (
Nah
), but I bounce 'em with no problem
Tell 'em, Problem (
Problem!
)


I'm winnin', yeah, yeah, I'm winnin' (
What?
)
I'm winnin', yeah, yeah, I'm winnin' (
What?
)
I'm winnin', yeah, yeah, I'm winnin' (
What?
)
Rich kid, asshole, paint me as a villain


What?
Don't be mad 'cause I'm doing me better than you doing you
Don't be mad 'cause I'm doing me better than you doing you
Don't be mad 'cause I'm doing me better than you doing you
Better than you doing you
Fuck it, what you gon' do? (
What?!
)


Different color, my passport
Instagram my stack load
Hashtag my daywear, and your girl drank my daycare
And I'm born rich, life ain't fair, 
it's silver spoon coon, ho
Ain't nobody sicker in my Fisker, “vroom-vroom,” ho
Ain't nobody—
(Fiskers don't make noise when they start up, just so you know)
Top of the holy totem
Ri-ri-ri-rich forever, a million was not the quota
My father owned half the MoMA and did it with no diploma
Year off, got no rules, trippin' off of them toadstools
More green than my Whole Foods
And I'm too fly, Jeff Goldblum
Got a glasshouse in the Palisades, that A-K-A
White hood, white hood, O-K-K-K
Furniture custom, you shop at IKEA
Show Maserati, you whippin' a Kia
Spendin' this money, it's longer than Nia
Live like a Coppola, me and Sofia
Wakin' up broke, man, wouldn't wanna be ya
Friends with the dopeman, help a nigga re-up
Bring a girlfriend, man, trouble when I see her
"
Err-eh-err-eh
," onomatopoeia
Ohh, I got my cool on (Tailor-made)
I'm winnin', so they had to dump the Gatorade
And I don't give a fuck about my family name


What?
Don't be mad 'cause I'm doing me better than you doing you
Don't be mad 'cause I'm doing me better than you doing you
Don't be mad 'cause I'm doing me better than you doing you
Better than you doing you
Fuck it, what you gon' do? (
What?!
)""",
    },
    "CG_06": {
        "title":  "V. 3005 (Beach Picnic Version)",
        "artist": "Childish Gambino",
        "lyrics": """Is anybody out there?

Uh

This is real life I'm rappin' bout, ambitions I'm actin' out
Haters smell it comin', and hold they breath until they passin' out
And half the doubt, I'm seein' is a product of my past
This underdog just whooped yo ass, I'm on fire bet y'all ain't laughin' now
No 9/11 but, they callin 'em when I smack ya mouth
Wit controversial language, got Pistons that could stack-a-house
My music is life, double figure 8s around these niggas
Thinkin' that they competition, and they politely backin' out
I could easily get up on this microphone and yap about
The money, bitches... clothes but my conscience would have to bounce
Like checks, style is foreign like Czechoslovakians
My mission, to make failure impossible like a Romney win
They jockeyin', to get that pole position by local dissin'
Hear that passion in my vocals drippin' like Joker lip n'
Only got four conditions nigga, keep calm n respect mine
Give it to me straight up and make sure my f*ckin' checks signed
Y'all don't know my struggle, I'm a product of domestic violence
Coincided wit my skin color's more than enough
To keep that drive burnin' inside Kobe Bryant Olympic
Five rings, honin' my craft I'm too fly for yo physics Wake UP
Cause all I see is (see is), imitators n kids
They stay backtrackin' this progress, they on Twitter followin' trends
And I know, you claimin' yo clique is riders like Winona
Well mine is stackin' that paper, this rapper got a diploma and
My president is half black, the other half is kinda white but like Barack
This African blowin' like Black, Dynamite
Find a flight, outta the country I got that Coyote Ugly
For rappers thinkin' they can touch me (ha)
Y'all brain matter dusty, utilizin' that autotune to make yo moves
That shit is outdated like readin' that paper for news
I been payin' my dues, thinkin' bout that rapper life
Lyrically slap you niggas, wit lotion like a Kappa fight
One day I'mma have a wife, for now I got a ride-or-die
Lady wit class, that hold me down n I ain't gotta lie
Firefly, Campin' out wit niggas I would never doubt
Shoutout to Gambino this instrumental I'm stampin' out
Bodybag, stretchin' out my lyrics like Pilate class
Blessed, catchin' breaks that could make a Maserati drag
I got my feet wet, now I kill it off reflex
Game losin' color, I'mma dye it like I eat less
I'm THE best, rapper you know that's college educated
If it wasn't for my friends n fam I'd a never made it
I became a monster when my parents was separated
Seein' through black n white because my vision desegregated
My music elevated, young kids wit' a dream to get
Outside of they circumstance, real shit n I plead the fifth
On how I gained this knowledge, shoulda stayed wit Vonage
Cause my phone calls is long distance, y'all blow hard wit no sinus
This rap shit is my passion, got no competition I know of
Y'all spittin' that same shit, so y'all lames get no love
Hashtag turn up and poppin' Mollys in yo lyrics
That shit might work in Atlanta, but the world ain't tryna hear it mannnn

Ha... quick break to breathe

Back at it...
Look, I was born for this, it's written on my birth certificate
Flippin' syllables and sentences, feelin' terrific wit terrific wit
Goin' hard for people that I need to reach
Wakin' niggas up on the daily, cause y'all been sleep for weeks""",
    },
    "CG_07": {
        "title":  "Me and Your Mama",
        "artist": "Childish Gambino",
        "lyrics": """I'm in love when we are smoking that
 la-la-la-la-la
I'm in love when we are smoking that
 la-la-la-la-la
I'm in love when we are smoking that
 la-la-la-la-la
I'm in love when we are smoking that
 la-la-la-la-la
I'm in love when we are smoking that
 la-la-la-la-la
I'm in love when we are smoking that
 la-la-la-la-la
I'm in love when we are smoking that
 la-la-la-la-la
I'm in love when we are smoking that
 la-la-la-la-la


Do what you want
(Woo!)


(I'm telling you) Let me into your heart


Can't stand it, backhanded
They wanna see us falling apart
You know that I love you
So let me into you (Woo)


Let me into your heart
(Do you really like me? I'ma get you, girl, ah!)


This is the end of us
Sleeping with the moon and the stars
I know where you been, oh
You can see us far then near


Let me into your heart
(Oh, this ain't no bullshit, I really love you, girl)
Oh, oh, god


Girl, you really got a hold on me
So this isn't just puppy love
Girl, you really got a hold on me
So this isn't just puppy love


I'm in love when we are smokin' that
(Oh my God, I)
Let me in (Girl, you really got a hold, woo!)""",
    },
    "CG_08": {
        "title":  "Terrified",
        "artist": "Childish Gambino",
        "lyrics": """There's a bottom to the top of a moment
You won't always be around
Catch a nigga coming quickly behind you
People want you underground
Do you misbehave?
Haunt you to your grave
I'm going to eat you alive
Please don't find me rude
But I don't eat fast food
So don't run too fast, ooh, oh-oh


Just hide, ooh!
You know that you're the one that's terrified, ooh
Just hide, ooh!
You know that you're the one that's terrified, ooh


La, la, la, la, la
La, la, la, la, la


I'm spinning, I'm spinning, I'm spinning you up
I'm spinning, I'm spinning, I'm spinning you up
I'm spinning, I'm spinning, I'm spinning you up
I'm spinning, I'm spinning, I'm spinning you up
I'm spinning, I'm spinning, I'm spinning you up
I'm spinning, I'm spinning, I'm spinning you up
I'm spinning, I'm spinning, I'm spinning you up
I'm spinning, I'm spinning, I'm spinning you up


Just hide, ooh!
You know that you're the one that's terrified, ooh
Just hide, ooh!
You know that you're the one that's terrified, ooh


No, no, no, no, no, no, no, please
Ooh-oh, no, no, no, ooh!
Oh, you can't run from me
You can't hide from me""",
    },
    "CG_09": {
        "title":  "Heartbeat",
        "artist": "Childish Gambino",
        "lyrics": """I wanted you to know
That I am ready to go, heartbeat
My heartbeat
I wanted you to know
Whenever you are around, can't speak
I can't speak
I wanted you to know
That I am ready to go, heartbeat
My heartbeat
I wanted you to know
Whenever you are around, can't speak
I can't speak


I know what your boy like
Skinny tie and a cuff type
He go and make breakfast
You walkin' round naked
I might just text you
Turn your phone over
When it's all over, no settlin' down
My text go to your screen, you know better than that
I come around when you least expect me
I'm sittin' at the bar when your glass is empty
You thinkin' that this song's comin' on to tempt me
I need to be alone like the way you left me
You start callin', you start crying
I come over, I'm inside you
I can't find you, the girl that I once had
But the sex that we have isn't half bad
Text say that "It's not fair"
That's code for "He's not here"
And I'ma flirt with this new girl
And I'ma call if it don't work
So we fuck 'til it come to conclusions
All the things that we thought we were losin'
I'm a ghost and you know this
That's why we broke up in the first place
'Cause


I wanted you to know
That I am ready to go, heartbeat
My heartbeat
I wanted you to know
Whenever you are around, can't speak
I can't speak
I wanted you to know
That I am ready to go, heartbeat
My heartbeat
I wanted you to know
Whenever you are around, can't speak
I can't speak


It's late-night Thursday
I know that you heard me
But you don't want the same thing, hm
Well, two can play that game
So I'm chillin' with my girlfriend
But she not my real girlfriend
She got a key to my place but
She not my real girlfriend
Stupid, so dummy
Say the wrong thing and wrong girls come runnin'
I'm paranoid that these girls want somethin' from me
And it's hard to make a dime go one-hunnid
And my dude freakin' out over a worse fate
She on time, but she late for they first date
'Cause he went and tried out a new condom
Slipped off in a threesome, good problems?
Right? Wrong
Askin' 'em if she'd wanna play games
We the Super Smash Brothers, but none of 'em you
I miss the sex where you kiss whenever you through
Sixty-nine is the only dinner for two
I was wrong, but would you have listened to you?
Uh, you were crazy
I got a heart, but the art of choking's
Only thing girls want when you in that smoke and light


I wanted you to know
That I am ready to go, heartbeat
My heartbeat
I wanted you to know
Whenever you are around, can't speak
I can't speak
I wanted you to know
That I am ready to go, heartbeat
My heartbeat
I wanted you to know
Whenever you are around, can't speak
I can't speak


So we're done? This the real shit?
We used to hold hands like field trips
I'm a jerk, but your dude is a real dick
I read his posts on your wall and I feel sick
He ain't cool, he ball and all that
But he just a fake nigga who blog in all caps
You couldn't wait to date
I'm goin' straight for your thighs like the cake you ate
I give a fuck about the niggas that you say you ate
You know that I'm the best when I'm a-fake-tionate
I'm the best that you had, face it
J and Keyshia are related, racist
I give you money, then you burn me, then you made off
She ain't a killer, but she'd fuckin' blow your head up
I know he wonderin', "What the fuck you hidin'?"
That we dated like raps about Bin Laden
Ayo, fuck this
Are we datin'? Are we fuckin'?
Are we best friends? Are we somethin'
In between that?
I wish we never fucked, and I mean that


But not really
You say the nastiest shit in bed and it's fuckin' awesome""",
    },
    "CG_10": {
        "title":  "Outside",
        "artist": "Childish Gambino",
        "lyrics": """I used to dream every night, now I never dream at all
I'm hopin' that it's 'cause I'm livin' everything I want
I used to wake up in a bed between my mom and aunt
Playing with this 
Land Before Time
 toy from Pizza Hut
My dad works nights, putting on a stone face
He's saving up so we can get our own place
In the projects, man, that sound fancy to me
They called me "fat nose," my mom say, "You handsome to me"
Mrs. Glover, ma'am, your son is so advanced
But he's acting up in class and keeps peeing in his pants
And I just wanna fit in, but nobody was helping me out
They talking hood shit and I ain't know what that was about
'Cause hood shit and black shit is super different
So I'm talking hood shit and cool, it now like New Edition
Mom and dad wouldn't listen
They left the Bronx so I wouldn't be that
All their friends in NY deal crack
It's weird, you think that they'd be proud of 'em
But when you leave the hood
They think that you look down on 'em
The truth is we still struggle on a different plane
7 dollars an hour, WIC vouchers, it's all the same
Facebook messaging hopin' that could patch up shit
But all they get now is, "Can your son read this script?"


There's a world we can visit if we go outside
Outside, outside—we can follow the road
There's a world we can visit if we go outside
Outside, outside—no one knows
There's a world we can visit if we go outside
Outside, outside—we can follow the road
There's a world we can visit if we go outside
Outside, outside—no one knows


Yeah, Dad lost his job, mama worked at Mrs. Winner's
Gun pulled in her face, she still made dinner
“Donald, watch the meter so they don’t turn the lights off"
Workin' two jobs so I can get into that white school
And I hate it there
They all make fun of my clothes and wanna touch my hair
And my uncle on that stuff that got my grandma shook
Drug dealers roughed him up and stole his address book
He’s supposed to pay ‘em back
He owe 'em money but his bank account is zero
So my mama made us sleep with Phillips heads
Under the pillow, like that would do somethin'
But she got six kids, she gotta do somethin'
She don’t want me in a lifestyle like my cousin
And he mad 'cause his father ain’t around
He lookin' at me now, like
"Why you so fuckin' lucky? I had a father too
But he ain’t around, so I'ma take it out on you"
We used to say "I love you," now we only think that shit
It feels weird that you’re the person I took sink baths with
Street took you over, I want my cousin back
The world sayin' what you are
Because you’re young and black, don't believe 'em
You're still that kid who kept the older boys
From teasin', for some reason


There's a world we can visit if we go outside
Outside, outside—we can follow the road
There's a world we can visit if we go outside
Outside, outside—no one knows
There's a world we can visit if we go outside
Outside, outside—we can follow the road
There's a world we can visit if we go outside
Outside, outside—no one knows


Can you hear me now?
Can you hear me now?
Oh, help us, Lord
Oh, I'm screamin' baby, baby""",
    },
    "CG_11": {
        "title":  "telegraphs",
        "artist": "Childish Gambino",
        "lyrics": """I was making Japanese and she's watching DVDs
In Oakland, in Oakland
Now I'm driving up the 5 and she waits til' I arrive
In Oakland, in Oakland
Everything that I wanted
Only gotta drive for the moment
If you tell me "turn around," then I'm on it
For the moment, but you know me
You know how I get when I'm lonely
And I think about you and the moments
But everything you do is so Oakland, so Oakland


Foot on the gas
I'm just trying to pass
All the red lights
And the stop signs
I'm ready to go
Before I get to The Bay
Babe, that's a problem
Because I'm way too scared to call
And you might get me to stay, and oh


I don't really mind the drive
But I think I'd rather die
In Oakland, in Oakland
With my hands on two and ten
So I guess it all depends
On Oakland, on Oakland
And I'm nervous, truth be told
I never saw me growing old
In Oakland, in Oakland
And if I married you tonight
It would probably start a riot
In Oakland, in Oakland


Everything, that I needed
Now that I got you in your feelings
Everything you won't say, you tweet it
And a nigga don’t like that shit at all
So treated
Can we just roll with the feeling?
Can we just roll for a minute?
Wait a minute


Foot on the gas
I'm just tryna pass
All the red lights
And the stop signs
I'm ready to go
But I'm really not ready, girl
That's a problem
'Cause I'm way too scared to fall
And I know you choose to stay, and oh oh


All the girlfriends saying, "Here we go again" (Go again)
Rich kid but he act like a gentleman (Gentlemen)
Last one didn't end like it should've been (Shoulda been)
Two dates and he still wanna get it in
And they're sayin' it's because of the Internet
Try her once and it's on to the next chick
X-O the O face on your exes, right?
And we can do the same thing if you wanna have at it
When your thoughts can't breathe and you thinking asthmatic
And you wanna be a mom and I wasn't mad at it
I was thinking 'bout me, I'd be really bad at it
'Cause I'm thinking 'bout me, (Oh) weeks in Dubai
Fourth of July, house in Kauai, yeah we can try
So let's try


(Say some things)
Whoa
Whoa
I took off my nine to five
But you still don't have the time to kiss me, just hit me
And if I left you all alone, would you still pick up the phone?
It's iffy, you miss me
I got furniture to move
And we'll both be thirty soon
In Oakland, in Oakland
The only one I know is you, so the fuck I'm supposed to do?
In Oakland, in Oakland
In Oakland, in Oakland
In Oakland, in Oakland
In Oakland, in Oakland
In Oakland, in Oakland
In Oakland, in Oakland""",
    },
    "CG_12": {
        "title":  "California",
        "artist": "Childish Gambino",
        "lyrics": """She want to move to California
She must've fucking lost her mind
She want to move to California
That's how they get you every time
She make a movie with her friends
Put it up in a minute
Everybody say it now
Ain't no loop at the minute
Everybody saying
"How, how you do it, you did it?"
I'ma show you what it done
But enough for a finish
Pay attention, you listen
You keep losing your mind
How you want to loop this shit
But looking like a Vine?


But they no pay for no privilege
Now she broke in Koreatown
In the condo you rented
Better get your percentage


In California, oh
She must've fucking lost her mind, yeah
He want to move to California
He want to hang with DC Fly


All the people all around and the follower people
I go watching a "haha," make a girlfriend giggle
Make her feel so official, make it Serena Vista
Supernova, new residual, making money a little
Make the smoker illegal
Make the living illegal
Make the laughing illegal
Make it snap for a people
When you make a movie now
Know you making no difference
It's a tickle on the mind
'Fore me finish your sentence


So go pimp a like on Vine
But don't pay for the privilege
Now you broke in Koreatown
In the condo you rented
Better get your percentage
Oh, you broke in Koreatown
In that condo you rented
Better get your percentage


In California
She must've fucking lost her mind, yeah
I want to move to California
I want to hang with DC Fly""",
    },
}
