# Auto-generated by 03_build_schema.py — do not edit manually.
# Artist: Chance the Rapper  |  Code: CH
# Songs included: 12  |  Missing: 0

CH_SCHEMA = {
    "CH_01": {
        "title":  "Blessings",
        "artist": "Chance the Rapper",
        "lyrics": """I'm gon' praise Him, praise Him 'til I'm gone
I'm gon' praise Him, praise Him 'til I'm gone
When the praises go up, 
the blessings come down
When the praises go up, the blessings come down
It seems like blessings keep falling in my lap
It seems like blessings keep falling in my lap


I don't make songs for free, I make 'em for freedom
Don't believe in kings, believe in the Kingdom
Chisel me into stone, prayer whistle me into song air
Dying laughing with Krillin saying something 'bout blonde hair
Jesus' black life ain't matter, I know, I talked to his daddy
Said you the man of the house now, look out for your family
He has ordered my steps,  gave me a sword with a crest
And gave Donnie a trumpet in case I get shortness of breath


I'm gon' praise Him, praise Him 'til I'm gone
 (Don't be mad)
I'm gon' praise Him, praise Him 'til I'm gone
When the praises go up (Good God)
The blessings come down
, Good God
When the praises go up (Good God) the blessings come down
(The blessings come down)
When the praises go up, the blessings come down
(It seems like blessings keep falling in my lap)
The blessings come down
When the praises go up, the blessings come down
(Good God)


They booked the nicest hotels on the 59th floor
With the big wide windows, with the suicide doors
Ain't no blood on my money, ain't no Twitter in Heaven
I know them drugs isn't close, ain't no visitin' Heaven
I know the difference in blessings and worldly possessions
Like my ex-girl getting pregnant
And her becoming my everything
I'm at war with my wrongs, I'm writing four different songs
I never forged it or forfeited, I'm a force to be reconciled
They want four-minute songs
You need a four-hour praise dance performed every morn
I'm feeling shortness of breath, so Nico grab you a horn
Hit Jericho with a buzzer beater to end a quarter
Watch brick and mortar fall like dripping water, ugh
(Good God)


I'm gon' praise Him, praise Him 'til I'm gone
(Good God)
I'm gon' praise Him, praise Him 'til I'm gone
When the praises go up, (Good God) the blessings come down
(The blessings come down)
When the praises go up, the blessings come down
(The blessings come down)
When the praises go up, the blessings come down
(Are you ready for your blessings?)
When the praises go up, the blessings come down
(Are you ready for your miracle?)

Are you ready, are you ready?
Are you ready, are you ready?
Are you ready, are you ready?
Are you ready, are you ready?
It seems like blessings keep falling in my lap""",
    },
    "CH_02": {
        "title":  "No Problem",
        "artist": "Chance the Rapper",
        "lyrics": """You don't want zero problems, big fella!
Yep! Igh!


If one more label try to stop me
It's gon' be some dreadhead niggas in ya lobby, huh huh


You don't want no problem, want no problem with me, bih
You don't want no problem, want no problem with me, huh, haha
Just another day, had to pick up all the mail
There go Chano ridin' through the streets, they be like, "There he go!"
You don't want no problem, want no problem with me, bih
You don't want no problem, want no problem with me, huh, haha
Just another day, had to pick up all the mail
There go Chano ridin' through the streets, they be like, "There he go!"


Ooh, watch me come and put the hinges in their hands
Countin' Benjis while we meetin', make 'em shake my other hand, huh
Milly rockin', scoopin' all the blessings out my lap
Bitch I know you tried to cheat, you shoulda never took a nap, hey
Fuck wrong with you? What you were thinkin'?
Fuck you thought it was?
You talk that talk that make a lame-ass nigga fall in love
Not me, though, bitch, you can keep those
Bruh, I'm at your head like Craig did Deebo
Don't tweak, bro, it's never sweet, ho
My shooters come for free, so


If one more label try to stop me
It's gon' be some dreadhead niggas in ya lobby, huh, huh


You don't want no problem, want no problem with me, you bih
You don't want no problem, want no problem with me, huh, haha
Yep, yep
Pull up in the new thing, I'm like
You don't want no problem, want no problem with me, bih
You don't want no problem, want no problem with me, huh, haha
You don't want no problem, want no problem with me, bih
You don't want no problem, want no problem with me, huh, haha
(
Yeah, 2 Chainz
)
They be like, "There he go!"


You old Petey Pablo, take your shirt off
Wave 'round your head like a helicopter
I ain't put enough weed in the blunt
All you do is smoke tobacco
Where the hell you get them from?
Yeezy said he ain't make them
My niggas chasin' bounty hunters
And gettin' chased by their baby mamas
My first tat was on my stomach
Got a pocket full of money (Money)
And a mind full of ideas
Some of this shit may sound weird
Inside of the Maybach
Look like it came out of Ikea
Run shit like diarrhea (True)
Big yacht, no power steering (Yeah)
Aye, aye, captain (Ooh!)
I'm high, captain (A-alright!)
I'm so high (I'm so high)
Me and God dappin' (Alright)
This is my blessin' (Yeah)
This is my passion
School of hard knocks
I took night classes


You don't want no problem, want no problem with me, bih
You don't want no problem, want no problem with me, huh, haha
Yep
Pull up in the new thing, I'm like
They be like, "There he go!"


I got problems bigger than these boys, yeah
My deposits, they be on steroids
Lord, free the Carter, niggas need the Carter
Sacrificin' everything, I feel like Jesus Carter
Hold up, I got this sewed up, my soda poured up
My woes up, I'm flippin' those bucks, they doing toe tucks
I rolled up and let the smoke puff
I lay down, toes up
Hold up, get too choked up when I think of old stuff
Move on, put my goons on, they kidnap newborns
In the streets my face a coupon
Her pussy too warm
All these bitches come to do harm
Just bought a new charm
Fuck the watch, I buy a new arm, you lukewarm
I'm Uncle Luke with the hoes
Pretty bitches, centerfolds
Tippy toes around my crib in they robes, just their robes
Half a milli' in the safe, another in the pillowcase
Codeine got me movin' slower than a caterpillar race
Fuck wrong with you? What you were thinkin'?
What you thought it was?
I just popped five Percocets and only caught a buzz
And if that label try to stop me
There gon' be some crazy Weezy fans waitin' in the lobby
Mula, baby


You don't want no problem, want no problem with me, bih
You don't want no problem, want no problem with me, huh, haha
Just another day, had to pick up all the mail
There go Chano ridin' through the streets, they be like, "There he go!"
You don't want no problem, want no problem with me, bih
You don't want no problem, want no problem with me, huh, haha
Just another day, had to pick up all the mail
There go Chano ridin' through the streets, they be like, "There he go!"


You don't want no problem, want no problem with me
You don't want no problem, want no problem with me
You don't want no problem, want no problem with me
You don't want no problem, want no problem with me
You don't want no problem, want no problem with me
You don't want no problem, want no problem with me
They say so, ridin' with the payo'
They be like, "There he go!"
There he go""",
    },
    "CH_03": {
        "title":  "Same Drugs",
        "artist": "Chance the Rapper",
        "lyrics": """We don't do the same drugs no more
We don't do the, we don't do the same drugs, do the same drugs no more
'Cause she don't do the same drugs no more
We don't do the, we don't do the same drugs, do the same drugs no more


When did you change?
Wendy, you've aged
I thought you'd never grow up
I thought you'd never
Window closed, Wendy got old
I was too late, I was too late
A shadow of what I once was


'Cause we don't do the same drugs no more
We don't do the, we don't do the same drugs, do the same drugs no more
She don't laugh the same way no more
We don't do the, we don't do the same drugs, do the same drugs no more


Where did you go?
Why would you stay?
You must have lost your marbles
You always were so forgetful
In a hurry, don't wait up
I was too late, I was too late
A shadow of what I once was
'Cause we don't, we don't do what we say we're gonna
You were always perfect, and I was only practice
Don't you miss the days, stranger?
Don't you miss the days?
Don't you miss the danger?


We don't (
We don't
) do the same drugs no more (
Do the same drugs no more
)
We don't do the, we don't do the same drugs, do the same drugs no more
We don't (
We don't
) do the same drugs no more (
Do the same drugs no more
)
We don't do the, we don't do the same drugs, do the same drugs no more
We don't do the, we don't do the same drugs


Turn it around
I remember when
This age of pathetics
Don't forget the happy thoughts
All you need is happy thoughts
The past tense, past bed time
Way back then when everything we read was real
And everything we said rhymed
Wide eyed kids being kids
Why did you stop?
What did you do to your hair?
Where did you go to end up right back here?
When did you start to forget how to fly?
It's so natural
Tastes like Juicy Fruit
Works like a magic trick
Please give me half of that
We don't, we don't, we don't
Don't you color out
Don't you bleed on out, oh
Stay in the line, stay in the line
Dandelion
We don't do the same drugs no more
We don't do the, we don't do the same drugs, do the same drugs no more
We don't, we don't, we don't
Don't you color out
Don't you bleed on out, oh
Stay in the line, stay in the line
Dandelion""",
    },
    "CH_04": {
        "title":  "Angels",
        "artist": "Chance the Rapper",
        "lyrics": """Angels (Na-na, na-na, ah)


I got my city doing front flips
When every father, mayor, rapper jump ship
I guess that's why they call it where I stay
Clean up the streets so my daughter can have somewhere to play
I'm the blueprint to a real man
Some of these niggas toss they tassel for a deal, man
I ain't goin' to hell or to Hillman
Ah, ah, ah, ah for my real fans
I got caught up with a little Xan
Couldn't stop me, but it slowed me, though
Yeah, a nigga famous, you don't know me though
But every DJ still play me, though
Damn, I don't even need a radio
And my new shit sound like a rodeo
Got the old folks dancing the do-si-do
'Til they fuck around, sign me to OVO
Ooh, I just might share my next one with Keef
Got the industry in disbelief, they be asking for beef
This what it sound like when God split a atom with me
I even had Steve giving out apples for free


They was talkin', "Woo, this woo wap da bam"
City so damn great, I feel like Alexand'
Wear your halo like a hat, that's like the latest fashion
I got angels all around me, they keep me surrounded


Who is you, and who the fuck is you and who is him?
All of a sudden, woo wap da bam, you can't touch me
Na, na, na, na, I got angels
I got angels


I ain't change my number since the seventh grade
This for my day one, ten years, seven days
A week, niggas never tired on they Kevin Gates
And if they rest in peace, they bunny hopping Heaven's gates
It's too many young angels on the southside
Got us scared to let our grandmamas outside
You gon' make me take the campers way downtown
You gon' make me turn my BM to my housewife
I just had a growth spurt
It done took so long, my tippy toes hurt
You can keep the nose ring, I don't have to soul search
I'm still at my old church, only ever sold merch
Grandma say I'm Kosher, mama say I'm culture
GCI, 107.5, angel goin' live
Power 92, angel, juke, angel gon' juke
GCI, 107.5, goin' live
Power 92, angel gon' juke, juke, juke, juke


They was talkin', "Woo, this woo wap da bam"
City so damn great, I feel like Alexand'
Wear your halo like a hat, that's like the latest fashion
I got angels all around me, they keep me surrounded

Wap da bam (Na, na, na, na)
I got (I got angels)
I got angels all around me, they keep me surrounded
Na, na, na, na
I got, I got angels


They was talkin', "Woo, this woo wap da bam"
City so damn great, I feel like Alexand'
Wear your halo like a hat, that's like the latest fashion
I got angels all around me, they keep me surrounded


Who is you, and who the fuck is you and who is him?
All of a sudden, woo wap da bam, you can't touch me
Na, na, na, na, I got angels
I got, I got angels


Na, na
Na, na
I got, I got—""",
    },
    "CH_05": {
        "title":  "Paranoia",
        "artist": "Chance the Rapper",
        "lyrics": """Ten damn days
And all I got to show for it is shoes and shows
And chauffeurs with road rage
Still the same damn ad-lib, "Igh," old ways
Still got a letterman, no practice
Still got a burner, man, no lacking
Still outtin' Jams nigga, no Jackson
No Jordan, and we toe-tagging
I'll take you to the land where the lake made of sand
And the milk don't pour, and the honey don't dance
And the money ain't yours
Now it's just a red pill
Got a blue and a handful of Advils
I'm the new Nitty, fuck it, Nitty the old me
So I'ma tell the buyer what Nitty told me, igh


I got that mmm, mmm, I got that goddamn
I'm your pusha man, I'm your, I'm your pusha man
Pimp slappin', toe taggin', I'm just tryna fight the man
I'm your pusha man, I'm your, I'm your pusha man
I got that mmm, mmm, I got that goddamn
I'm your pusha man, I'm your, I'm your pusha man
Pimp slappin', toe taggin', I'm just tryna fight the man
I'm your pusha man, I'm your, I'm your pusha man
Pimp slappin', toe taggin', I'm just tryna fight the man
I'm your pusha man, I'm your, I'm your pusha man


You a lame
And your bitch break down my weed sometimes
See my face in the streets, in the tweets
And a Reader or a RedEye if you read Sun-Times
She got blisters on her knees, she's a fiend for the D
Even though I only beat one time
One time, it was one two times
It was two plus me equals threesome time
Shouts out to Nate, I jackball, and I bop, I flex
Got neck from all these thots I sex
Rastafari them shottas, yes
House safari, mi casa, yes
Poppy fields of that popeye
She came to party, she popped a molly
Said, "Come to papá," she said, "Papá, yes"


I got that mmm, mmm, I got that goddamn
I'm your pusha man, I'm your, I'm your pusha man
Pimp slappin', toe taggin', I'm just tryna fight the man
I'm your pusha man, I'm your, I'm your pusha man
I got that mmm, mmm, I got that goddamn
I'm your pusha man, I'm your, I'm your pusha man
Pimp slappin', toe taggin', I'm just tryna fight the man
I'm your pusha man, I'm your, I'm your pusha man, igh






I've been riding around with my blunt on my lips
With the sun in my eyes and my gun on my hip
Paranoia on my mind, got my mind on the fritz
But a lot of niggas dyin', so my 9 with the shits
I've been riding around with my blunt on my lips
With the sun in my eyes and my gun on my hip
Paranoia on my mind, got my mind on the fritz
But a lot of niggas dyin', so my 9 with the shits


Move to the neighborhood, I bet they don't stay for good, watch
Somebody'll steal daddy's Rollie, call it the neighborhood watch
Pray for a safer hood when my paper good, watch
Captain Save-a-Hood, hood savior, baby boy
Still getting ID'd for Swishers (Mama still wash my clothes)
Still with the Save Money militia (I'ma still watch my bros)
Trapped in the middle of the map
With a little-bitty rock and a little bit of rap
That, with a literary knack
And a little-shitty Mac, and like literally jack


I've been riding around with my blunt on my lips
With the sun in my eyes and my gun on my hip
Paranoia on my mind, got my mind on the fritz
But a lot of niggas dyin', so my 9 with the shits
I've been riding around with my blunt on my lips
With the sun in my eyes and my gun on my hip
Paranoia on my mind, got my mind on the fritz
But a lot of niggas dyin', so my 9 with the shits


They murking kids, they murder kids here
Why you think they don't talk about it? They deserted us here
Where the fuck is Matt Lauer at?
Somebody get Katie Couric in here
Probably scared of all the refugees
Look like we had a fuckin' hurricane here
They'll be shooting whether it's dark or not
I mean, the days is pretty dark a lot
Down here, it's easier to find a gun
Than it is to find a fucking parking spot
No love for the opposition, specifically a cop position
'Cause they've never been in our position
Getting violations from the nation, correlating, you dry snitchin'


I've been riding around with my blunt on my lips
With the sun in my eyes and my gun on my hip
Paranoia on my mind, got my mind on the fritz
But a lot of niggas dyin', so my 9 with the shits
I've been riding around with my blunt on my lips
With the sun in my eyes and my gun on my hip
Paranoia on my mind, got my mind on the fritz
But a lot of niggas dyin', so my 9 with the shits


I know you scared
You should ask us if we scared, too
I know you scared
Me too
I know you scared
You should ask us if we scared, too
If you was there
Then we'd just knew you cared, too


It just got warm out, this the shit I've been warned 'bout
I hope that it storm in the mornin', I hope that it's pourin' out
I hate crowded beaches, I hate the sound of fireworks
And I ponder what's worse
Between knowing it's over and dyin' first
'Cause everybody dies in the summer
Wanna say your goodbyes, tell them while it's spring
I heard everybody's dying in the summer
So pray to God for a little more spring


I know you scared
You should ask us if we scared, too
If you was there
Then we'd just knew you cared, too""",
    },
    "CH_06": {
        "title":  "Sunday Candy",
        "artist": "Chance the Rapper",
        "lyrics": """She could say in her voice
In her way that she love me
With her eyes, with her smile
With her belt, with her hands, with her money
I am the thesis of her prayers
Her nieces and her nephews are just pieces of the layers
Only ones she love as much as me is Jesus Christ and Taylor
I got a future so I'm singing for my grandma
You singing too, but your grandma ain't my grandma
Mine's hand made, pan fried, sun dried
Southside, and beat the devil by a landslide
Praying with her hands tied, president of my fan club, Santa
Something told me I should bring my butt to church


You gotta move it slowly
Take and eat my body like it's holy
I've been waiting for you for the whole week
I've been praying for you you're my Sunday candy
You gotta move it slowly
Take and eat my body like it's holy
I've been waiting for you for the whole week
I've been praying for you you're my Sunday Candy
Come on in this house, cause it's gonna rain
Rain down Zion, it's gonna rain
You better come on in this house, cause it's gonna rain
Rain down Zion, it's gonna rain


I come to church for the candy, your peppermints is the truth
I'm pessimistic on Monday if I had tweaked and missed you
You look so good with that hat on, had to match with the shoes
Came and dressed in the satin, I came and sat in your pew
I come to Christmas for dinner, fifty rolls on my plate
Hella holes in my stocking holding your pockets in place
I like my love with a budget, I like my hugs with a scent
You smell like light, gas, water, electricity, rent
You sound like why the gospel got so tired
Singin' his praises daily basis so I gotta try it
You're my dreamcatcher, dream team, team captain
Matter fact, I ain't seen you in a minute let me take my butt to church


You better come on in this house
(Come on in this house)
Cause it's gonna rain
(It's gonna rain)
Rain down Zion
(Rain down)
Cause it's gonna rain
(It's gonna rain)
You better come on in this house
(Come on in this house)
Cause it's gonna rain
(It's gonna rain)
Rain down Zion
(Rain down, IGH!)
It's gonna rain


You gotta move it slowly
Take and eat my body like it's holy
I've been waiting for you for the whole week
I've been praying for you you're my Sunday Candy
You gotta move it slowly
Take and eat my body like it's holy
I've been waiting for you for the whole week
I've been praying for you you're my Sunday Candy
Slowly
Take and eat my body like it's holy
I've been waiting for you for the whole week
I've been praying for you you're my Sunday Candy
You better come on in this house
(Come on in this house)
Cause it's gonna rain
(It's gonna rain)
Rain down Zion
(Rain down)
It's gonna rain
(Its gonna rain)
You better come on in this house
(Come on in this house)
Cause it's gonna rain
(Its gonna rain)
Rain down Zion
(Rain down)
It's gonna rain""",
    },
    "CH_07": {
        "title":  "Favorite Song",
        "artist": "Chance the Rapper",
        "lyrics": """Chance, acid rapper, soccer, hacky sacker
Cocky khaki jacket jacker
Slap-happy faggot slapper, bah-bah
Iraqi rocket launcher
Shake that Laffy Taffy, jolly raunchy rapper
Dang, dang, dang, skeet, skeet, skeet
She do that thing for three retweets
The album feel like '92
Now take that ball 'fore he three-peat
Chance, ho, acid, cruising on that LSD
Asked Joseph about my deal
He looked back said, "Hell yeah, let's eat"


This shit my favorite song, you just don't know the words
But I still fuck with you, you just ain't never heard
It go like, count that stack, pop that cap then down that Jack
All my niggas hit that xan, and all my ladies bob that back
This my jam, this my jam, this my jam, this my jam
I'm 'bout that jam, I'm 'bout that jam, I'm 'bout that jam, I'm 'bout that jam
This my jam, this my jam, this my jam, this my jam
I'm 'bout that jam, I'm 'bout that jam, I'm 'bout that jam, I'm bout that jam


Young Rascal Flatts, young ass kid ass could rap
Fuck all the faculty, tobacco-packing acrobat
Back-to-back packin' bags back and forth with fifths of Jack and
Fourths of weed, I'm back to pack on hands
With young Cletus to pat my back
Real nigga with a nose ring, that's right
Just here to rap them songs
Rag on my hair, wrap weed in Vegas, rockin' Vagabonds
Sang a song, oh, you don't know? What?
Well, I still bang with you
Hang with you, sip drank with you
As long as I can sang with you like


This shit my favorite song, you just don't know the words
But I still fuck with you, you just ain't never heard
It go like, count that stack, pop that cap then down that Jack
All my niggas hit that xan, and all my ladies bob that back
This my jam, this my jam, this my jam, this my jam
I'm 'bout that jam, I'm 'bout that jam, I'm 'bout that jam, I'm 'bout that jam
This my jam, this my jam, this my jam, this my jam
I'm 'bout that jam, I'm 'bout that jam, I'm 'bout that jam, I'm bout that jam


Niggas, please be focused, that Bino, you know this
He rep the home of Sosas, you know I'm from that Zone 6
You know I rep that Stone shit, you know your hood is so clit
As God as my witness, this Will Smith spit real shit
I'ma be that, CG busy gettin', where the weed at?
Bought your girl some new kneepads
You're fuckin' with the Fifi bag
My stars, egad, she said, "This my favorite song"
"Hold my purse", now she on the floor, droppin' like it's hot
You blast this shit in Abercrombie when your work is finished
Your mom won't play it in the car 'cause it got cursing in it
Your boy like, "I'm the one who showed you"
He want his percentage
'Cause you were like, "This ain't the nigga you said spittin', is it?"
Two-step, white dude's Harlem Shake
Why you laughing? 'Cause you Harlem Shake
I was never fake, I was just too good to be true
That's acid rap, we killed the track
You had your chance, and 'Bino too, ooh


This shit my favorite song, you just don't know the words
But I still fuck with you, you just ain't never heard
It go like, count that stack, pop that cap then down that Jack
All my niggas hit that xan, and all my ladies bob that back
This my jam, this my jam, this my jam, this my jam
I'm 'bout that jam, I'm 'bout that jam, I'm 'bout that jam, I'm 'bout that jam
This my jam, this my jam, this my jam, this my jam
I'm 'bout that jam, I'm 'bout that jam, I'm 'bout that jam, I'm bout that jam""",
    },
    "CH_08": {
        "title":  "All We Got",
        "artist": "Chance the Rapper",
        "lyrics": """And we back
And we back, and we back, and we back, and we back, and we, huh
And we back, and we back, nah, nah, nah


Hey, this ain't no intro, this the entree
Hit that intro with Kanye and sound like André
Tryna turn my baby mama to my fiancée
She like music, she from Houston like Auntie Yoncé
Man my daughter couldn't have a better mother
If she ever find another, he better love her
Man I swear my life is perfect, I could merch it
If I die I'll prolly cry at my own service, igh-igh!
It was a dream, you could not mess with the Beam
This is like this many rings
Y'all know wha' mean?
This for the kids of the king of all kings
This is the holiest thing
This is the beat that played under the Word
This is the sheep that ain't like what it heard
This is officially first
This is the third


This is the bom-bom-bom
Bom-bom-bom
Bom-bom-bom
Music is all we got
Oh, bom-bom-bom
So we might as well give it all we got
This is the bom-bom-bom (
Huh
)
Bom-bom-bom
Bom-bom-bom
Music is all we got
, got, got
Oh, bom-bom-bom
So we might as well give it all we got


Ayy, ayy, I get my word from the sermon
I do not talk to the serpent
That's the holistic discernment
Daddy said I'm so determined
Told me these goofies can't hurt me
I just might make me some Earl tea
I was baptized like real early
I might give Satan a swirlie
Wish I could tell you it's ready
Tell you it's ready today
They don't give nothin' away
You gotta fight for your way
And that don't take nothin' away
'Cause at the end of the day


Music is all we got
Music is all we got
Music is all we got
Oh, bom-bom-bom
So we might as well give it all we got
Music is all we got (
Huh, huh
)
Music is all we got (
Huh, huh
)


We know, we know we got it
We know, we know we got it
We know, we know we got it
We know, we know we got it
Music
We know, we know we got it
We know, we know we got it
We know, we know we got it
We know, we know we got it
Music
Music is all we got""",
    },
    "CH_09": {
        "title":  "Cocoa Butter Kisses",
        "artist": "Chance the Rapper",
        "lyrics": """Na-na-na-na-na-na-na-na-na-na, igh
Na-na-na-na-na-na-na-na-na-na, igh


Cigarettes on cigarettes, my mama think I stank
I got burn holes in my hoodies, all my homies think it's dank
I miss my cocoa butter kisses
I miss my cocoa butter kisses
Cigarettes on cigarettes, my mama think I stank
I got burn holes in my hoodies, all my homies think it's dank
I miss my cocoa butter kisses (Kisses, kisses)
I miss my cocoa butter kisses


Okie dokie, alkie, keep it low-key like Thor lil' bro
Or he'll go blow the loudy, saudy of sour Saudi
Wiley up off peyote, wilin' like that coyote
If I sip any Henny, my belly just might be outie
Pull up inside a huggy, Starsky & Hutch a dougie
I just opened up the pack, in an hour I'll ash my lucky
Tonight she just yelling "Fuck me"
Two weeks she'll be yelling "Fuck me"
Used to like orange cassette tapes with Timmy, Tommy, and Chuckie
And Chuck E. Cheese's pizzas, Jesus pieces, sing Jesus love me
Put Visine inside my eyes so my grandma would fucking hug me
Oh, generation above me, I know you still remember me
My afro look just like daddy's, y'all taught me how to go hunting, blam


Cigarettes on cigarettes, my mama think I stank
I got burn holes in my hoodies, all my homies think it's dank
I miss my cocoa butter kisses (Kisses, kisses)
I miss my cocoa butter kisses
Cigarettes on cigarettes, my mama think I stank (Innanet)
I got burn holes in my hoodies, all my homies think it's dank
I miss my cocoa butter kisses (Kisses, kisses)
I miss my cocoa butter kisses (Innanet)
(Kisses, kisses)


I will smoke a little something but I don't inhale
Everywhere that I go, everywhere, they be asking how's it going
Say the going's well, go figure, Victor's light skinned
Jesus got me feeling like Colin Powell, all praise to the God
God knows he's a pro, he's a pro like COINTEL
Check, checkmate, check me, take me to the bedroom
Like she know me well, I mean normally
You see Norma Jean wouldn't kick it with Farmer Phil
But these kids these days, they get so high
Burn trees, smoke chlorophyll, 'til they can't feel shit
Shit-faced, faced it, 15 hits on this L
Elevated, train, and the craziest thing
Got me feeling like Lauryn Hill, miseducated, my dick delegated
Rap Bill Bellamy, they said I shoulda never made it
Probably shoulda been dead or in jail
Deadbeat dad, enough of that jazz
Asshole, absinthe, thumpin' that glass
Are we there yet? Ice cubes in a bong
Rip, brain-dead, take a tug and then pass


I think we all addicted
Yeah, I think we all addicted
Really though, I think we all addicted (Yah)
I think we all addicted


Cigarettes on cigarettes, my mama think I stank
I got burn holes in my memories, my homies think it's dank
I miss my cocoa butter kisses (Kisses, kisses)
I think we all addicted (Kisses, kisses)


Cigarettes on cigarettes, my mama think I stank
I got burn holes in my hoodies, all my homies think it's dank
I miss my cocoa butter kisses (Kisses, kisses)
I miss my cocoa butter kisses


I could make a flow, pitter patter with a patter pitter, juicy
Used to be in a jalabiya and a kufi
Trying hard not to be addicted to a groupie
I ended up on an album cover in a Coogi
You see, I be still a God but a goofy
You be flowing about drugs and a Uzi
That's the dual principle, sometimes I'ma be about some hoes
Sometimes I'ma wanna make a movie
And when it come to rapping fast, I'm the Higgs Boson (Yeah)
And though my style freakish
I could still break your body down to five pieces like I did Voltron
'Cause I'm addicted to the craft and I be off a OG
Know me, I'm the Obi-Wan Kenobi of the dope, see (What?)
Never scared of mean spirits, methamphetamine lyrics
Cooler like I'm off of codeine, low key
Don't be so judgmental, even though I'm reminiscing
If I don't know what I miss is
I'ma end up figuring out that it's home
And my mother and my grandmother cocoa butter kisses
This is just a testament to the ones that raised me
The ones that I praise and I'm thanking
I need 'em but the chronic all up in my clothes
And I wanna get a hug, and I can't 'cause I'm stanking
Never too old for a spanking, IGH!


Cigarettes on cigarettes, my momma think I stank
I got burn holes in my memories, my homies think it's dank
I miss my cocoa butter kisses (Kisses, kisses)
I think we all addicted (Kisses, kisses)


Cigarettes on cigarettes, my mama think I stank
I got burn holes in my hoodies, all my homies think it's dank
I miss my cocoa butter kisses (Kisses, kisses)
I miss my cocoa butter kisses (Kisses, kisses)
Cigarettes on cigarettes, my mama think I stank
I got burn holes in my hoodies, all my homies think it's dank
I miss my cocoa butter kisses
I miss my cocoa butter kisses""",
    },
    "CH_10": {
        "title":  "Smoke Again",
        "artist": "Chance the Rapper",
        "lyrics": """Mmm, igh
Acid Rap


I don't even talk to them on the phone again
Leave in the AM, on the road again
So bitch, let's fuck so I can smoke again
I gotta smoke again, I got shit to do
I don't even talk to them on the phone again
Leave in the AM, on the road again
So bitch, let's fuck so I can smoke again
I gotta smoke again, I got shit to do


Who smokin' in my car? It's that nigga Chano
AKA Mr. Bennett, AK Tony Montano
I've got some folks in low end, I got some folks in C-note
AK hundred dinero, you ever seen Casino?
I just got back with 'Bino, I got a bitch but she know
Her friends done did the Dino, that's that Chicago lingo
Flamin' hots with cheese, and a Kiwi Mistic
My dick won't even call her, 'cause she left all that lipstick
Niggas be on dirt, that's why I stay on petty
I know that bangers jam, that's why my hands stay ready
Flip the candy, yum, that's the fucking bombest
Lean all on the square, that's a fuckin' rhombus


I don't even talk to them on the phone again
Leave in the AM, on the road again
So bitch, let's fuck so I can smoke again
I gotta smoke again, I got shit to do
I don't even talk to them on the phone again
Leave in the AM, on the road again
So bitch, let's fuck so I can smoke again
I gotta smoke again, I got shit to do
I don't even talk to them on the phone again
Leave in the AM, on the road again
So bitch, let's fuck so I can smoke again
I gotta smoke again, I got shit to do
I don't even talk to them on the phone again
Leave in the AM, on the road again
So bitch, let's fuck so I can smoke again
I gotta smoke again, I got shit to do


Who's sneaking in the club? That's that young sir rapper
Un-saran wrap the purple, wrap that blunt under after
Smoke all out the window, cops could eat a dick
If you ain't the hitter, you just might be the lick
Flame on, flame on, I'm your bitch's ringtone
She like when I rap raps, but better when I sing songs
No Drake, but I get my Trey on, killin' in the hood like Trayvon
Shoppin' like I got a coupon, savin' like I got a cape on
Cookin' crack in my apron, dressed like a nigga had eight proms
Tell shorty I may change and I made it and I napalm
Trippy shit to watch, drugs while on the clock
Acid on the face, that's a work of art


I don't even talk to them on the phone again
Leave in the AM, on the road again
So bitch, let's fuck so I can smoke again
I gotta smoke again, I got shit to do
I don't even talk to them on the phone again
Leave in the AM, on the road again
So bitch, let's fuck so I can smoke again
I gotta smoke again, I got shit to do
I don't even talk to them on the phone again
Leave in the AM, on the road again
So bitch, let's fuck so I can smoke again
I gotta smoke again, I got shit to do
I don't even talk to them on the phone again
Leave in the AM, on the road again
So bitch, let's fuck so I can smoke again
I gotta smoke again, I got shit to do


Soulo ho-ho twerk somethin' (Soulo)
Throw it back like you tryna hurt somethin' (Soulo)
I'm so def, I ain't ever heard nothin'
My name Herb, take herb, smoke herb (Say word?)
How 'bout you? No dap, but I'll take a pound or two
No doubt like Gwen Stefani's group
Look, let me put my mouth where you potty, boo (Igh)
Yeah, them niggas pissed, need potty training
They movement shit, that's a potty train
She ain't left yet, but she probably came
We kicked it then I score, soccer game (Yeah)
She was a phony goalie, I got great aim though, don't insult me (Don't insult me)
I'll give it to ya straight, this is what she told me
My name Soulo, 'cause I'm the one and only
She only got you as a nigga on the side
That's a nigga on the side of a side bitch, homie
Then we got out a Dodge, like them Dukes of Hazzard
Music and tabs of Lucy, take your chance with this rapper


I don't even talk to them on the phone again
Leave in the AM, on the road again (Soul)
So bitch, let's fuck so I can smoke again
I gotta smoke again, I got shit to do
I don't even talk to them on the phone again
Leave in the AM, on the road again
So bitch, let's fuck so I can smoke again
I gotta smoke again, I got shit to do
I don't even talk to them on the phone again
Leave in the AM, on the road again
So bitch, let's fuck so I can smoke again
I gotta smoke again, I got shit to do
I don't even talk to them on the phone again
Leave in the AM, on the road again
So bitch, let's fuck so I can smoke again
I gotta smoke again, I got shit to do""",
    },
    "CH_11": {
        "title":  "Hot Shower",
        "artist": "Chance the Rapper",
        "lyrics": """Yup, yup, yerp
And then the smoke got me
Hey


I got muscles like Superman trainer, ayy (
Ooh
)
Real, real rare like Super Saiyan manga
I jump stomp-stomp on Lucifer, Satan (Skrrt)
Now I got a few rings on, Jupiter skating (
Yeah, yeah, yeah
)
I meant to say Saturn, switched up the pattern (
Blaow
)
Smoking on some shatter (
Ooh
), got me higher than a ladder (
Ooh
)
Thanks, I'm flattered, my baby mama badder (
Yeah
)
You look like Mick Jagger, oops, the grease splattered (
Ooh, ooh
)
Hot, hot (Ooh), jumping out the grease
It's a whole lotta degrees
'Bout to come up out the fleece, fleece, fleece
Shh, I don't wanna hear a peep (Skrr)
Tryna catch some sleep (Yeah), tryna count some sheep (
Yeah, yeah
)


Hot damn, hot water, hot shower (Brrt)
Hotlanta, smoking green, cauliflower (
Ooh, ooh
)
Tangerine, yeah, I call her sweet and sour (Yeah)
And my lawyer say it's urgent, I'ma call him in a hour


Dude, I just called the plug and his phone was unplugged
I was lookin' at Doug like (Ooh, ooh, ooh)
Dude, that shit don't even make no fucking sense
Like having fuckin' arguments for payin' fifty extra cents for barbecue
Saucing on the workers at McDonald's
I don't wanna sit and argue, Good Burger shoulda taught you (
Yeah, yeah, yeah
)
We all dudes
And I'm all professional and proper
But my baby mama stopped me in a meeting (
Skrrt, skrrt
)
Just to AirDrop me some nudes


Hot damn, hot water, hot shower (Ooh, brrt)
Hotlanta, smoking green, cauliflower (
Ooh, ooh, ooh
)
Tangerine, yeah, I call her sweet and sour
And my lawyer say it's urgent, I'ma call him in a hour (Ooh)


Yeah, hopped off the flight, Louis V, Off-White (Ooh)
I just made a dub and she tryna spend the night, uh (Check)
Heard they need more, yeah, my jeans Dior, uh (Ooh)
Shawty got cake if you tryna eat more (Skrrt, skrrt)
Think they need more
I think they need more, ugh, ooh (Ooh, brrt, ooh)
This the second round, I'm tryna speed more (Ooh, ooh, ooh)
Going stupid, going crazy, uh, uh (Yeah, yeah, yeah)
Big gas in that Mercedes, uh, uh (Ooh, ooh, ooh)
Pull up lit, uh, going 30, uh, uh (Yeah, yeah, yeah)
Pull up Vic, uh, in a hurry, uh, uh (Yeah, yeah, yeah)
Shoot your shot, uh, flex a lot, uh, uh (Ooh, ooh, ooh)
Big cheese, uh, hella knots (Ooh, ooh, ooh)
Chopped and screwed, Michael Watts (Ooh, ooh, ooh)
Point 'em out, air 'em out (Skrrt, skrrt)
Get me right, sippin' Sprite (Skrrt, skrrt)
180, halfpipe (Skrrt, skrrt)
Ooh


Hot damn, hot water, hot shower
Hotlanta, smoking green, cauliflower
Tangerine, yeah, I call her sweet and sour
And my lawyer say it's urgent, I'ma call him in a hour


Goddamn
Think I got a new lawsuit, I need to come see you (What's that?)
I got a new whip, you know what a car do (Vroom)
Turn your bitch to a eater (Mmh, mmh)
She say we don't got enough room to get freaky in here
'Cause it's just a two-seater (Okay, question)
Am I still considered a trick if I get her a hoopty
And buy me a Bimmer? (Uh-uh)
I had a new case but the judge had to throw it out
My lawyer beat it like Tina
I always find a way to get ahead with my intelligence
When they critique my demeanor (Hah)
Today I'll dress up a Republican (What else?)
And go get some head from a white man's daughter
Her lips aren't big but I'm loving it (Mwah)
I get in, fake ID, I'm McLovin it (Yeah)
BDB ENT like the government (What?)
Except for the cops (Who?), mission impossible
Strapped with the Glock, Danny Gloverin' (Pew-pew)
Tip a hundred if you let my cousin in
You know everybody my cousin (Cuz)
Oh yeah, and I gotta be thuggin' it
'Cause my hair can get nappy as fuck
I wear jewelry and I got that chocolate coloring


Well at least, like you know, that's what they make me feel like
Why they make you feel like that?
I don't know, I mean it's America, right?


Ooh, hot damn, hot water, hot shower
Hotlanta, smoking green, cauliflower (Ooh, ooh, ooh)
Tangerine, yeah, I call her sweet and sour
And my lawyer say it's urgent, I'ma call him in a hour""",
    },
    "CH_12": {
        "title":  "I Might Need Security",
        "artist": "Chance the Rapper",
        "lyrics": """Fuck you
Fu-u-u-u-u-uck you, fu-fuck you
Fu-u-u-u-u-uck you, fu-fuck you
Fu-u-u-u-u-uck you, fu-fuck you
Fu-u-u-u-u-uck you, fu-fuck you
 (Yep)
Fu-u-u-u-u-uck you, fu-fuck you
 (Nah-nah)
Fu-u-u-u-u-uck you, fu-fuck you
 (Nah-nah)
Fu-u-u-u-u-uck you, fu-fuck you
 (No)
Fu-u-u-u-u-uck you


I ain't no activist, I'm the protagonist
I don't co-captain it, I fly solo like one cup in the cabinet
The cab is the cabinet, they trust me at landing it
They call me the advocate, they'll slide like the abacus
Boy meets world, everybody been savages
I just want to really know how much that your shooter averages
I'm not no nice guy, I'm just the good guy
The bad guys should really stay on my good side
I smelled my roses younger than the good die
The Illuminati couldn't see me with they good eye
They think they Heath Ledger scary, they just Jack Nichols
I'm a sign to my city like the Bat-Signal
Young chosen one, golden boy, De La Hoya
It ain't too many me's, rest in peace to Verne Troyer
I was younger than I seemed as a kid
I mean my G17 18 in the head
I mean I'm only 25 but I'm Motown 25
Bet I get a statue in my hometown when I die
And Rahm, you done, I'm expectin' resignation
An open investigation on all of these paid vacations for murderers


Fuck you, oh-oh
Fuck you, fuck you
Fu-u-u-u-u-uck you, fuck you-ou-ou-ou
Fu-fu-fu-fu-fu-fu, fu-fu-fu-fu-fu-fu
Fuck you, oh-oh
Fuck you, fuck you
Fu-u-u-u-u-uck you, fuck you-ou-ou-ou
Fu-fu-fu-fu-fu-fu, fu-fu-fu-fu-fu-fu
Fuck you, fu-u-u-u-u-uck you, fu-fuck you
Fu-u-u-u-u-uck you, fu-fuck you
Fu-u-u-u-u-uck you, fu-fuck you
Fu-u-u-u-u-uck you, oh


I don't get no paper, I gotta sign at the bottom
Still in my bag like the fries at the bottom
And I can't do nothing right, they gon' always be at me
I missed a Crain's interview, they tried leaking my addy
I donate to the schools next, they call me a deadbeat daddy
The Sun-Times gettin' that Rauner business
I got a hit-list so long I don't know how to finish
I bought the Chicagoist just to run you racist bitches out of business
Speaking of racist, fuck your microaggressions
I'll make you fix your words like a typo suggestion
Pat me on the back too hard and Pat'll ask for your job
And in unrelated news, someone'll beat your ass at your job
I'm the real deal
Who taught all these rappers that a big deal's not a big deal?
Inherited the earth, popping wheelies on a big wheel
My enemy lives in his mother's basement
That's why my videos don't got no Baphomet product placement
I'm a real one
The honey is sweet, the apple's bitter
They'll try to convince you you stronger without your woman than when you with her
And tell you they kidding while Twitter trashing your litter
I know the devil's a liar
I know that players is quitters, I heard you hire your hitters
I know the higher the bidder, that mean the less on return
So I just hire a sitter
I'm not no boss nigga, I'm a soldier
Kingdom builder, man somebody shoulda told ya
Fuck you


Fuck you, oh-oh
Fuck you, fuck you
Fu-u-u-u-u-uck you, fuck you-ou-ou-ou
Fu-fu-fu-fu-fu-fu, fu-fu-fu-fu-fu-fu
Fuck you, oh-oh
Fuck you, fuck you
Fu-u-u-u-u-uck you, fuck you-ou-ou-ou
Fu-fu-fu-fu-fu-fu, fu-fu-fu-fu-fu-fu
Fuck you, fu-u-u-u-u-uck you, fu-fuck you
Fu-u-u-u-u-uck you, fu-fuck you
Fu-u-u-u-u-uck you, fu-fuck you
Fu-u-u-u-u-uck you, fu-fuck you""",
    },
}
