# Auto-generated by 03_build_schema.py — do not edit manually.
# Artist: Daft Punk  |  Code: DP
# Songs included: 14  |  Missing: 1

DP_SCHEMA = {
    "DP_01": {
        "title":  "Get Lucky",
        "artist": "Daft Punk",
        "lyrics": """Like the legend of the phoenix, huh
All ends with beginnings
What keeps the planet spinnin', ah-ah
The force from the beginnin'
Huh, look


We've come too far
To give up who we are
So let's raise the bar
And our cups to the stars


She's up all night to the sun
I'm up all night to get some
She's up all night for good fun
I'm up all night to get lucky
We're up all night to the sun
We're up all night to get some
We're up all night for good fun
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky


The present has no ribbon
Your gift keeps on giving
What is this I'm feelin'?
If you wanna leave, I'm with it, ah-ah


We've come too far
To give up who we are
So let's raise the bar
And our cups to the stars


She's up all night to the sun
I'm up all night to get some
She's up all night for good fun
I'm up all night to get lucky
We're up all night to the sun
We're up all night to get some
We're up all night for good fun
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky


She's up all night to the sun
I'm up all night to get some
She's up all night for good fun
I'm up all night to get lucky
We're up all night to the sun
We're up all night to get some
We're up all night for good fun
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky


She's up all night to the sun
I'm up all night to get some
She's up all night for good fun
I'm up all night to get lucky
We're up all night to the sun
We're up all night to get some
We're up all night for good fun
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky


We're up all night to get
We're up all night to get
We're up all night to get
We're up all night to get
We're up all night to get
We're up all night to get
We're up all night to get
We're up all night to get
We're up all night to get back together
We're up all night to get (Let's get funked again)
We're up all night to get (Funky)
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky


We've come too far
To give up who we are
So let's raise the bar
And our cups to the stars


She's up all night to the sun
I'm up all night to get some
She's up all night for good fun
I'm up all night to get lucky
We're up all night to the sun
We're up all night to get some
We're up all night for good fun
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky


We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky
We're up all night to get lucky""",
    },
    "DP_02": {
        "title":  "Harder, Better, Faster, Stronger",
        "artist": "Daft Punk",
        "lyrics": """Work it, make it
Do it, makes us
Harder, better
Faster, stronger
More than, hour
Hour, never
Ever, after
Work is, over
Work it, make it
Do it, makes us
Harder, better
Faster, stronger


Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over


Work it harder, make it
Do it faster, makes us
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over
Work it, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over


Work it harder
Do it faster
More than ever, hour
Work is never over
Work it harder, make it better
Do it faster, makes us stronger
More than ever, hour after hour
Work is never over""",
    },
    "DP_03": {
        "title":  "Around the World",
        "artist": "Daft Punk",
        "lyrics": """Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world


Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world


Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world
Around the world, around the world""",
    },
    "DP_05": {
        "title":  "Instant Crush",
        "artist": "Daft Punk",
        "lyrics": """I didn't want to be the one to forget
I thought of everything I'd never regret
A little time with you is all that I get
That's all we need because it's all we can take
One thing I never see the same when you're 'round
I don’t believe in him and his lips on the ground
I wanna take you to that place in the Roche
But no one gives us any time anymore
He asks me once if I'd look in on his dog
You made an offer for it, then you ran off
I got this picture of us kids in my head
And all I hear is the last thing that you said


"I listened to your problems, now listen to mine"
I didn't want to anymore, oh-oh-oh


And we will never be alone again
'Cause it doesn't happen every day
Kinda counted on you being a friend
Can I give it up or give it away?
Now I thought about what I wanna say
But I never really know where to go
So I chained myself to a friend
'Cause I know it unlocks like a door
And we will never be alone again
'Cause it doesn't happen every day
Kinda counted on you being a friend
Can I give it up or give it away?
Now I thought about what I wanna say
But I never really know where to go
So I chained myself to a friend
Some more again


It didn't matter what they wanted to see
He thought he saw someone that looked just like me
The summer memory that just never dies
We worked too long and hard to give it no time
He sees right through me, it's so easy with lies
Cracks in the road that I would try and disguise
He runs his scissors at the seam in the wall
He cannot break it down or else he would fall
One thousand lonely stars hiding in the cold
Take it, oh, I don't wanna sing anymore




"I listened to your problems, now listen to mine"
I didn't want to anymore, oh-oh-oh


And we will never be alone again
'Cause it doesn't happen every day
Kinda counted on you being a friend
Can I give it up or give it away?
Now I thought about what I wanna say
But I never really know where to go
So I chained myself to a friend
'Cause I know it unlocks like a door
And we will never be alone again
'Cause it doesn't happen every day
Kinda counted on you being a friend
Can I give it up or give it away?
Now I thought about what I wanna say
But I never really know where to go
So I chained myself to a friend
'Cause I know it unlocks like a–


I don't understand, don't get upset
I'm not with you
We're swimming around, it's all I do
When I'm with you


And we will never be alone again
'Cause it doesn't happen every day
Kinda counted on you being a friend
Can I give it up or give it away?
Now I thought about what I wanna say
But I never really know where to go
So I chained myself to a friend
'Cause I know it unlocks like a door
And we will never be alone again
'Cause it doesn't happen every day
Kinda counted on you being a friend
Can I give it up or give it away?
Now I thought about what I wanna say
But I never really know where to go
So I chained myself to a friend
'Cause I know it unlocks like a door""",
    },
    "DP_06": {
        "title":  "Lose Yourself to Dance",
        "artist": "Daft Punk",
        "lyrics": """I know you don't get a chance to take a break this often
I know your life is speedin' and it isn't stoppin'
Here, take my shirt and just go ahead and wipe up all the
Sweat, sweat, sweat


Lose yourself to dance
Lose yourself to dance
Lose yourself to dance
Lose yourself to dance
Lose yourself to dance
Lose yourself to dance
Lose yourself to dance
Lose yourself to dance
Lose yourself to dance


I know you don't get a chance to take a break this often
I know your life is speedin' and it isn't stoppin'
Here, take my shirt and just go ahead and wipe up all the
Sweat, sweat, sweat


Lose yourself to dance
(
Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on
)
Lose yourself to dance
(
Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on
)
Lose yourself to dance
(
Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on
)
Lose yourself to dance
(
Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on
)
Lose yourself to dance
"Take your time"
(
Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on
)
Lose yourself to dance
(
Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on
)
Lose yourself to dance
(
Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on
)
Lose yourself to dance
(
Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on
)
Lose yourself to dance


Everybody's dancing on the floor
Getting ready for more
(Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on)
Everybody's dancing on the floor
Getting ready for more
(Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on)
Lose yourself to dance
Everybody's dancing on the floor
Getting ready for more
(Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on)
Everybody's dancing on the floor
Getting ready for more
(Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on)
Lose yourself to dance
Everybody's dancing on the floor
Getting ready for more
(Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on)
Lose yourself to dance
Everybody's dancing on the floor
Getting ready for more
(Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on)
Lose yourself to dance
"Take your time"
Everybody on the floor, everybody on the floor
(Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on)
Lose yourself to dance
Everybody on the floor, everybody on the floor
(Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on)
Lose yourself to dance
Everybody on the floor (Aw yeah), everybody on the floor
(Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on)
Everybody on the floor (Aw yeah), everybody on the floor
(Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on)
Lose yourself to dance
Everybody on the floor (Aw yeah, oh yeah)
(Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on)
Lose yourself to dance
Everybody on the floor (Aw yeah, oh yeah)
(Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on)


Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on
Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on
Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on
Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on


I know you don't get a chance to take a break this often
I know your life is speedin' and it isn't stoppin'
Here, take my shirt and just go ahead and wipe up all the
Sweat, sweat, sweat


Lose yourself to dance
(
Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on
)
Lose yourself to dance
(
Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on
)
Lose yourself to dance
(
Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on
)
Lose yourself to dance
(
Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on
)
Lose yourself to dance


Everybody's dancing on the floor
Getting ready for more
(Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on)
Lose yourself to dance
Everybody's dancing on the floor
Getting ready for more
(Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on)
Lose yourself to dance
Everybody's dancing on the floor
Getting ready for more
(Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on)
Lose yourself to dance
Everybody's dancing on the floor
Getting ready for more
(Come on, come on, come on, come on, come on, come on, come on, come on, come on, come on)


Lose yourself to dance
Lose yourself to dance
Lose yourself to dance
Lose yourself to dance
Lose yourself to dance
Lose yourself to dance
Lose yourself to dance
Lose yourself to dance
Lose yourself to dance
I know you don't get a chance to take a break this often""",
    },
    "DP_07": {
        "title":  "Something About Us",
        "artist": "Daft Punk",
        "lyrics": """It might not be the right time
I might not be the right one
But there's something about us I want to say
'Cause there's something between us anyway


I might not be the right one
It might not be the right time
But there's something about us I've got to do
Some kind of secret I will share with you


I need you more than anything in my life
I want you more than anything in my life
I'll miss you more than anyone in my life
I love you more than anyone in my life""",
    },
    "DP_08": {
        "title":  "Digital Love",
        "artist": "Daft Punk",
        "lyrics": """Last night I had a dream about you
In this dream, I'm dancing right beside you
And it looked like everyone was having fun
The kind of feeling I've waited so long
Don't stop, come a little closer
As we jam, the rhythm gets stronger
There's nothing wrong with just a little little fun
We were dancing all night long
The time is right to put my arms around you
You're feeling right, you wrap your arms around too
But suddenly I feel the shining sun
Before I knew it, this dream was all gone


Ooh, I don't know what to do
About this dream and you
I wish this dream comes true
Ooh, I don't know what to do
About this dream and you
We'll make this dream come true


Why don't you play the game?
Why don't you play the game?""",
    },
    "DP_09": {
        "title":  "Within",
        "artist": "Daft Punk",
        "lyrics": """There are so many things that I don't understand
There's a world within me that I cannot explain
Many rooms to explore, but the doors look the same
I am lost, I can't even remember my name


I've been, for some time
Looking for someone
I need to know now
Please tell me who I am
I've been, for some time
Looking for someone
I need to know now
Please tell me who I am


There are so many things that I don't understand
There's a world within me that I cannot explain
Many rooms to explore, but the doors look the same
(Where are the locks to try the key?)
I am lost, I can't even remember my name
(And I wonder why)


I've been, for some time
Looking for someone
I need to know now
Please tell me who I am
I've been, for some time
Looking for someone
I need to know now
Please tell me who I am
I've been, for some time
Looking for someone
I need to know now
Please tell me who I am
I've been, for some time
Looking for someone
I need to know now
Please tell me who I am""",
    },
    "DP_10": {
        "title":  "Give Life Back to Music",
        "artist": "Daft Punk",
        "lyrics": """Let the music in tonight
Just turn on the music
Let the music of your life
Give life back to music
Let the music in tonight
Just turn on the music
Let the music of your life
Give life back to music
Let the music in tonight
Just turn on the music
Let the music of your life
Give life back to music
Let the music in tonight
Just turn on the music
Let the music of your life
Give life back to music


Give life back to music
Give life back to music


Let the music in tonight
Just turn on the music
Let the music of your life
Give life back to music
Let the music in tonight
Just turn on the music
Let the music of your life
Give life back to music
Let the music in tonight
Just turn on the music
Let the music of your life
Give life back to music
Let the music in tonight
Just turn on the music
Let the music of your life
Give life back to music""",
    },
    "DP_11": {
        "title":  "Fragments of Time",
        "artist": "Daft Punk",
        "lyrics": """Driving this road down to paradise
Letting the sunlight into my eyes
Our only plan is to improvise
And it's crystal clear that I don't ever want it to end
If I had my way, I would never leave
Keep building these random memories
Turning our days into melodies
But since I can't stay


I'll just keep playing back these fragments of time
Everywhere I go these moments will shine
I'll just keep playing back these fragments of time
Everywhere I go these moments will shine


Familiar faces I've never seen
Living the gold and the silver dream
Making me feel like I'm seventeen
And it's crystal clear that I don't ever want it to end
If I had my way, I would never leave
Keep building these random memories
Turning our days into melodies
But since I can't stay


I'll just keep playing back these fragments of time
Everywhere I go these moments will shine
I'll just keep playing back these fragments of time
Everywhere I go these moments will shine




I'll just keep playing back these fragments of time
Everywhere I go these moments will shine
I'll just keep playing back these fragments of time
These moments will shine""",
    },
    "DP_12": {
        "title":  "Human After All",
        "artist": "Daft Punk",
        "lyrics": """We are human
After all
Much in common
After all
We are human
After all
Much in common
After all


We are human
After all
Much in common
After all
We are human
After all
Much in common
After all


We are human
After all
Much in common
After all
We are human
After all
Much in common
After all
We are human
After all
Much in common
After all
We are human
After all
Much in common
After all


We are human
After all
Much in common
After all
We are human
After all
Much in common
After all
We are human
After all
Much in common
After all
We are human
After all
Much in common
After all


Human, human, human, human
Human, human, human, human
Human, human, human, human
Human, human, human, after all
Human, human, human, human
Human, human, human, human
Human, human, human, human
Human, human, human, after all
Human, human, human, human
Human, human, human, human
Human, human, human, human
Human, human, human, after all
Human, human, human, human
Human, human, human, human
Human, human, human, human
Human, human, human, after all
Human, human, human, human
Human, human, human, human
Human, human, human, human
Human, human, human, after all
Human, human, human, human
Human, human, human, human
Human, human, human, human
Human, human, human, after all
Human, human, human, human
Human, human, human, human
Human, human, human, human
Human, human, human, after all
Human, human, human, human
Human, human, human, human
Human, human, human, human
Human, human, human, after all""",
    },
    "DP_13": {
        "title":  "Technologic",
        "artist": "Daft Punk",
        "lyrics": """Buy it, use it, break it, fix it
Trash it, change it, mail – upgrade it
Charge it, point it, zoom it, press it
Snap it, work it, quick – erase it
Write it, cut it, paste it, save it
Load it, check it, quick – rewrite it
Plug it, play it, burn it, rip it
Drag and drop it, zip – unzip it
Lock it, fill it, call it, find it
View it, code it, jam – unlock it
Surf it, scroll it, pause it, click it
Cross it, crack it, switch – update it
Name it, read it, tune it, print it
Scan it, send it, fax – rename it
Touch it, bring it, pay it, watch it
Turn it, leave it, start – format it
Buy it, use it, break it, fix it
Trash it, change it, mail – upgrade it
Charge it, point it, zoom it, press it
Snap it, work it, quick – erase it
Write it, cut it, paste it, save it
Load it, check it, quick – rewrite it
Plug it, play it, burn it, rip it
Drag and drop it, zip – unzip it
Lock it, fill it, call it, find it
View it, code it, jam – unlock it
Surf it, scroll it, pause it, click it
Cross it, crack it, switch – update it
Name it, read it, tune it, print it
Scan it, send it, fax – rename it
Touch it, bring it, pay it, watch it
Turn it, leave it, start – format it


Technologic
Technologic
Technologic
Technologic


Buy it, use it, break it, fix it
Trash it, change it, mail – upgrade it
Charge it, point it, zoom it, press it
Snap it, work it, quick – erase it
Write it, cut it, paste it, save it
Load it, check it, quick – rewrite it
Plug it, play it, burn it, rip it
Drag and drop it, zip – unzip it
Lock it, fill it, call it, find it
View it, code it, jam – unlock it
Surf it, scroll it, pause it, click it
Cross it, crack it, switch – update it
Name it, read it, tune it, print it
Scan it, send it, fax – rename it
Touch it, bring it, pay it, watch it
Turn it, leave it, start – format it
Buy it, use it, break it, fix it
Trash it, change it, mail – upgrade it
Charge it, point it, zoom it, press it
Snap it, work it, quick – erase it
Write it, cut it, paste it, save it
Load it, check it, quick – rewrite it
Plug it, play it, burn it, rip it
Drag and drop it, zip – unzip it
Touch it, bring it, pay it, watch it
Turn it, leave it, start – format it
Touch it, scroll it, pause it, click it
Cross it, crack it, switch – update it

Lock it, fill it, call it, find it
View it, code it, jam – unlock it
Buy it, use it, break it, fix it
Trash it, change it, mail – upgrade it
Charge it, point it, zoom it, press it
Snap it, work it, quick – erase it
Write it, cut it, paste it, save it
Load it, check it, quick – rewrite it
Surf it, scroll it, pause it, click it
Cross it, crack it, switch – update it
Name it, read it, tune it, print it
Scan it, send it, fax – rename it
Touch it, bring it, pay it, watch it
Turn it, leave it, start – format it
Buy it, use it, break it, fix it
Trash it, change it, mail – upgrade it
Charge it, point it, zoom it, press it
Snap it, work it, quick – erase it
Write it, cut it, paste it, save it
Load it, check it, quick – rewrite it
Plug it, play it, burn it, rip it
Drag and drop it, zip – unzip it
Surf it, scroll it, pause it, click it
Cross it, crack it, switch – update it
Name it, read it, tune it, print it
Scan it, send it, fax – rename it
Touch it, bring it, pay it, watch it
Turn it, leave it, start – format it
Buy it, use it, break it, fix it
Trash it, change it, mail – upgrade it
Charge it, point it, zoom it, press it
Snap it, work it, quick – erase it
Write it, cut it, paste it, save it
Load it, check it, quick – rewrite it
Plug it, play it, burn it, rip it
Drag and drop it, zip – unzip it
Surf it, scroll it, pause it, click it
Cross it, crack it, switch – update it
Name it, read it, tune it, print it
Scan it, send it, fax – rename it
Buy it, use it, break it, fix it
Trash it, change it, mail – upgrade it
Charge it, point it, zoom it, press it
Snap it, work it, quick – erase it
Write it, cut it, paste it, save it
Load it, check it, quick – rewrite it
Plug it, play it, burn it, rip it
Drag and drop it, zip – unzip it
Lock it, fill it, call it, find it
View it, code it, jam – unlock it
Surf it, scroll it, pause it, click it
Cross it, crack it, switch – update it
Name it, read it, tune it, print it
Scan it, send it, fax – rename it
Touch it, bring it, pay it, watch it
Turn it, leave it, start – format it


Technologic
Technologic
Technologic
Technologic
Technologic
Technologic
Technologic
Technologic




Technologic
Technologic
Technologic
Technologic""",
    },
    "DP_14": {
        "title":  "Touch",
        "artist": "Daft Punk",
        "lyrics": """Touch, touch
I remember touch
Touch, touch
I remember touch
Where do I belong?
Touch, I need something more
I remember touch
I need something more in my mind


Touch, I remember touch
Pictures came with touch
A painter in my mind
Tell me what you see
A tourist in a dream
A visitor, it seems
A half-forgotten song
Where do I belong?
Tell me what you see
I need something more


Kiss, suddenly alive
Happiness arrive
Hunger like a storm
How do I begin?
A room within a room
A door behind a door
Touch, where do you lead?
I need something more
Tell me what you see
I need something more




Home, hold on, if love is the answer, you're home
Hold on, if love is the answer, you're home
Hold on, if love is the answer, you're home
Hold on, if love is the answer, you're home
Hold on, if love is the answer, you're home
Hold on, if love is the answer, you're home
Hold on, if love is the answer, you're home
Hold on, if love is the answer, you're–




Hold on, if love is the answer, you're home
Hold on, if love is the answer, you're home
Hold on, if love is the answer, you're home
Hold on, if love is the answer, you're home
Hold on, if love is the answer, you're home
Hold on, if love is the answer, you're home
Hold on, if love is the answer, you're home
Hold on, if love is the answer, you're home
Hold on, if love is the answer, you're–


Touch, sweet touch
You've given me too much to feel
Sweet touch
You've almost convinced me I'm real
I need something more
I need something more""",
    },
    "DP_15": {
        "title":  "Voyager",
        "artist": "Daft Punk",
        "lyrics": """[Letra de "Daft Punk - Voyager (Traducción al Español)"]

[Instrumental]""",
    },
}
