# Auto-generated by 03_build_schema.py — do not edit manually.
# Artist: Disclosure  |  Code: DS
# Songs included: 15  |  Missing: 0

DS_SCHEMA = {
    "DS_01": {
        "title":  "Latch",
        "artist": "Disclosure",
        "lyrics": """Un autre
Un autre
Un autre


Tu soulèves mon cœur quand le reste de moi est à terre
Tu, tu m'envoûtes même quand tu n'es pas là
S'il y a des limites, j'essaierai de les démolir
Je m'accroche à, bébé, maintenant je sais ce que j'ai trouvé


Je sens que nous sommes suffisamment proches
Je veux enfermer ton amour
Je sens que nous sommes suffisammеnt proches
Puis-je enfеrmer ton amour, bébé ?


Maintenant que je t'ai dans mon espace
Je ne te laisserai pas partir
Tu es enchaîné dans mon étreinte
Je m'accroche à toi
Maintenant que je t'ai dans mon espace
Je ne te laisserai pas partir
Tu es enchaîné dans mon étreinte
Je m'accroche à toi


Je suis envoûté, je suis enveloppé par ton contact
Je me sens si amoureux, serre-moi fort dans ton étreinte
Comment fais-tu ? Tu me fais perdre le souffle
Que m'as-tu donné pour faire battre mon cœur hors de ma poitrine


Je sens que nous sommes suffisamment proches
Je veux enfermer ton amour ?
Je sens que nous sommes suffisamment proches
Puis-je enfermer ton amour, bébé ?
Je sens que nous sommes suffisamment proches
Je veux enfermer ton amour ?
Je sens que nous sommes suffisamment proches
Puis-je enfermer ton amour, bébé ?


Maintenant que je t'ai dans mon espace
Je ne te laisserai pas partir
Tu es enchaîné dans mon étreinte
Je m'accroche à toi
Maintenant que je t'ai dans mon espace
Je ne te laisserai pas partir
Tu es enchaîné dans mon étreinte
Je m'accroche à toi


Je m'accroche à toi
Je ne te laisserai pas partir
Je m'accroche à toi
Je ne te laisserai pas partir
Je ne te laisserai pas partir, je ne te laisserai pas partir
Je ne te laisserai pas partir, je ne te laisserai pas partir""",
    },
    "DS_02": {
        "title":  "F for You",
        "artist": "Disclosure",
        "lyrics": """I've been infected with restless whispers and cheats
They're manifested in words and the lies that you speak
I've been infected with restless whispers and cheats
They're manifested in words and the lies that you speak
I've been infected with restless whispers and cheats
They're manifested in words and the lies that you speak
I've been infected with restless whispers and cheats
They're manifested in words and the lies that you speak


Because I played the fool for you
Because I played the fool for you
Because I played the fool for you
Because I played the fool for you
Because I...
Because I...
Because I...
Because I...


I've been infected with restless whispers and cheats
They're manifested in words and the lies that you speak
I've been infected with restless whispers and cheats
They're manifested in words and the lies that you speak
I've been infected with restless whispers and cheats
They're manifested in words and the lies that you speak
I've been infected with restless whispers and cheats
They're manifested in words and the lies that you speak


Because I played the fool for you
Because I played the fool for you
Because I played the fool for you
Because I played the fool for you
Because I played the fool for you
Because I played the fool for you
Because I played the fool for you
Because I played the fool for you


Because I played the fool for you
Because I played the fool for you
Because I played the fool for you
Because I played the fool for you


Because I...
Because I...
Because I...
Because I...
Because I...


I've been infected with restless whispers and cheats
They're manifested in words and the lies that you speak
I've been infected with restless whispers and cheats
They're manifested in words and the lies that you speak
I've been infected...
They're manifested...
I've been infected...
They're manifested...""",
    },
    "DS_03": {
        "title":  "You & Me",
        "artist": "Disclosure",
        "lyrics": """I'll be giving up, oh


Home is where the heart is
And I gave it to you in a paper bag
Even though it's tarnished
You told me it's the best you'd ever had
You've got my secret combination
And I don't be giving that out easily
With my deepest dedication
I can tell that you have got the same for me


(Have you got room for love?)


So please don't let go 'cause you know
Exactly what we've found
So please don't let go, my darling
And keep it locked up underground
It's gonna be you and me
It's gonna be everything you ever dreamed
I'm gonna be who you need
It's gonna be everything, yeah, everything, we're meant to be


We're meant to be


Rolling with the punches
So they won't get inside our happiness
Love is always hunted
But your arrows are soaring through my chest
'Cause you know you give me something
Yeah, you give me exactly what I need
Got my blood pumping
'Cause you know you own each drop of blood I bleed


(Have you got room for love?)


So please don't let go 'cause you know
Exactly what we've found
So please don't let go, my darling
And keep it locked up underground
It's gonna be you and me
It's gonna be everything you ever dreamed
I'm gonna be who you need
It's gonna be everything, yeah, everything, we're meant to be


In your big house on the hill
Where you keep your dollar bills
Where you stashed my heart somewhere in the dark
Keep it safe, I know you will
Know you will, know you will, know you will
I know you will
(We're meant to be)
(We're meant to be)""",
    },
    "DS_04": {
        "title":  "White Noise",
        "artist": "Disclosure",
        "lyrics": """I know you're smart
You spin me round like a knot
You know the pieces, pieces of my heart
Sometimes its fun, you pull my strings one by one
Until you get me, get me, onto one


Lately I've been thinking if you wanna get tough
Then let's play rough
Lately I've been thinking if you wanna get tough
Then let's play rough
I don't need you
Giving it straight to me, giving it straight to me
You're just gonna get knocked back
I don't need you
Telling me how to be, telling me how to be
Just gonna get knocked back
Just gonna get knocked back
Just gonna get knocked back
Just gonna get knocked back
Just gonna get knocked back
Back, back, back, back
Back, back, back, back...


Just noise, white noise
Just noise, white noise
I'm hearing static, you're like an automatic
You just wanna keep me on repeat and hear me crying
Just noise, white noise
Just noise, white noise
I'm hearing static, you're like an automatic
You just wanna keep me on repeat and hear me crying


Only you can look at me the way you do
You always tint me, tint me black and blue
Such a shame, you frame me with such disdain
You got me washed out, washed out colour drained


Lately I've been thinking if you wanna get tough
Then let's play rough
Lately I've been thinking if you wanna get tough
Then let's play rough
I don't need you
Giving it straight to me, giving it straight to me
You're just gonna get knocked back
I don't need you
Telling me how to be, telling me how to be
Just gonna get knocked back
Just gonna get knocked back
Just gonna get knocked back
Just gonna get knocked back
Just gonna get knocked back
Back, back, back, back
Back, back, back, back...


Just noise, white noise
Just noise, white noise
I'm hearing static, you're like an automatic
You just wanna keep me on repeat and hear me crying""",
    },
    "DS_05": {
        "title":  "Magnets",
        "artist": "Disclosure",
        "lyrics": """Never really felt bad about it
As we drank deep from the lie
'Cause I felt melting magnets, babe
The second I saw you through half-shut eyes


Smoke and sunset
Off Mulholland
He was talking
I was wonderin' 'bout you
You and that girl
She your girlfriend?
Face from heaven
Bet the world she don't know
Pretty girls don't know the things that I know
Walk my way, I'll share the things that she won't
Pretty girls don't know the things that I know
Walk my way, I'll share the things that she won't


I was wondering 'bout you
Bet the world she don't know
Pretty girls don't know the things that I know
Pretty girls don't know the things that I know


Never really thought we would make it
We be thinking about what could have been
But we've had a record summer, can't turn it down, oh
Now I don't wanna see the end begin


Smoke and sunset
Off Mulholland
He was talking
I was wonderin' 'bout you
You and that girl
She your girlfriend?
Face from heaven
Bet the world she don't know
Pretty girls don't know the things that I know
Walk my way, I'll share the things that she won't
Pretty girls don't know the things that I know
Walk my way, I'll share the things that she won't


Won't
Walk my way, I'll share the things that she won't
Pretty girls don't know the things that I know
Walk my way, I'll share the things that she won't
Pretty girls don't know the things that I know
Walk my way, I'll share the things that she won't
Pretty girls don't know the things that I know
Pretty girls don't know the things that I know
The things that I know""",
    },
    "DS_06": {
        "title":  "Holding On",
        "artist": "Disclosure",
        "lyrics": """(Whoooooa....shake it, shake, shake it..)


Weight of love on my shoulders
I thought that it would be easier than this
I found my heart had grown colder
But the warmth of your kiss, I can't dismiss


Though my past has left me bruised
I ain't hiding from the truth
When the truth won't let me lie right next to you


But it's holding on
And it's holding strong
Even though I tried to make it
Played the part, but I can't fake it
It keeps holding on
And it's holding strong
Even though I tried to break it
Heaven knows that I can't shake it
But it's holding on
And it's holding strong
Even though I tried to make it
Played the part, but I can't fake it
It keeps holding on
And it's holding strong
Even though I tried to break it
Heaven knows that I can't shake it


Shake it, sh-shake it
Shake it, sh-shake it
Shake it, sh-shake it
Shake it, sh-shake it
Shake it, sh-shake it
Shake it, sh-shake it
Shake it, sh-shake it
Shake it, sh-shake it


It keeps holding on and on
It keeps holding on and on
It keeps holding on and on
It keeps holding on and on


I've seen times that were harder
I remember the taste of bitterness
Won't you help me, my father?
Help me fall in the love that I have missed


Though my past has left me bruised
I ain't hiding from the truth
When the truth won't let me lie right next to you


But it's holding on
And it's holding strong
Even though I tried to make it
Played the part, but I can't fake it
It keeps holding on
And it's holding strong
Even though I tried to break it
Heaven knows that I can't shake it
But it's holding on
And it's holding strong
Even though I tried to make it
Played the part, but I can't fake it
It keeps holding on
And it's holding strong
Even though I tried to break it
Heaven knows that I can't shake it


Shake it, sh-shake it
Shake it, sh-shake it
Shake it, sh-shake it
Shake it, sh-shake it
Shake it, sh-shake it
Shake it, sh-shake it
Shake it, sh-shake it
Shake it, sh-shake it


It keeps holding on and on
It keeps holding on and on
It keeps holding on and on
It keeps holding on and on
But it...naah..naaah
But it...""",
    },
    "DS_07": {
        "title":  "Voices",
        "artist": "Disclosure",
        "lyrics": """There are voices in my head and my heart is trying hard to drown them out
I keep hearing what they said, they've enticed me into what they’re all about
Willpower slips away
And I’m weakening with every word they say
So I contemplate my fate, as I do, the whisper turns into a shout


You bring out the darkest side of me
Chased out from a place that I can’t reach
I would love to practice what I preach
But you bring out the darkest side of me, yeah


I tried to resist, but you caught me
I tried to dismiss what you taught me
I tried to resist, but you caught me
I tried to dismiss what you taught me


Risking everything I had, I was keen to find the worst that I could do
Drove the sanity away, brought destruction to the people that I knew
My head became a cage
I became a puppet on the stage
And even though we’re not okay, the feeling brings me pleasure all the same, all the same


You bring out the darkest side of me
Chased out from a place that I can’t reach
I would love to practice what I preach
But you bring out the darkest side of me, yeah


I tried to resist, but you caught me
I tried to dismiss what you taught me
I tried to resist, but you caught me
I tried to dismiss what you taught me""",
    },
    "DS_08": {
        "title":  "Help Me Lose My Mind",
        "artist": "Disclosure",
        "lyrics": """Talk to me, and watch me crumble
You will see me come undone
Faithfully I will look over
There I'll find what you've become
(What you've become)


You help me lose my mind
And you bring me something I can't define
Help me lose my mind
Make me wonder what I felt before
Keep biding my time
How much longer have I been waiting for?


Jealousy will be washed over
Carefully we will come through
Could it be easy to start over?
Somehow I will bring you to
(What you've become)


You help me lose my mind
And you bring me something I can't define
Help me lose my mind
Make me wonder what I felt before
Keep biding my time
How much longer have I been waiting for?


Waiting, waiting, I've been waiting
Waiting, waiting, I've been waiting
Waiting, waiting, I've been waiting
Waiting, waiting, I've been waiting
Waiting, waiting, I've been waiting
Waiting, waiting, I've been waiting
Waiting, waiting, I've been waiting
Waiting, waiting


You help me lose my mind
And you bring me something I can't define
Help me lose my mind
Make me wonder what I felt before
Keep biding my time
How much longer have I been waiting for?

You help me lose my mind
And you bring me something I can't define
Help me lose my mind
Make me wonder what I felt before
Keep biding my time
How much longer have I been waiting for?""",
    },
    "DS_09": {
        "title":  "Omen",
        "artist": "Disclosure",
        "lyrics": """I'm feeling something, something different
When you left, my picture changed
I was blinded, I'd not envisioned
The same face in a different frame


It's an omen, caught my baby crying
Saw the silver lining
It must be an omen
Needed you to show me, without you I am lonely


My mind would rule my heart
I didn't pay attention to the light in the dark
It left me torn apart
But now I see your tears as an omen


Oh, oh, oh, oh
Oh, oh, oh, omen
Oh, oh, oh, oh
Oh, oh, oh, omen


You were waiting, I was vacant
You left before my eyes
Then it hit me, you're relocating
And I need you by my side


It's an omen, caught my baby crying
Saw the silver lining
It must be an omen
Needed you to show me, without you I am lonely


My mind would rule my heart
I didn't pay attention to the light in the dark
It left me torn apart
But now I see your tears as an omen
My mind would rule my heart
I didn't pay attention to the light in the dark
It left me torn apart
But now I see your tears as an omen


Oh, oh, oh, oh
Oh, oh, oh, omen (Woah, now, love)
Oh, oh, oh, oh
Oh, oh, oh, omen
(I didn't pay attention to the light in the dark)
Oh, oh, oh, oh
Oh, oh, oh, omen (But now I see your tears as an omen)
Oh, oh, oh, oh
Oh, oh, oh, omen (Now I see your tears as an omen)
Oh, oh, oh, oh
Oh, oh, oh, omen
Oh, oh, oh, oh
Oh, oh, oh, omen""",
    },
    "DS_10": {
        "title":  "Jaded",
        "artist": "Disclosure",
        "lyrics": """Your words give you away
Be careful how you say my name
Step back, refrain
Be honest and you'll save some face
Cause you're fading
Don't mistake me for a fool
The game you play has changed


Take a look at yourself and the stories you tell
Does the truth weigh on your mind?
Tell me what did it cost when the moment was lost?
Is this how you survive?


Why, oh why do you have to lie?
What are you afraid of?
We know what you're made of
Now your time has passed you by
You've already made it
There's no need to chase it
Soak it up, soak it up and save it
Cause enough is enough, you're jaded
Golden years left you behind
You cannot replace them
Face it or you'll waste them
You cannot replace them
Face it or you'll waste them
Face it or you'll waste them
You cannot replace them


The gospel that you preach
It's poisonous beyond belief
But still, you'll reach
Be careful or the truth might speak
It's amazing when it's there in black and white for all to see
We sow and you reap


Take a look at yourself and the stories you tell
Does the truth weigh on your mind?
Tell me what did it cost when the moment was lost?
Is this how you survive?


Why, oh why do you have to lie?
What are you afraid of?
We know what you're made of
Now your time has passed you by
You've already made it
There's no need to chase it
Soak it up, soak it up and save it
Cause enough is enough, you're jaded
Golden years left you behind
You cannot replace them
Face it or you'll waste them
You cannot replace them
Face it or you'll waste them


Soak it up, soak it up and save it
Cause enough is enough, you're jaded
Golden years left you behind
You cannot replace them
Face it or you'll raise them
You cannot replace them""",
    },
    "DS_11": {
        "title":  "Good Intentions",
        "artist": "Disclosure",
        "lyrics": """Babe you can believe me when I say I tried my best
But there's no other way
You deserve the world, I couldn't give you less


But I'm not perfect, the way you're perfect
And though it hurts, yeah, it hurts to say goodbye


I know I let you down
It wasn't that your love wasn't good enough
Couldn't stick around
It's only in myself that I didn't trust
I had good intentions
I had good intentions


And it's a shame
Oh, all the heartache that I went and put you through
I take the blame
Cause the truth, there's really nothing you could do


But I'm not perfect, the way you're perfect
And though it hurts, yeah, it hurts to say goodbye


I know I let you down
It wasn't that your love wasn't good enough
Couldn't stick around
It's only in myself that I didn't trust
I had good intentions
I had good intentions
I had good intentions
I  had good intentions


But I'm not perfect the way you're perfect
And though it hurts, yeah, it hurts to say goodbye
But I'm not perfect the way you're perfect
And though it hurts, yeah, it hurts to say goodbye""",
    },
    "DS_12": {
        "title":  "Ultimatum",
        "artist": "Disclosure",
        "lyrics": """If you don’t want to marry me, just tell me the truth
Don't you wanna play with me, don't you wanna talk to me? Please tell me the truth""",
    },
    "DS_13": {
        "title":  "Watch Your Step",
        "artist": "Disclosure",
        "lyrics": """I've been working and I spend my time
Dreaming about how I could ease my mind
Breakbeat, dance, feels like I can fly
Give me some space so I can close my eyes


I don't look in the crowd
Baby, even when the lights come down
I like to dance like I'm alone in the room
I'm here tonight, baby, to do what I do, yeah


You make me watch your step when you move
You make me watch your step when you move
You make me watch your step when you move
Now what you're doing's making me move with you


I'm free tonight, don't want this to end
I'm here alone and you can leave your friends
Breakbeat, dance, and we don't pretend
Dreaming together, now our rhythms blend


I don't look in the crowd
Baby, even when the lights come down
I like to dance like I'm alone in the room
I'm here tonight, baby, to do what I do, yeah


You make me watch your step when you move
(Watch your step when you move)
You make me watch your step when you move
(Watch your step when you move)
You make me watch your step when you move
(Watch your step when you move)
Now what you're doing's making me move with you


You make me watch your step when you move
You make me watch your step when you move
You make me watch your step when you move
(Watch your step when you move)
Now what you're doing's making me move with you


(With you, with you)
(With you, with you)
(With you, with you)
Watch your step when you move
Now what you're doing's making me move with you


I don't look in the crowd
Baby, even when the lights come down
I like to dance like I'm alone in the room
I'm here tonight, baby, to do what I do, yeah


You make me watch your step when you move
(Watch your step when you move)
You make me watch your step when you move
(Watch your step when you move)
You make me watch your step when you move
(Watch your step when you move)
Now what you're doing's making me move with you


(With you, with you)
(With you, with you)
(With you, with you)
(With you, with you)""",
    },
    "DS_14": {
        "title":  "Moving Mountains",
        "artist": "Disclosure",
        "lyrics": """I can't stop
Whether you know or not
I ain't strong
And it's something in you that I'm dependent on
Worth a shot
Even though I've lost the plot
I know it's wrong
But it's something in you that I'm dependent on


Not going out tonight
Stay home until daylight
I'm hanging on for my life
I know myself far too well
Set myself up to fail
Is that what the future entails?


You give nothing to me
Still why do you feel like someone I need
I've been thinkin' 'bout us
And I've given enough
With you here by my side
It seems like I can't do anything right
I've been thinkin' 'bout us
And I've given enough


Every day, every day, every day, every day
Anyway, anyway, anyway, anyway
Feels like I'm movin' mountains
It feels like I'm movin' mountains


Such a shame
Time for me to make a change
With what you've shown
Maybe you're just another stepping stone
Lost my name
Trying to put out this flame
I don't know
Maybe you're just another stepping stone


Not going out tonight
Stay home until daylight
I'm hanging on for my life
I know myself far too well
Set myself up to fail
Is that what the future entails?


You give nothing to me
Still why do you feel like someone I need
I've been thinkin' 'bout us
And I've given enough
With you here by my side
It seems like I can't do anything right
I've been thinkin' 'bout us
And I've given enough


Every day, every day, every day, every day
Anyway, anyway, anyway, anyway
Feels like I'm movin' mountains
It feels like I'm movin' mountains
Every day, every day, every day, every day
Anyway, anyway, anyway, anyway
Feels like I'm movin' mountains
It feels like I'm movin' mountains
Every day, every day, every day, every day
Anyway, anyway, anyway, anyway
Feels like I'm movin' mountains
It feels like I'm movin' mountains
Every day, every day, every day, every day
Anyway, anyway, anyway, anyway
Feels like I'm movin' mountains
It feels like I'm movin' mountains


Feels like I'm
Feels like I'm
Feels like I'm movin' mountains
It feels like I'm movin' mountains
Feels like I'm movin' mountains
It feels like I'm movin' mountains
Feels like I'm movin' mountains
It feels like I'm movin' mountains
Feels like I'm movin' mountains
It feels like I'm movin' mountains
Feels like I'm movin' mountains
It feels like I'm movin' mountains
Feels like I'm movin' mountains
It feels like I'm movin' mountains


Every day, every day, every day, every day
Anyway, anyway, anyway, anyway
Feels like I'm movin' mountains
It feels like I'm movin' mountains
Every day, every day, every day, every day
Anyway, anyway, anyway, anyway
Feels like I'm movin' mountains
It feels like I'm movin' mountains

Movin' mountains
Movin' mountains""",
    },
    "DS_15": {
        "title":  "Where Angels Fear to Tread",
        "artist": "Disclosure",
        "lyrics": """Fools rush in
Where angels fear to tread
And so I come to you my love
My heart above my head
Fools rush in
Where angels fear to tread
And so I come to you my love
My heart above my head


Fools rush in
Where wise men never go
But wise men never fall in love
So how are they to know


When we met
Where angels fear to tread
And so I come to you my love
My heart above my head
When we met
Where angels fear to tread
And so I come to you my love
My heart above my head


Fools rush in
Where wise men never go
But wise men never fall in love
So how are they to know
Oh, oh, oh, oh


When we met
Where angels fear to tread
And so I come to you my love
My heart above my head
Fools rush in
Where angels fear to tread
And so I come to you my love
My heart above my head


Care, fool, fool
Care, fool


Fools rush in
Where angels fear to tread
And so I come to you my love
My heart above my head


Fools rush in
Where angels fear to tread
And so I come to you my love
My heart above my head""",
    },
}
