# Auto-generated by 03_build_schema.py — do not edit manually.
# Artist: Ed Sheeran  |  Code: ES
# Songs included: 12  |  Missing: 0

ES_SCHEMA = {
    "ES_01": {
        "title":  "Shape of You",
        "artist": "Ed Sheeran",
        "lyrics": """A club isn't the best place to find a lover
So the bar is where I go (Mm)
Me and my friends at the table doin' shots
Drinkin' fast and then we talk slow (Mm)
And you come over and start up a conversation with just me
And trust me, I'll give it a chance now (Mm)
Take my hand, stop, put Van the Man on the jukebox
And then we start to dance, and now I'm singin' like


Girl, you know I want your love
Your love was handmade for somebody like me
Well, come on now, follow my lead
I may be crazy, don't mind me
Say, "Boy, let's not talk too much"
Grab on my waist and put that body on me
Well, come on now, follow my lead
Come, come on now, follow my lead, mm


I'm in love with the shape of you
We push and pull like a magnet do
Although my heart is fallin' too
I'm in love with your body
And last night, you were in my room
And now my bed sheets smell like you
Every day, discoverin' somethin' brand new
Well, I'm in love with your body


Oh, I, oh, I, oh, I, oh, I
Well, I'm in love with your body
Oh, I, oh, I, oh, I, oh, I
Well, I'm in love with your body
Oh, I, oh, I, oh, I, oh, I
Well, I'm in love with your body
Every day, discoverin' somethin' brand new
I'm in love with the shape of you


One week in, we let the story begin
We're goin' out on our first date (Mm)
You and me are thrifty, so go all-you-can-eat
Fill up your bag and I fill up a plate (Mm)
We talk for hours and hours about the sweet and the sour
And how your family is doin' okay (Mm)
And leave and get in a taxi, and kiss in the back seat
Tell the driver make the radio play and I'm singin' like


Girl, you know I want your love
Your love was handmade for somebody like me
Well, come on now, follow my lead
I may be crazy, don't mind me
Say, "Boy, let's not talk too much"
Grab on my waist and put that body on me
Well, come on now, follow my lead
Come, come on now, follow my lead, mm


I'm in love with the shape of you
We push and pull like a magnet do
Although my heart is fallin' too
I'm in love with your body
And last night, you were in my room
And now my bed sheets smell like you
Every day, discoverin' somethin' brand new
Well, I'm in love with your body


Oh, I, oh, I, oh, I, oh, I
Well, I'm in love with your body
Oh, I, oh, I, oh, I, oh, I
Well, I'm in love with your body
Oh, I, oh, I, oh, I, oh, I
Well, I'm in love with your body
Every day, discoverin' somethin' brand new
I'm in love with the shape of you


Come on, be my baby, come on
Come on, be my baby, come on
Come on, be my baby, come on
Come on, be my baby, come on
Come on, be my baby, come on
Come on, be my baby, come on
Come on, be my baby, come on
Come on, be my baby, come on


I'm in love with the shape of you
We push and pull like a magnet do
Although my heart is fallin' too
I'm in love with your body
And last night, you were in my room
And now my bed sheets smell like you
Every day, discoverin' somethin' brand new
Well, I'm in love with your body


Come on, be my baby, come on
Come on, be my baby, come on
I'm in love with your body
Come on, be my baby, come on
Come on, be my baby, come on
I'm in love with your body
Come on, be my baby, come on
Come on, be my baby, come on
I'm in love with your body
Every day, discoverin' somethin' brand new
I'm in love with the shape of you""",
    },
    "ES_02": {
        "title":  "Perfect",
        "artist": "Ed Sheeran",
        "lyrics": """I found a love for me
Darling, just dive right in and follow my lead
Well, I found a girl, beautiful and sweet
Oh, I never knew you were the someone waiting for me


'Cause we were just kids when we fell in love
Not knowing what it was
I will not give you up this time
Darling, just kiss me slow, your heart is all I own
And in your eyes, you're holding mine


Baby, I'm dancing in the dark with you between my arms
Barefoot on the grass, listening to our favourite song
When you said you looked a mess, I whispered underneath my breath
But you heard it, darling, you look perfect tonight


Well, I found a woman, stronger than anyone I know
She shares my dreams, I hope that someday I'll share her home
Well, I found a love, to carry more than just my secrets
To carry love, to carry children of our own


We are still kids but we're so in love
Fighting against all odds
I know we'll be alright this time
Darling, just hold my hand
Be my girl, I'll be your man
I see my future in your eyes


Baby, I'm dancing in the dark, with you between my arms
Barefoot on the grass, listening to our favourite song
When I saw you in that dress, looking so beautiful
I don't deserve this, darling, you look perfect tonight




Baby, I'm dancing in the dark, with you between my arms
Barefoot on the grass, listening to our favourite song
I have faith in what I see
Now I know I have met an angel in person and she looks perfect


I don't deserve this
You look perfect tonight""",
    },
    "ES_03": {
        "title":  "Thinking Out Loud",
        "artist": "Ed Sheeran",
        "lyrics": """When your legs don't work like they used to before
And I can't sweep you off of your feet
Will your mouth still remember the taste of my love?
Will your eyes still smile from your cheeks?
And darlin', I will be lovin' you till we're seventy
And baby, my heart could still fall as hard at twenty-three


And I'm thinkin' 'bout how
People fall in love in mysterious ways
Maybe just the touch of a hand
Well, me, I fall in love with you every single day
And I just wanna tell you I am


So honey, now, take me into your lovin' arms
Kiss me under the light of a thousand stars
And place your head on my beatin' heart, I'm thinkin' out loud
Maybe we found love right where we are


When my hair's all but gone and my memory fades
And the crowds don't remember my name
When my hands don't play the strings the same way, mmm
I know you will still love me the same
'Cause, honey, your soul could never grow old, it's evergreen
And baby, your smile's forever in my mind and memory


I'm thinkin' 'bout how
People fall in love in mysterious ways
And maybe it's all part of a plan
Oh, I'll just keep on makin' the same mistakes
Hoping that you'll understand


That, baby, now, take me into your lovin' arms
Kiss me under the light of a thousand stars
Place your head on my beatin' heart, I'm thinkin' out loud
And maybe we found love right where we are, oh-oh


Lo-lo-lo, lo-lo-lo
Lo-lo-lo, lo-lo-lo, love


So baby, now, take me into your lovin' arms
And kiss me under the light of a thousand stars, oh, darlin'
Place your head on my beatin' heart, I'm thinkin' out loud
That maybe we found love right where we are
Oh, maybe we found love right where we are
And we found love right where we are""",
    },
    "ES_04": {
        "title":  "Photograph",
        "artist": "Ed Sheeran",
        "lyrics": """Lovin' can hurt
Lovin' can hurt sometimes
But it's the only thing that I know
And when it gets hard
You know it can get hard sometimes
It is the only thing that makes us feel alive


We keep this love in a photograph
We made these memories for ourselves
Where our eyes are never closin'
Hearts are never broken
And time's forever frozen still


So you can keep me
Inside the pocket of your ripped jeans
Holdin' me closer 'til our eyes meet
You won't ever be alone
Wait for me to come home


Lovin' can heal
Lovin' can mend your soul
And it's the only thing that I know, know
I swear it will get easier
Remember that with every piece of ya
Mm, and it's the only thing we take with us when we die


Mm, we keep this love in this photograph
We made these memories for ourselves
Where our eyes are never closin'
Hearts were never broken
And time's forever frozen still


So you can keep me
Inside the pocket of your ripped jeans
Holdin' me closer 'til our eyes meet
You won't ever be alone
And if you hurt me
Well, that's okay, baby, only words bleed
Inside these pages, you just hold me
And I won't ever let you go
Wait for me to come home


Wait for me to come home
Wait for me to come home
Wait for me to come home


Oh, you can fit me
Inside that necklace you got when you were sixteen
Next to your heartbeat, where I should be
Keep it deep within your soul
And if you hurt me
Well, that's okay, baby, only words bleed
Inside these pages, you just hold me
And I won't ever let you go


When I'm away, I will remember how you kissed me
Under the lamppost back on Sixth Street
Hearin' you whisper through the phone
"Wait for me to come home"""",
    },
    "ES_05": {
        "title":  "Castle on the Hill",
        "artist": "Ed Sheeran",
        "lyrics": """Letra de "Castle On The Hill" de Ed Sheeran
BELY BASARTE COVER


When I was six years old I broke my leg
I was running from my brother and his friends
And tasted the sweet perfume of the mountain grass I rolled down
I was younger then, take me back to when I


Found my heart and broke it here
Made friends and lost them through the years
And I've not seen the roaring fields in so long, I know I've grown
But I can't wait to go home


I'm on my way
Driving at 90 down those country lanes
Singing to "Tiny Dancer"
And I miss the way you make me feel, and it's real
We watched the sunset over the castle on the hill


Fifteen years old and smoking hand-rolled cigarettes
Running from the law through the backfields and getting drunk with my friends
Had my first kiss on a Friday night, I don't reckon that I did it right
But I was younger then, take me back to when


We found weekend jobs, when we got paid
We'd buy cheap spirits and drink them straight
Me and my friends have not thrown up in so long, oh how we've grown
But I can't wait to go home


I'm on my way
Driving at 90 down those country lanes
Singing to "Tiny Dancer"
And I miss the way you make me feel, and it's real
We watched the sunset over the castle on the hill
Over the castle on the hill
Over the castle on the hill


One friend left to sell clothes
One works down by the coast
One had two kids but lives alone
One's brother overdosed
One's already on his second wife
One's just barely getting by
But these people raised me
And I can't wait to go home


And I'm on my way, I still remember
These old country lanes
When we did not know the answers
And I miss the way you make me feel, it's real
We watched the sunset over the castle on the hill
Over the castle on the hill
Over the castle on the hill""",
    },
    "ES_06": {
        "title":  "Galway Girl",
        "artist": "Ed Sheeran",
        "lyrics": """She played the fiddle in an Irish band
But she fell in love with an English man
Kissed her on the neck and then I took her by the hand
Said, "Baby, I just wanna dance"


I met her on Grafton Street right outside of the bar
She shared a cigarette with me while her brother played the guitar
She asked me what does it mean, the Gaelic ink on your arm?
Said it was one of my friend's songs, do you wanna drink on?
She took Jamie as a chaser, Jack for the fun
She got Arthur on the table with Johnny riding a shotgun
Chatted some more, one more drink at the bar
Then put Van on the jukebox, got up to dance


You know, she played the fiddle in an Irish band
But she fell in love with an English man
Kissed her on the neck and then I took her by the hand
Said, "Baby, I just wanna dance"
With my pretty little Galway Girl
You're my pretty little Galway Girl


You know she beat me at darts and then she beat me at pool
And then she kissed me like there was nobody else in the room
As last orders were called was when she stood on the stool
After dancing the céili singing to trad tunes
I never heard Carrickfergus ever sung so sweet
A cappella in the bar using her feet for a beat
Oh, I could have that voice playing on repeat for a week
And in this packed out room, swear she was singing to me


You know, she played the fiddle in an Irish band
But she fell in love with an English man
Kissed her on the neck and then I took her by the hand
Said, "Baby, I just wanna dance"
My pretty little Galway Girl
My, my, my, my, my, my, my Galway Girl
My, my, my, my, my, my, my Galway Girl
My, my, my, my, my, my, my Galway Girl


And now we've outstayed our welcome and it's closing time
I was holding her hand, her hand was holding mine
Our coats both smell of smoke, whisky and wine
As we fill up our lungs with the cold air of the night
I walked her home then she took me inside
To finish some Doritos and another bottle of wine
I swear I'm gonna put you in a song that I write
About a Galway Girl and a perfect night


She played the fiddle in an Irish band
But she fell in love with an English man
Kissed her on the neck and then I took her by the hand
Said, "Baby, I just wanna dance"
My pretty little Galway Girl
My, my, my, my, my, my, my Galway Girl
My, my, my, my, my, my, my Galway Girl
My, my, my, my, my, my, my Galway Girl (Hey)""",
    },
    "ES_07": {
        "title":  "Bad Habits",
        "artist": "Ed Sheeran",
        "lyrics": """(One, two, three, four)
Ooh, ooh


Every time you come around, you know I can't say no
Every time the sun goes down, I let you take control
I can feel the paradise before my world implodes
And tonight had something wonderful


My bad habits lead to late nights endin' alone
Conversations with a stranger I barely know
Swearin' this'll be the last, but it probably won't
I got nothin' left to lose, or use, or do
My bad habits lead to wide eyes starin' at space
And I know I lose control of the things that I say
Yeah, I was lookin' for a way out, now I can't escape
Nothin' happens after two, it's truе, it's true
My bad habits lead to you


Ooh-ooh, ooh-ooh
My bad habits lead to you
Ooh-ooh, ooh-ooh
My bad habits lеad to you


Every pure intention ends when the good times start
Fallin' over everything to reach the first time's spark
It started under neon lights and then it all got dark
I only know how to go too far


My bad habits lead to late nights endin' alone
Conversations with a stranger I barely know
Swearin' this'll be the last, but it probably won't
I got nothin' left to lose, or use, or do
My bad habits lead to wide eyes starin' at space
And I know I lose control of the things that I say
Yeah, I was lookin' for a way out, now I can't escape
Nothin' happens after two, it's true, it's true
My bad habits lead to you


Ooh-ooh, ooh-ooh
My bad habits lead to you
Ooh-ooh, ooh-ooh


We took the long way 'round
And burned till the fun ran out, now


My bad habits lead to late nights endin' alone
Conversations with a stranger I barely know
Swearin' this'll be the last, but it probably won't
I got nothin' left to lose, or use, or do
My bad habits lead to wide eyes starin' at space
And I know I lose control of the things that I say
Yeah, I was lookin' for a way out, now I can't escape
Nothin' happens after two, it's true, it's true
My bad habits lead to you


Ooh-ooh, ooh-ooh
My bad habits lead to you
Ooh-ooh, ooh-ooh
My bad habits lead to you""",
    },
    "ES_08": {
        "title":  "Shivers",
        "artist": "Ed Sheeran",
        "lyrics": """I took an arrow to the heart
I never kissed a mouth that tastes like yours
Strawberries and then somethin' more
Ooh, yeah, I want it all
Lipstick on my guitar
Fill up the engine, we can drive real far
Go dancin' underneath the stars
Ooh, yeah, I want it all
Mmm, you got me feelin' like


I wanna be that guy, I wanna kiss your eyes
I wanna drink that smile, I wanna feel like I'm
Like my soul's on fire, I wanna stay up all day and all night
Yeah, you got me singin' like


Ooh, I love it when you do it like that
And when you're close up, give mе the shivers
Oh, baby, you wanna dance 'til thе sunlight cracks
And when they say the party's over, then we'll bring it right back
And we'll say, "Ooh, I love it when you do it like that"
And when you're close up, give me the shivers
Oh, baby, you wanna dance 'til the sunlight cracks
And when they say the party's over, then we'll bring it right back


Into the car
On the backseat in the moonlit dark
Wrap me up between your legs and arms
Ooh, I can't get enough
You know you could tear me apart
Put me back together and take my heart
I never thought that I could love this hard
Ooh, I can't get enough
Mmm, you got me feelin' like


I wanna be that guy, I wanna kiss your eyes
I wanna drink that smile, I wanna feel like I'm
Like my soul's on fire, I wanna stay up all day and all night
Yeah, you got me singin' like


Ooh, I love it when you do it like that
And when you're close up, give me the shivers
Oh, baby, you wanna dance 'til the sunlight cracks
And when they say the party's over, then we'll bring it right back
And we'll say, "Ooh, I love it when you do it like that"
And when you're close up, give me the shivers
Oh, baby, you wanna dance 'til the sunlight cracks
And when they say the party's over, then we'll bring it right back


Baby, you burn so hot, you make me shiver
With the fire you got, this thing we started
I don't want it to stop
You know you make me shiver-er-er
Baby, you burn so hot, you make me shiver
With the fire you got, this thing we started
I don't want it to stop
You know you make me shiver
Yeah, you got me singin' like


Ooh, I love it when you do it like that
And when you're close up, give me the shivers
Oh, baby, you wanna dance 'til the sunlight cracks
And when they say the party's over, then we'll bring it right back (Oh, no)
And we'll say, "Ooh, I love it when you do it like that"
And when you're close up, give me the shivers
Oh, baby, you wanna dance 'til the sunlight cracks
And when they say the party's over, then we'll bring it right back, hey""",
    },
    "ES_09": {
        "title":  "Overpass Graffiti",
        "artist": "Ed Sheeran",
        "lyrics": """This is a dark parade
Another rough patch to rain on
To rain on
I know your friends may say
This is a cause for celebration
Hip, hip, hooray, love


Photographs in sepia tones
So still, the fire's barely fighting the cold
Alone
There are times when I can feel your ghost
Just when I'm almost letting you go
The cards were stacked against us both


I will always love you for what it's worth
We'll never fade like graffiti on the overpass
And I know time may change the way you think of us
But I'll remember the way we were
You were the first full-stop love that will never leave
Baby, you will never be lost on me


This is a goddamn shame
I never wanted to break it
Leave us tainted
Know I should walk away
But I just can't replace us
Or even erase us


The car was stuck, the engine stalled
And both of us got caught out in the snow
Alone
There were times when I forget the lows
And think the highs were all that we'd ever known
The cards were stacked against us both


I will always love you for what it's worth
We'll never fade like graffiti on the overpass
And I know time may change the way you think of us
But I'll remember the way we were
You were the first full-stop love that will never leave
Baby, you will never be lost on me


Lost on me
Baby, you will never be lost on me
Lost on me


Well, I will always love you for what it's worth
We'll never fade like graffiti on the overpass, yeah
And I know time may change the way you think of us
But I'll remember the way we were
You were the first full-stop love that will never leave
Baby, you will never be lost on me


Yeah, yeah, yeah
Yeah, yeah, yeah, yeah
Lost on me
Ooh, graffiti on the overpass""",
    },
    "ES_10": {
        "title":  "The A Team",
        "artist": "Ed Sheeran",
        "lyrics": """White lips, pale face
Breathin' in the snowflakes
Burnt lungs, sour taste
Light's gone, days end
Struggling to pay rent
Long nights, strange men


And they say
She's in the Class A Team
Stuck in her daydream
Been this way since eighteen, but lately
Her face seems
Slowly sinking, wasting
Crumbling like pastries
And they scream
"The worst things in life come free to us"


'Cause we're just under the upper hand
And go mad for a couple grams
And she don't wanna go outside tonight
And in a pipe, she flies to the Motherland
Or sells love to another man
It's too cold outside
For angels to fly
Angels to fly


Ripped gloves, raincoat
Tried to swim and stay afloat
Dry house, wet clothes
Loose change, banknotes
Weary-eyed, dry throat
Call girl, no phone


And they say
She's in the Class A Team
Stuck in her daydream
Been this way since eighteen, but lately
Her face seems
Slowly sinking, wasting
Crumbling like pastries
And they scream
"The worst things in life come free to us"


'Cause we're just under the upper hand
And go mad for a couple grams
But she don't wanna go outside tonight
And in a pipe, she flies to the Motherland
Or sells love to another man
It's too cold outside
For angels to fly


An angel will die, covered in white
Closed eye and hopin' for a better life
This time, we'll fade out tonight
Straight down the line


And they say
She's in the Class A Team
Stuck in her daydream
Been this way since eighteen, but lately
Her face seems
Slowly sinking, wasting
Crumbling like pastries
And they scream
"The worst things in life come free to us"


And we're all under the upper hand
And go mad for a couple grams
And we don't wanna go outside tonight
And in a pipe, we fly to the Motherland
Or sell love to another man
It's too cold outside
For angels to fly


Angels to fly
Fly, fly
For angels to fly
To fly, to fly
Angels to die""",
    },
    "ES_11": {
        "title":  "Lego House",
        "artist": "Ed Sheeran",
        "lyrics": """I'm gonna pick up the pieces and build a LEGO house
If things go wrong, we can knock it down
My three words have two meanings, but there's one thing on my mind
It's all for you, mh


And it's dark in a cold December
But I got you to keep me warm
If you're broken, I'll mend ya
And I'll keep you sheltered from the storm that's raging on now


I'm out of touch, I'm out of love
I'll pick you up when you're gettin' down
And out of all these things I've done
I think I love you better now
I'm out of sight, I'm out of mind
I'll do it all for you in time
And out of all these things I've done
I think I love you better now, now


I'm gonna paint you by numbers and colour you in
If things go right, we can frame it, and put you on a wall
And it's so hard to say it, but I've been here before
Now, I'll surrender up my heart, and swap it for yours


I'm out of touch, I'm out of love
I'll pick you up when you're gettin' down
And out of all these things I've done
I think I love you better now
I'm out of sight, I'm out of mind
I'll do it all for you in time
And out of all these things I've done
I think I love you better now


Don't hold me down
I think the braces are breaking
And it's more than I can take


And it's dark in a cold December
But I got you to keep me warm
If you're broken, I'll mend ya
And I'll keep you sheltered from the storm that's raging on now


I'm out of touch, I'm out of love
I'll pick you up when you're gettin' down
And out of all these things I've done
I think I love you better now
I'm out of sight, I'm out of mind
I'll do it all for you in time
And out of all these things I've done
I think I love you better now


I'm out of touch, I'm out of love
I'll pick you up when you're gettin' down
And out of all these things I've done
I will love you better now""",
    },
    "ES_12": {
        "title":  "Happier",
        "artist": "Ed Sheeran",
        "lyrics": """Walkin' down 29th and Park
I saw you in another's arm
Only a month we've been apart
You look happier
Saw you walk inside a bar
He said somethin' to make you laugh
I saw that both your smiles were twice as wide as ours
Yeah, you look happier, you do


Ain't nobody hurt you like I hurt you
But ain't nobody love you like I do
Promise that I will not take it personal, baby
If you're movin' on with someone new


'Cause, baby, you look happier, you do
My friends told me one day I'll feel it, too
And until then, I'll smile to hide the truth
But I know I was happier with you


Hey-yeah, hey-yeah, hey-yeah


Sat in the corner of the room
Everything's reminding me of you
Nursin' an empty bottle and tellin' myself
You're happier, aren't you? (Hey-yeah, hey-yeah, hey-yeah)


Oh, ain't nobody hurt you like I hurt you (Hey-yeah, hey-yeah, hey-yeah)
But ain't nobody need you like I do (Hey-yeah, hey-yeah, hey-yeah)
I know that there's others that deserve you (Hey-yeah, hey-yeah, hey-yeah)
But, my darlin', I am still in love with you


But I guess you look happier, you do
My friends told me one day I'll feel it, too
I could try to smile to hide the truth
But I know I was happier with you


'Cause, baby, you look happier, you do
I knew one day you'd fall for someone new
But if he breaks your heart like lovers do
Just know that I'll be waitin' here for you""",
    },
}
