# Auto-generated by 03_build_schema.py — do not edit manually.
# Merges all artist schemas into a single FULL_CATALOG dict.

from schemas.RTJ_schema import RTJ_SCHEMA
from schemas.KL_schema import KL_SCHEMA
from schemas.JC_schema import JC_SCHEMA
from schemas.DR_schema import DR_SCHEMA
from schemas.EM_schema import EM_SCHEMA
from schemas.TC2_schema import TC2_SCHEMA
from schemas.MM_schema import MM_SCHEMA
from schemas.CH_schema import CH_SCHEMA
from schemas.NS_schema import NS_SCHEMA
from schemas.CG_schema import CG_SCHEMA
from schemas.GD_schema import GD_SCHEMA
from schemas.BD_schema import BD_SCHEMA
from schemas.TC_schema import TC_SCHEMA
from schemas.JI_schema import JI_SCHEMA
from schemas.SS_schema import SS_SCHEMA
from schemas.KM_schema import KM_SCHEMA
from schemas.JP_schema import JP_SCHEMA
from schemas.GW_schema import GW_SCHEMA
from schemas.CW_schema import CW_SCHEMA
from schemas.TS_schema import TS_SCHEMA
from schemas.TW_schema import TW_SCHEMA
from schemas.DL_schema import DL_SCHEMA
from schemas.AG_schema import AG_SCHEMA
from schemas.ES_schema import ES_SCHEMA
from schemas.BE_schema import BE_SCHEMA
from schemas.HS_schema import HS_SCHEMA
from schemas.OR_schema import OR_SCHEMA
from schemas.DP_schema import DP_SCHEMA
from schemas.DS_schema import DS_SCHEMA
from schemas.CB_schema import CB_SCHEMA
from schemas.JB_schema import JB_SCHEMA
from schemas.LCD_schema import LCD_SCHEMA
from schemas.BN_schema import BN_SCHEMA
from schemas.GZ_schema import GZ_SCHEMA

FULL_CATALOG = {
    **RTJ_SCHEMA,
    **KL_SCHEMA,
    **JC_SCHEMA,
    **DR_SCHEMA,
    **EM_SCHEMA,
    **TC2_SCHEMA,
    **MM_SCHEMA,
    **CH_SCHEMA,
    **NS_SCHEMA,
    **CG_SCHEMA,
    **GD_SCHEMA,
    **BD_SCHEMA,
    **TC_SCHEMA,
    **JI_SCHEMA,
    **SS_SCHEMA,
    **KM_SCHEMA,
    **JP_SCHEMA,
    **GW_SCHEMA,
    **CW_SCHEMA,
    **TS_SCHEMA,
    **TW_SCHEMA,
    **DL_SCHEMA,
    **AG_SCHEMA,
    **ES_SCHEMA,
    **BE_SCHEMA,
    **HS_SCHEMA,
    **OR_SCHEMA,
    **DP_SCHEMA,
    **DS_SCHEMA,
    **CB_SCHEMA,
    **JB_SCHEMA,
    **LCD_SCHEMA,
    **BN_SCHEMA,
    **GZ_SCHEMA,
}
