# Auto-generated by 03_build_schema.py — do not edit manually.
# Artist: Grateful Dead  |  Code: GD
# Songs included: 15  |  Missing: 0

GD_SCHEMA = {
    "GD_01": {
        "title":  "Minglewood Blues",
        "artist": "Grateful Dead",
        "lyrics": """I was born in the desert
Raised in a lion's den
I was born in the desert
Raised in a lion's den
Oh, my number one occupation
Is stealing women from their men


Well, now the doctor call me crazy
Sometimes I am, sometimes I ain't
Said now the doctor call me crazy
Sometimes I am, sometimes I ain't
Yes, and the preacher man call me sinner
But his little girl call me a saint
Well a couple shots of whiskey
Women around here start looking good
I said a couple shots of whiskey
Women round here start looking good
A couple more shots of whiskey
I'm going down to Minglewood


Said, I was born in the desert
Raised in a lion's den
Said, I was born in the desert
Raised in a lion's den
Yes and my number one occupation
Is stealing women from their men
I was born in the desert
Raised in a lion's den
I was born in the desert
Raised in a lion's den
Oh, my number one occupation
Is stealing women from their men""",
    },
    "GD_02": {
        "title":  "They Love Each Other",
        "artist": "Grateful Dead",
        "lyrics": """Merry run around, sailin' up and down
Looking for a shove in some direction
Got it from the top, it's nothing you can stop
Lord, you know they made a fine connection


They love each other
Lord, you can see that it's true
Lord, you can see that it's true
Lord, you can see that it's true


He could pass his time, around some other line
But you know he chose this place beside her
Don't get in their way, there's nothing you can say
Nothing that you need to add or do


They love each other
Lord, you can see that it's true
Lord, you can see that it's true
Lord, you can see that it's true




It's nothing, they explain, it's like a diesel train
You better not be there when it rolls over
And when that train rolls in, you wonder where it's been
You gotta try and see a little further


Though you'll make a noise, just can't hear your voice
All the dizzy ride on your cold shoulder

Won't you believe what I say is true?
Everything I did I heard it first from you


Everything I tell you, I heard it first from you
Heard your news report, you know you're falling short
Pretty soon, we'll trust you for the weather
When that ship comes in, you won't know where it's been
You got to try to see a little further


They love each other
Lord, you can see that it's true
Lord, you can see that it's true
Lord, you can see that it's true""",
    },
    "GD_03": {
        "title":  "Cassidy",
        "artist": "Grateful Dead",
        "lyrics": """I have seen where the wolf has slept by the
Silver stream
I can tell by the mark he left you were in his
Dream
Ah, child of countless trees
Ah, child of boundless seas
What you are, what you're meant to be
Speaks his name, though you were born to me
Born to me
Cassidy...


Lost now on the country miles in his cadillac
I can tell by the way you smile he's rolling back
Come wash the nighttime clean
Come grow this scorched ground green
Blow the horn, tap the tambourine
Close the gap of the dark years in between
You and me
Cassidy...


Quick beats in an icy heart
Catch-colt draws a coffin cart
There he goes now, here she starts:
Hear her cry
Flight of the seabirds, scattered like lost words
Wheel to the storm and fly


Fare thee well now
Let your life proceed by its own design
Nothing to tell now
Let the words be yours, I'm done with mine
(repeat verse)

Flight of the seabirds, scattered like lost words
Wheel to the storm and fly""",
    },
    "GD_04": {
        "title":  "Loser",
        "artist": "Grateful Dead",
        "lyrics": """If I had a gun for every ace I have drawn
I could arm a town the size of Abilene
Don't you push me, baby, because I'm moanin' low
And you know I'm only in it for the gold


All that I am asking for is ten gold dollars
And I could pay you back with one good hand
You can look around about the wide world over
And you'll never find another honest man


Last fair deal in the country, Sweet Suzie
Last fair deal in the town
Put your gold money where your love is, baby
Before you let my deal go down


Don't you push me, baby, 'cause I'm moanin' low
And I know a little something you won't ever know
Don't you touch hard liquor, just a cup of cold coffee
Gotta get up in the morning and go


Everybody's braggin' and drinkin' that wine
I can tell the Queen of Diamonds by the way she shines
Come to daddy on an inside straight
Well I got no chance of losin' this time


Last fair deal in the country
Last fair deal in the town
Put your gold money where your love is, baby
Before you let my deal go down


Everybody's braggin' and drinkin' that wine
I can tell the Queen of Diamonds by the way she shines
Come to daddy on an inside straight
Well I got no chance of losin' this time""",
    },
    "GD_05": {
        "title":  "Jack Straw",
        "artist": "Grateful Dead",
        "lyrics": """We can share the women, we can share the wine
We can share what we got of yours cause we done shared all of mine
Keep on rollin', just a mile to go;
Keep on rollin' my old buddy, you're movin' much too slow


I just jumped the watchman, right outside the fence
Took his rings, four bucks in change, ain't that Heaven sent?
Hurts my ears to listen, Shannon, burns my eyes to see;
Cut down a man in cold blood, Shannon, might as well've been me


We used to play for silver, now we play for life;
And one's for sport and one's for blood at the point of a knife
And now the die is shaken, now the die must fall
There ain't a winner in the game, he don't go home with all
Not with all


Leavin' Texas, fourth day of July
Sun so hot, the clouds so low, the eagles filled the sky
Catch the Detroit Lightning out of Santa Fe
The Great Northern out of Cheyenne, from sea to shining sea


Gotta go to Tulsa, first train we can ride
Gotta settle one old score, one small point of pride
There ain't a place a man can hide, Shannon, will keep him from the sun
Ain't a bed can give us rest now, you keep us on the run


Jack Straw from Wichita
Cut his buddy down
Dug for him a shallow grave
And laid his body down
Half a mile from Tucson
By the morning light
One man gone and another to go
My old buddy, you're moving much
Too slow


We can share the women, we can share the wine""",
    },
    "GD_06": {
        "title":  "Tennessee Jed",
        "artist": "Grateful Dead",
        "lyrics": """Cold iron shackles, ball and chain
Listen to the whistle of the evening train
You know you bound to wind up dead
If you don't head back to Tennessee, Jed


Rich man step on my poor head
When you get up, you better butter my bread
Well, you know it's like I said
You better head back to Tennessee, Jed


Tennessee, Tennessee
There ain't no place I'd rather be
Baby, won't you carry me?
Back to Tennessee




Drink all day and rock all night
Law come to get you if you don't walk right
Got a letter this morning and it, all it read:
"You better head back to Tennessee, Jed"


I dropped four flights and cracked my spine
Honey, come quick with the iodine
Catch a few winks down under the bed
Then head back to Tennessee, Jed


Tennessee, Tennessee
There ain't no place I'd rather be
Baby, won't you carry me?
Back to Tennessee




I run into Charlie Phogg
He blacked my eye and he kicked my dog
My dog, he turned to me and he said:
"Let's head back to Tennessee, Jed"


I woke up a-feeling mean
Went down to play the slot machine
The wheels turned 'round and the letters read:
"Better head back to Tennessee, Jed"


Tennessee, Tennessee
There ain't no place I'd rather be
Baby, won't you carry me?
Back to Tennessee






Tennessee, Tennessee
There ain't no place I'd rather be
Baby, won't you carry me?
Back to Tennessee""",
    },
    "GD_07": {
        "title":  "Passenger",
        "artist": "Grateful Dead",
        "lyrics": """Firefly, can you see me?
Shine on, glowing, brief and brightly
Could you imagine? One summer day
That same night be on your way
Do you remember? Hearts were too cold
Seasons have frozen us into our souls
People were saying the whole world is burning
Ashes have scattered too hard to turn


Upside out or inside down
False alarm, the only game in town
No man's land, the only game in town
Terrible, the only game in town


Passenger, don't you hear me?
Destination seen unclearly
What is a man deep down inside?
But a raging beast with nothing to hide


Upside out or inside down
False alarm, the only game in town
No man's land, the only game in town
Terrible, the only game in town""",
    },
    "GD_08": {
        "title":  "Peggy-O",
        "artist": "Grateful Dead",
        "lyrics": """As we rowed up to Fennario
As we rowed up to Fennario
Our captain fell in love
With a lady like a dove
And he called her by name, Pretty Peggy-O
Come steppin' down the stairs Pretty Peggy-O
Come steppin' down the stairs Pretty Peggy-O
Come steppin' down the stairs, holding back your yellow hair
In the hand??? ???, William-O
Will you marry me Pretty Peggy-O?
Will you marry me Pretty Peggy-O?
If you will marry me, I will set your cities free
And free all the people of the area-O
I would marry you sweet William-O
I would marry you sweet William-O
I would marry you but your guineas are too few
And I fear my mama would be angry-O
What would your mama think Pretty Peggy-O
What would your mama think Pretty Peggy-O
What would your mama think if she heard my guineas clink
Saw me riding at the head of my soldiers-O
If ever I return Pretty Peggy-O
If ever I return Pretty Peggy-O
If ever I return, all your cities I will burn
Destroy all the people in the area-O
Come steppin' down the stairs Pretty Peggy-O
Come steppin' down the stairs Pretty Peggy-O
Come steppin' down the stairs, holding back your yellow hair
Bid a last farewell to your William-O
Sweet William he is dead Pretty Peggy-O
Sweet William he is dead Pretty Peggy-O
Sweet William he is dead and he died for a maid
And he spent the loot he had in the country-O
As we rowed up to Fennario
As we rowed up to Fennario
Our captain fell in love
With a lady like a dove
And he called her by name, Pretty Peggy-O""",
    },
    "GD_09": {
        "title":  "Me & My Uncle",
        "artist": "Grateful Dead",
        "lyrics": """Me and my uncle went riding down
South Colorado, West Texas bound
We stopped over in Santa Fe
That being the point just about half way
And you know it was the hottest part of the day


I took the horses up to the stall
Went to the barroom, ordered drinks for all
Three days in the saddle, you know my body hurt
It being summer, I took off my shirt
And I tried to wash off some of that dusty dirt


West Texas cowboys, they's all around
With liquor and money, they're loaded down
So soon after payday, know it seemed a shame;
You know my uncle, he starts a friendly game
High-low jack and the winner take the hand




My uncle starts winning; cowboys got sore
One of them called him, and then two more
Accused him of cheating; oh no, it couldn't be
I know my uncle, he's as honest as me
And I'm as honest as a Denver man can be


One of them cowboys, he starts to draw
And I shot him down, lord he never saw
Shot me another, oh damn he won't grow old
In the confusion, my uncle grabbed the gold
And we high-tailed it down to Mexico


I love those cowboys, I love their gold
I loved my uncle, god rest his soul
Taught me good, Lord, taught me all I know
Taught me so well, I grabbed that gold
And I left his dead ass there by the side of the road""",
    },
    "GD_10": {
        "title":  "Friend of the Devil",
        "artist": "Grateful Dead",
        "lyrics": """I lit out from Reno, I was trailed by twenty hounds
Didn't get to sleep that night 'til the morning came around


Set out runnin' but I take my time
A friend of the devil is a friend of mine
If I get home before daylight
Just might get some sleep tonight


Ran into the devil, babe, he loaned me twenty bills
Spent the night in Utah in a cave up in the hills


Set out runnin' but I take my time
A friend of the devil is a friend of mine
If I get home before daylight
Just might get some sleep tonight


I ran down to the levee but the devil caught me there
He took my twenty dollar bill and he vanished in the air


Set out runnin' but I take my time
A friend of the devil is a friend of mine
If I get home before daylight
Just might get some sleep tonight


Got two reasons why I cry away each lonely night:
The first one's named sweet Anne Marie, and she's my heart's delight
The second one is prison, babe, and the sheriff's on my trail
And if he catches up with me, I'll spend my life in jail


Got a wife in Chino, babe, and one in Cherokee
The first one says she's got my child, but it don't look like me


Set out runnin' but I take my time
A friend of the devil is a friend of mine
If I get home before daylight
Just might get some sleep tonight


Got two reasons why I cry away each lonely night:
The first one's named sweet Anne Marie, and she's my heart's delight
The second one is prison, babe, the sheriff's on my trail
And if he catches up with me, I'll spend my life in jail


Got a wife in Chino, babe, and one in Cherokee
The first one says she's got my child, but it don't look like me


Set out runnin' but I take my time
A friend of the devil is a friend of mine
If I get home before daylight
Just might get some sleep tonight""",
    },
    "GD_11": {
        "title":  "Truckin'",
        "artist": "Grateful Dead",
        "lyrics": """Truckin', got my chips cashed in
Keep truckin', like the do-dah man
Together, more or less in line
Just keep truckin' on


Arrows of neon and flashing marquees out on Main Street
Chicago, New York, Detroit and it's all on the same street
Your typical city involved in a typical daydream
Hang it up and see what tomorrow brings


Dallas, got a soft machine;
Houston, too close to New Orleans
New York's got the ways and means
But just won't let you be, oh no


Most of the cats that you meet on the streets speak of true love
Most of the time they're sittin' and cryin' at home
One of these days they know they gotta get goin'
Out of the door and down to the street all alone


Truckin', like the do-dah man
Once told me "You've got to play your hand"
Sometimes the cards ain't worth a dime
If you don't lay 'em down


Sometimes the light's all shinin' on me
Other times I can barely see
Lately it occurs to me
What a long, strange trip it's been


What in the world ever became of sweet Jane?
She lost her sparkle, you know she isn't the same
Livin' on reds, vitamin C, and cocaine
All a friend can say is "Ain't it a shame"


Truckin' up to Buffalo
Been thinkin', you got to mellow slow
Takes time to pick a place to go
And just keep truckin' on


Sittin' and starin' out of the hotel window
Got a tip they're gonna kick the door in again
I'd like to get some sleep before I travel
But if you got a warrant, I guess you're gonna come in


Busted down on Bourbon Street
Set up like a bowlin' pin
Knocked down, it gets to wearin' thin
They just won't let you be, oh no


You're sick of hangin' around and you'd like to travel
Get tired of travelin' and you want to settle down
I guess they can't revoke your soul for tryin'
Get out of the door and light out and look all around


Sometimes the light's all shinin' on me
Other times I can barely see
Lately it occurs to me
What a long, strange trip it's been


Truckin', I'm a goin' home
Whoa whoa baby, back where I belong
Back home, sit down and patch my bones
And get back truckin' on
Hey now, get back truckin' home""",
    },
    "GD_12": {
        "title":  "Casey Jones",
        "artist": "Grateful Dead",
        "lyrics": """Driving that train, high on cocaine
Casey Jones you better, watch your speed
Trouble ahead, trouble behind
And you know that notion just crossed my mind


This old engine
Makes it on time
Leaves Central Station
About a quarter to nine
Hits river junction
At seventeen to
At a quarter to ten
You know it's traveling again


Driving that train, high on cocaine
Casey Jones you better watch your speed
Trouble ahead, trouble behind
And you know that notion just crossed my mind


Trouble ahead
A lady in red
Take my advice
You'd be better off dead
Switch-man sleeping
Train hundred and two
Is on the wrong track
And headed for you


Driving that train, high on cocaine
Casey Jones you better, watch your speed
Trouble ahead, trouble behind
And you know that notion just crossed my mind


Trouble with you is
The trouble with me
Got two good eyes
But we still don't see
Come round the bend
You know it's the end
The fireman screams and
The engine just gleams


Driving that train, high on cocaine
Casey Jones you better, watch your speed
Trouble ahead, trouble behind
And you know that notion just crossed my mind


Driving that train, high on cocaine
Casey Jones you better, watch your speed
Trouble ahead, trouble behind
And you know that notion just crossed my mind


And you know that notion
Just crossed my mind""",
    },
    "GD_13": {
        "title":  "Touch of Grey",
        "artist": "Grateful Dead",
        "lyrics": """Must be getting early
Clocks are running late
Paint-by-number morning sky looks so phony
Dawn is breaking everywhere
Light a candle, curse the glare
Draw the curtains, I don't care 'cause it's all right


I will get by
I will get by
I will get by
I will survive


I see you've got your fist out
Say your piece and get out
Yes, I get the gist of it, but it's all right
Sorry that you feel that way
The only thing there is to say
Every silver lining's got a touch of grey


I will get by
I will get by
I will get by
I will survive


It's a lesson to me
The Ables and the Bakers and the C's
The ABCs we all must face
Try to keep a little grace




It's a lesson to me
The Deltas and the East and the Freeze
The ABCs we all think of
To try to win a little love


I know the rent is in arrears
The dog has not been fed in years
It's even worse than it appears, but it's all right
Cow is giving kerosene
Kid can't read at seventeen
The words he knows are all obscene, but it's all right


I will get by
I will get by
I will get by
I will survive


The shoe is on the hand it fits
There's really nothing much to it
Whistle through your teeth and spit 'cause it's all right
Oh, well, a touch of grey kind of suits you anyway
And that was all I had to say, and it's all right


I will get by
I will get by
I will get by
I will survive


We will get by
We will get by
We will get by
We will survive
We will get by
We will get by
We will get by""",
    },
    "GD_14": {
        "title":  "Ripple",
        "artist": "Grateful Dead",
        "lyrics": """If my words did glow with the gold of sunshine
And my tunes were played on the harp unstrung
Would you hear my voice come through the music?
Would you hold it near as it were your own?


It's a hand-me-down, the thoughts are broken
Perhaps they're better left unsung
I don't know, don't really care
Let there be songs to fill the air


Ripple in still water
When there is no pebble tossed
Nor wind to blow


Reach out your hand, if your cup be empty
If your cup is full, may it be again
Let it be known there is a fountain
That was not made by the hands of men


There is a road, no simple highway
Between the dawn and the dark of night
And if you go, no one may follow
That path is for your steps alone


Ripple in still water
When there is no pebble tossed
Nor wind to blow


You who choose to lead must follow
But if you fall you fall alone
If you should stand then who's to guide you?
If I knew the way I would take you home""",
    },
    "GD_15": {
        "title":  "Scarlet Begonias",
        "artist": "Grateful Dead",
        "lyrics": """As I was walking round Grosvenor Square
Not a chill to the winter
But a nip to the air
From the other direction
She was calling my eye
It could be an illusion
But I might as well try
Might as well try

She had rings on her fingers and
Bells on her shoes
And I knew without asking she was
Into the blues
She wore scarlet begonias
Tucked into her curls
I knew right away
She was not like other girls
Other girls

In the thick of the evening
When the dealing got rough
She was too pat to open
And too cool to bluff
As I picked up my matches and
Was closing the door
I had one of those flashes:
I'd been there before
Been there before

Well, I ain't often right
But I've never been wrong
It seldom turns out the way
It does in the song
Once in a while
You get shown the light
In the strangest of places
If you look at it right

Well, there ain't nothing wrong
With the way she moves
Or scarlet begonias or a
Touch of the blues
And there's nothing wrong with
The look that's in her eye
I had to learn the hard way
To let her pass by
Let her pass by

The wind in the willows played tea for two
The sky was yellow and the sun was blue
Strangers stopping strangers
Just to shake their hand
Everybody's playing
In the Heart of Gold Band
Heart of Gold Band""",
    },
}
