# Auto-generated by 03_build_schema.py — do not edit manually.
# Artist: Gillian Welch  |  Code: GW
# Songs included: 12  |  Missing: 0

GW_SCHEMA = {
    "GW_01": {
        "title":  "Everything Is Free",
        "artist": "Gillian Welch",
        "lyrics": """Everything is free now
That's what they say
Everything I ever done
Gonna give it away
Someone hit the big score
They figured it out
That we're gonna do it anyway
Even if it doesn't pay


I can get a tip jar
Gas up the car
And try to make a little change
Down at the bar
Or I can get a straight job
I done it before
Never minded working hard
It's who I'm working for


And everything is free now
That's what they say
Everything I ever done
Gotta give it away
Someone hit the big score
They figured it out
That we're gonna do it anyway
Even if it doesn't pay




Every day I wake up
Hummin' a song
But I don't need to run around
I'll just stay at home
And sing a little love song
My love and myself
If there's something that you wanna hear
You can sing it yourself


'Cause everything is free now
That's what I said
No one's gotta listen to
The words in my head
Someone hit the big score
And I figured it out
And I'm gonna do it anyway
Even if it doesn't pay""",
    },
    "GW_02": {
        "title":  "Time (The Revelator)",
        "artist": "Gillian Welch",
        "lyrics": """Darling remember, when you come to me
I'm the pretender; I'm not what I'm supposed to be
But who could know if I'm a traitor?
Time's the revelator


They caught the Katy, and left me a mule to ride
The fortune lady came along, she walked beside
But every word seemed to date her
Time's the revelator, the revelator




Up in the morning, up and on the line
Drive into Corning, and all the spindles whine
And every day is getting straighter
Time's the revelator, the revelator




Leaving the valley, and fucking out of sight
I'll go back to Cali where I can sleep out every night
And watch the waves and move the fader
Time's the revelator, the revelator


Queen of fakes and imitators
Time's the revelator""",
    },
    "GW_03": {
        "title":  "Elvis Presley Blues",
        "artist": "Gillian Welch",
        "lyrics": """I was thinking that night about Elvis
Day that he died, day that he died
I was thinking that night about Elvis
Day that he died, day that he died


Just a country boy that combed his hair
And put on a shirt his mother made and went on the air
And he shook it like a chorus girl
And he shook it like a Harlem queen
And he shook it like a midnight rambler, baby
Like you never seen
Never seen


I was thinking that night about Elvis
Day that he died, day that he died
I was thinking that night about Elvis
Day that he died, day that he died


'Cause he took it all out of black and white
Grabbed his wand in the other hand and he held on tight
And he shook it like a hurricane
And he shook it like to make it break
And he shook it like a holy roller, baby
With his soul at stake
Soul at stake


I was thinking that night about Elvis
Day that he died, day that he died
I was thinking that night about Elvis
Day that he died, day that he died


He was all alone in a long decline
Thinking how happy John Henry was that he fell down and died
When he shook it and he rang like silver
And he shook it and it shined like gold
And he shook it and he beat that steam drill, baby
Well bless my soul
Well bless my soul


And he shook it and he beat that steam drill, baby
Well bless my soul, what's wrong with me?


I was thinking that night about Elvis
Day that he died, day that he died
I was thinking that night about Elvis
Day that he died, day that he died


Just a country boy that combed his hair
And put on a shirt his mother made and went on the air
And he shook it like a chorus girl
And he shook it like a Harlem queen
And he shook it like a midnight rambler, baby
Like you never seen
Never seen


Like you never seen
Never seen""",
    },
    "GW_04": {
        "title":  "Orphan Girl",
        "artist": "Gillian Welch",
        "lyrics": """I am an orphan on God's highway
But I'll share my troubles, if you go my way
I have no mother, no father
No sister, no brother
I am an orphan girl

I have had friendships, pure and golden
But the ties of kinship, I have not known them
I know no mother, no father
No sister, no brother
I am an orphan girl

But when He calls me, I will be able
To meet my family at God's table
I'll meet my mother, my father
My sister, my brother
No more orphan girl

Blessed Savior, make me willing
And walk beside me until I'm with them
Be my mother, my father
My sister, my brother
I am an orphan girl""",
    },
    "GW_05": {
        "title":  "Acony Bell",
        "artist": "Gillian Welch",
        "lyrics": """The fairest bloom the mountain knows
Is not an iris or a wild rose
But the little flower of which I'll tell
Known as the brave acony bell


Just a simple flower, so small and plain
With a pearly hue and a little known name
But the yellow birds sing when they see it bloom
For they know that spring is coming soon


Well, it makes its home amid the rocks and the rills
Where the snow lies deep on the windy hills
And it tells the world, "Why should I wait?
This ice and snow is gonna melt away"


And so I'll sing that yellow bird's song
For the troubled times will soon be gone""",
    },
    "GW_06": {
        "title":  "Look at Miss Ohio",
        "artist": "Gillian Welch",
        "lyrics": """Oh me oh my oh
Look at Miss Ohio
She’s a-running around with her ragtop down
She says "I wanna do right, but not right now"


Gonna drive to Atlanta
And live out this fantasy
Running around with the ragtop down
Yeah, I wanna do right, but not right now




Had your arm around her shoulder
A regimental soldier
Mamma starts pushing that wedding gown
Yeah, you wanna do right, but not right now


Oh me oh my oh
Would you look at Miss Ohio?
She’s a-running around with the ragtop down
She says "I wanna do right, but not right now"




I know all about it
So you don’t have to shout it
I’m gonna straighten it out somehow
Yeah, I wanna do right, but not right now


Oh me oh my oh
Look at Miss Ohio
She a-running around with her ragtop down
She says "I wanna do right, but not right now"
Oh, I want do right, but not right now""",
    },
    "GW_07": {
        "title":  "One More Dollar",
        "artist": "Gillian Welch",
        "lyrics": """A long time ago, I left my home
For a job in the fruit trees
But I missed those hills with the windy pines
Their song seemed to suit me
So I sent my wages to my home
Said we'd soon be together
For the next good crop would pay my way
And I would come home forever

One more dime to show for my day
One more dollar and I'm on my way
When I reach those hills, boys, I'll never roam
One more dollar and I'm going home

'No work,' said the boss at the bunkhouse door
'There's a freeze on the branches'
So when the dice came out at the bar downtown
I rolled and I took my chances

One more dime to show for my day
One more dollar and I'm on my way
When I reach those hills, boys, I'll never roam
Just one more dollar and I'm going home

A long time ago, I left my home
Just a boy passing twenty
Could you spare a coin and a Christian prayer?
For my luck has turned against me

One more dime to show for my day
One more dollar and I'm on my way
When I reach those hills, boys, I'll never roam
Just one more dollar and I'm going home

One more dollar
Boys, I'm going home""",
    },
    "GW_08": {
        "title":  "By the Mark",
        "artist": "Gillian Welch",
        "lyrics": """When I cross over
I will shout and sing
I will know my savior
By the mark where the nails have been

By the mark where the nails have been
By the sign upon his precious skin
I will know my savior when I come to him
By the mark where the nails have been

A man of riches
May claim a crown of jewels
But the king of heaven
Can be told from the prince of fools

By the mark where the nails have been
By the sign upon his precious skin
I will know my savior when I come to him
By the mark where the nails have been

On Calvary Mountain
Where they made him suffer so
All my sin was paid for
A long, long time ago

By the mark where the nails have been
By the sign upon his precious skin
I will know my savior when I come to him
By the mark where the nails have been""",
    },
    "GW_09": {
        "title":  "Revelator",
        "artist": "Gillian Welch",
        "lyrics": """Darling remember, when you come to me
I'm the pretender; I'm not what I'm supposed to be
But who could know if I'm a traitor?
Time's the revelator


They caught the Katy, and left me a mule to ride
The fortune lady came along, she walked beside
But every word seemed to date her
Time's the revelator, the revelator




Up in the morning, up and on the line
Drive into Corning, and all the spindles whine
And every day is getting straighter
Time's the revelator, the revelator




Leaving the valley, and fucking out of sight
I'll go back to Cali where I can sleep out every night
And watch the waves and move the fader
Time's the revelator, the revelator


Queen of fakes and imitators
Time's the revelator""",
    },
    "GW_10": {
        "title":  "I Dream a Highway",
        "artist": "Gillian Welch",
        "lyrics": """Oh I dream a highway back to you, love
A winding ribbon with a band of gold
A silver vision come and rest my soul
I dream a highway back to you


John, he's kicking out the footlights
The Grand Ole Opry's got a brand new band
Lord, let me die with a hammer in my hand
I dream a highway back to you


I think I'll move down into Memphis
And thank the hatchet man who forked my tongue
I lie and wait until the wagons come
And dream a highway back to you


The getaway kicking up cinders
An empty wagon full of rattling bones
Moon in the mirror on a three-hour jones
I dream a highway back to you


Oh I dream a highway back to you, love
A winding ribbon with a band of gold
A silver vision come arrest my soul
And I dream a highway back to you


Which lover are you, Jack of Diamonds?
Now you be Emmylou and I'll be Gram
I'll send a letter, don't know who I am
I dream a highway back to you


I'm an indisguisable shade of twilight
Any second now, I'm gonna turn myself on
In the blue display of the cool cathode ray
I dream a highway back to you


I wish you knew me, Jack of Diamonds
Fire-riding, wheeling when I laid 'em up
Drank whiskey with my water, sugar with my tea
My sails in rags with the staggers and the jags
I dream a highway back to you


Oh I dream a highway back to you, love
A winding ribbon with a band of gold
A silver vision convalesced my soul
I dream a highway back to you


Now give me some of what you're having
I'll take you as a viper into my head
A knife into my bed, arsenic when I'm fed
And I dream a highway back to you


Hang overhead from all directions
Radiation from the porcelain light
Blind and blistered by the morning white
I dream a highway back to you


Sunday morning at the diner
Hollywood trembles on the verge of tears
I watched the waitress for a thousand years
Saw a wheel inside a wheel, heard a call within a call
And I dreamed a highway back to you


Oh I dream a highway back to you, love
A winding ribbon with a band of gold
A silver vision convalesced my soul
I dream a highway back to you


Step into the light, poor Lazarus
Don't lie alone behind the window shade
Let me see the mark death made
And I dream a highway back to you
I dream a highway back to you


What will sustain us through the winter?
Where did last year's lessons go?
Walk me out into the rain and snow
I dream a highway back to you


Oh I dream a highway back to you, love
A winding ribbon with a band of gold
A silver vision come and bless my soul
I dream a highway back to you
I dream a highway back to you


Oh I dream a highway back to you, love
A winding ribbon with a band of gold
A silver vision come and bless my soul
I dream a highway back to you""",
    },
    "GW_11": {
        "title":  "Dear Someone",
        "artist": "Gillian Welch",
        "lyrics": """I wanna go all over the world and start living free
I know that there's somebody who is waiting for me
I'll build a boat, steady and true
As soon as it's done, I'm gonna sail along in a dream
Of my dear someone


One little star smiling tonight knows where you are
Stay, little star, steady and bright to guide me afar
Rush, little wind, over the deep, for now I've begun
Hurry and take me straight into the arms
Of my dear someone


Hurry and take me into the arms
Of my dear someone""",
    },
    "GW_12": {
        "title":  "Rock of Ages",
        "artist": "Gillian Welch",
        "lyrics": """Round, round, wanna go round
Wanna see the rock of ages
When my body gives out
Gonna read the final pages


Oh, my mother is gone
She told me I should meet her
Someday streets of gold
Gonna guide me on to greet her


Once my father sat down
And told me of the prophets
Matthew, Mark, Luke, and John
They're gone but not forgotten


Round, round, wanna go round
Wanna see the rock of ages
Till my body gives out
Gonna read the gospel pages


Moses heard a voice
It called him up the mountain
Forty days had set
When Moses come a shoutin'


Round, round, wanna go round
Wanna see the rock of ages
When my body gives out
Gonna read the final pages


Round, round, wanna go round
Wanna see the rock of ages
Till my body gives out
Gonna read the gospel pages


Round, round, wanna go round
Wanna see the rock of ages
When my body gives out
Gonna read the final pages""",
    },
}
