# Auto-generated by 03_build_schema.py — do not edit manually.
# Artist: Gorillaz  |  Code: GZ
# Songs included: 12  |  Missing: 0

GZ_SCHEMA = {
    "GZ_01": {
        "title":  "Feel Good Inc.",
        "artist": "Gorillaz",
        "lyrics": """Ha-ha-ha-ha-ha-ha-ha-ha-ha-ha-ha-ha
Feel good
Sha-ba, sha-ba, sha-ba-da-ba, feel good
Sha-ba, sha-ba, sha-ba-da-ba, feel good
Sha-ba, sha-ba, sha-ba-da-ba, feel good
Sha-ba, sha-ba, sha-ba-da-ba, feel good
Sha-ba, sha-ba, sha-ba-da-ba, feel good
Sha-ba, sha-ba, sha-ba-da-ba, feel good
(Change, change, change, change)
Sha-ba, sha-ba, sha-ba-da-ba, feel good
(Change, change, change, change)
Sha-ba, sha-ba, sha-ba-da-ba, feel good


City's breaking down on a camel's back
They just have to go, 'cause they don't know wack
So all ya fill the streets, it's appealing to see
You won't get undercounted 'cause you're damn-ass free
You got a new horizon, it's ephemeral style
A melancholy town where we never smile
And all I wanna hear is the message beep
My dreams, they gotta kiss because I don't get sleep, no
*Beep
*


Windmill, windmill for the land
Turn forever, hand in hand
Take it all in on your stride
It is ticking, falling down
Love forever, love is free
Let's turn forever, you and me
Windmill, windmill for the land
Is everybody in?


Laughin' gas, these hazmats, fast cats
Linin' 'em up like ass cracks
Play these ponies at the track
It's my chocolate attack
Shit, I'm steppin' in the heart of this here (Yeah)
Care Bear repping in harder this year (Yeah)
Watch me as I gravitate, ha-ha-ha-ha-ha!
Yo, we gon' ghost town this Motown
With yo' sound, you in the blink
Gon' bite the dust, can't fight with us
With yo' sound, you kill the Inc
So don't stop, get it, get it (Get it)
Until you're cheddar headed
And watch the way I navigate, ha-ha-ha-ha-ha
(Ha! Ha-ha! Ha-ha! Ha-ha! Ha!)
(Ha-ha-ha! Haa!)
(Ha-ha-ha-ha-ha! Haa!)
(Ha-ha-ha-ha-ha-ha-ha-ha! Haa!)
(Ha-ha-ha-ha-ha-ha-ha-ha!)


Sha-ba, sha-ba, sha-ba-da-ba, feel good
Sha-ba, sha-ba, sha-ba-da-ba, feel good
Sha-ba, sha-ba, sha-ba-da-ba, feel good
Sha-ba, sha-ba, sha-ba-da-ba, feel good




Windmill, windmill for the land
Turn forever, hand in hand
Take it all in on your stride
It is ticking, falling down
Love forever, love is free
Let's turn forever, you and me
Windmill, windmill for the land
Is everybody in?


Don't stop, get it, get it, peep how your captain's in it
(Sha-ba, sha-ba, sha-ba-da-ba, feel good)
Steady, watch me navigate, ha-ha-ha-ha-ha!
(Sha-ba, sha-ba, sha-ba-da-ba, feel good)
Don't stop, get it, get it, peep how your captain's in it
(Sha-ba, sha-ba, sha-ba-da-ba, feel good)
Steady, watch me navigate, ha-ha-ha-ha-ha!
(Sha-ba, sha-ba, sha-ba-da-ba, feel good)
Sha-ba, sha-ba, sha-ba-da-ba, feel good (Haa-ha-ha!)
Sha-ba, sha-ba, sha-ba-da-ba, feel good (Haa-ha-ha!)
Sha-ba, sha-ba, sha-ba-da-ba, feel good (Haa-ha-ha-ha-ha!)
Sha-ba, sha-ba, sha-ba-da-ba, feel good (Haa-ha-ha-ha-ha-ha!)""",
    },
    "GZ_02": {
        "title":  "DARE",
        "artist": "Gorillaz",
        "lyrics": """It's coming up, it's coming up
It's coming up, it's coming up
It's coming up, it's coming up
It's dare (
Uh
)
It's dare (
Oh-oh-oh
)


You've got to press it on you
You've just been thinking
That's what you do, baby (Oh-oh-oh)
Hold it down, dare
Jump with them all and move it
Jump back and forth
And feel like you were there yourself (Oh-oh-oh)
Work it out


Never did no harm, never did no harm
It's dare
It's coming up, it's coming up
It's coming up, it's coming up
It's coming up
It's dare (
Uh
)
It's dare (Oh-oh-oh)


You've got to press it on you
You've just been thinking
That's what you do, baby (Oh-oh-oh)
Hold it down, dare
Jump with them all and move it
Jump back and forth
And feel like you were there yourself
 (Oh-oh-oh)
Work it out


Never did no harm, never did no harm
It's dare
It's coming up, it's coming up
It's coming up, it's coming up
It's coming up
It's dare
Never did no harm, never did no harm
It's dare
It's coming up, it's coming up
It's coming up, it's coming up
It's coming up
It's dare (
Uh
)


You've got to press it on you
You've just been thinking
That's what you do, baby (Oh-oh-oh)
Hold it down, dare
Jump with them all and move it
Jump back and forth
And feel like you were there yourself
 (Oh-oh-oh)
Work it out
You've got to press it on you
You've just been thinking
That's what you do, baby (Oh-oh-oh)
Hold it down, dare
Jump with them all and move it
Jump back and forth
And feel like you were there yourself (Oh-oh-oh)
Work it out""",
    },
    "GZ_03": {
        "title":  "Clint Eastwood",
        "artist": "Gorillaz",
        "lyrics": """Hoo-hoo-hoo-hoo-hoo


I ain't happy, I'm feeling glad
I got sunshine in a bag
I'm useless, but not for long
The future is coming on
I ain't happy, I'm feeling glad
I got sunshine in a bag
I'm useless, but not for long
The future is coming on
It's coming on, it's coming on (Poof, right)
It's coming on, it's coming on (Yeah, haha)


Finally, someone let me out of my cage
Now time for me is nothing 'cause I'm countin' no age
Nah, I couldn't be there, now you shouldn't be scared
I'm good at repairs (It's all simple) and I'm under each snare
Intangible (Ah, y'all), bet you didn't think, so I command you to
Panoramic view (View?), look, I'll make it all manageable
Pick and choose, sit and lose, all you different crews
Chicks and dudes, who you think is really kickin' tunes?
Picture you getting down in a picture tube
Like you lit the fuse, you think it's fictional?
Mystical? Maybe, spiritual hero
Who appears in you to clear your view (Yeah) when you're too crazy?
Lifeless, to know the definition for what life is
Priceless to you because I put you on the hype shit
You like it? Gun smokin', righteous with one toke
Get psychic among those, possess you with one dose


I ain't happy, I'm feeling glad
I got sunshine in a bag
I'm useless, but not for long
The future is coming on
I ain't happy, I'm feeling glad
I got sunshine in a bag
I'm useless, but not for long
The future is coming on 
(That's right)
It's coming on, it's coming on
It's coming on, it's coming on


The essence, the basics, without it, you naked
Allow me to make this childlike in nature
Rhythm, you have it or you don't, that's a fallacy
I'm in them, every sproutin' tree, every child of peace
Every cloud and sea, you see with your eyes
I see destruction and demise, corruption in disguise 
(That's right)
From this fuckin' enterprise, now I'm sucked into your lies
Through Russel, not his muscles
But percussion he provides for me as a guide, y'all can see me now
'Cause you don't see with your eye, you perceive with your mind
That's the inner (Fuck 'em) so I'ma stick around with Russ and be a mentor
Bust a few rhymes so motherfuckers remember
Where the thought is, I brought all this
So you can survive when law is lawless 
(Right here)
Feelings, sensations that you thought was dead
No squealing and remember that it's all in your head


I ain't happy, I'm feeling glad
I got sunshine in a bag
I'm useless, but not for long
The future is coming on
I ain't happy, I'm feeling glad
I got sunshine in a bag
I'm useless, but not for long
My future is coming on
It's coming on, it's coming on
It's coming on, it's coming on


My future is coming on
It's coming on, it's coming on
It's coming on, it's coming on
My future is coming on
It's coming on, it's coming on
It's coming on, it's coming on
My future is coming on
It's coming on, it's coming on
My future is coming on
It's coming on, it's coming on
My future is coming on
It's coming on, it's coming on
My future""",
    },
    "GZ_04": {
        "title":  "On Melancholy Hill",
        "artist": "Gorillaz",
        "lyrics": """(Ah-ah)
(Ah-ah)


Up on Melancholy Hill, there's a plastic tree
Are you here with me?
Just looking out on the day of another dream
Where you can't get what you want, but you can get me
So let's set out to sea, love
'Cause you are my medicine when you're close to me
When you're close to me


(Ah-ah)


So call in the submarines, 'round the world we'll go
Does anybody know, love?
If we're looking out on the day of another dream?
(Ah-ah)
If you can't get what you want, then you come with me
Up on Melancholy Hill, sits the manatee (Ah-ah-ah-ah), love
Just looking out for the day when you're close to me
When you're close to me


Ooh, ooh-ooh-ooh (Ah-ah)
Ooh-ooh-ooh
Ooh-ooh-ooh, when you're close to me
Ooh, ooh-ooh-ooh (Ah-ah)
Ooh-ooh-ooh
Ooh-ooh-ooh
Ooh, ooh-ooh-ooh (Ah-ah)
Ooh-ooh-ooh""",
    },
    "GZ_05": {
        "title":  "Rhinestone Eyes",
        "artist": "Gorillaz",
        "lyrics": """I'm a scary gargoyle on a tower
That you made with plastic power
Your rhinestone eyes are like factories far away
When the paralytic dreams that we all seem to keep
Drive on engines 'til they weep
With future pixels in factories far away
So call the mainland from the beach
All parties now washed up in bleach
The waves are risin' for this time of year
And nobody knows what to do with the heat
Under sunshine pylons, we'll meet
While rain is fallin' like rhinestones from the sky


(Uh, mm)
Uh, mmm


I can't see you, now my heart is frozen
All the verses and the corrosion
Have been after native in my soul
I prayed on the immovable
Yet clinging to the atoms of rock
Seasons see adjustment signs of change
I can't see now, she said, "Taxi"
Now that light is all I can take
This dawn brings strange loyalties and skies
I'm a scary gargoyle on a tower
That you made with plastic power
Your rhinestone eyes are like factories far away


(Here we go again)
That's electric-tric-tric-tric-tric-tric-tric-tric-tric-tric-tric (Uh)
That's electric-tric-tric-tric-tric-tric-tric-tric-tric-tric-tric


Helicopters fly over the beach (Oh, oh)
Same time every day, same routine (Oh, oh)
A clear target in the summer when skies are blue
It's part of the noise when winter comes (Oh, oh)
It reverberates in my lungs
Nature's corrupted in factories far away


(Here we go again)
That's electric-tric-tric-tric-tric-tric-tric-tric-tric-tric-tric
Your love's like rhinestones falling from the sky (Uh)
That's electric-tric-tric-tric-tric-tric-tric-tric-tric-tric-tric
With future pixels in factories far away
(Here we go again)
That's electric-tric-tric-tric-tric-tric-tric-tric-tric-tric-tric
Your love's like rhinestones falling from the sky (Uh)
That's electric-tric-tric-tric-tric-tric-tric-tric-tric-tric-tric
With future pixels in factories far away (Here we go again)""",
    },
    "GZ_06": {
        "title":  "Stylo",
        "artist": "Gorillaz",
        "lyrics": """Love, electricity, shockwave central
Power on the motherboard, yes
Push up, overload, legendary heavy glow
Sunshine, thunder roll, keep this on
Yes, the lantern burns firm and easy
And broadcast, so raw and neatly
Thunder roll, sunshine, work it out


Overload, overload, overload
Comin' on to the
Overload, overload, overload
Comin' on to the
Overload, overload, overload
Comin' on to the
Overload, overload, overload
Comin' on to the


Oh, Stylo (Juice)
Go for blossom in your soul
When you know your heart is light
Electric is the love
When the mako flies (It's the giant fish)
Up from the bottom in your eyes (As it leaps from the stream)
Then I'll know the twilight skies (Blood curdles, it's a death throw)
Are not so broken hearted (Hot from the end of the line)


If it's love, it's electric
It'll be flowing on the streets
Night after night
Just to get through the week
Sometimes it's hard
Right now


Sing yourself (Juice)
Out of depression, rise above
All recession, if I know your heart
Electric is the love


There's only one way (
Overload, overload, overload
Comin' on to the
)
Let it play a little while longer (
Overload, overload, overload
Comin' on to the
)
It's got a way of passin' through man and woman (
Overload, overload, overload
Comin' on to the
)
In another world, in another world, in a universe, oh! (
Overload, overload, overload
Comin' on to the
)
Right now, here's what we got to do


If it's love, it's electric (
Overload, overload, overload
Comin' on to the
)
It'll be flowing on the streets (
Overload, overload, overload
Comin' on to the
)
Night after night (
Overload, overload, overload
Comin' on to the
)
Just to get through the week
Sometimes it's hard (
Overload, overload, overload
Comin' on to the
)
That's what I'm talkin' 'bout


Love, electricity, shockwave central
Power on the motherboard, yes
Push up, overload, legendary heavy glow
Sunshine, thunder roll, keep this on
Yes, the lantern burns firm and easy
And broadcast, so raw and neatly
Thunder roll, sunshine, work it out


Right now!""",
    },
    "GZ_07": {
        "title":  "Empire Ants",
        "artist": "Gorillaz",
        "lyrics": """Oh, joys arise, the sun has come again to hold you
Sailin' out the doldrums of the week
The polyphonic prayer is here, it's all around you
It's all around you, out here


And if the whole world is crashing down (On you)
Fall through space out of mind with me


Where the emptiness we leave behind on warm air rising
Blows all the shadows far away (Away-away-away)
The fallin' of the whole empire is here to hold you
Rolling out and haunted 'til it sleeps




Little memories, marchin' on
Your little feet, workin' the machine
Say will it spin, will it soar?
My little dream, workin' the machine
Soon, like a wave
Empires will fall
And closin' in on you
They're goin' on




Little memories (Memories-memories-memories)
Your little feet, workin' the machine
Say will it spin, will it soar?
My little dream, workin' the machine
Soon, like a wave
Empires will fall
And closin' in on you
They're goin' on""",
    },
    "GZ_08": {
        "title":  "Momentz",
        "artist": "Gorillaz",
        "lyrics": """Clocks on the wall
Talk to watches on the wrist
It's the moments we relive
It's the moments like this
When it's time to get ill
We be so ahead of time
It's the moments we achieve
Best believe it's the moments


Main event, yellow, red
Black, white, dirty
Moments
Main event, yellow, red
Black, white dirty
Moments
Shiver down my backbone


De La is also back again (Uh-huh)
With a crew that's bound to pack 'em in (Uh-huh)
Got a girl who's up for the matin'
I sense the need in her grammar
Her nose has never been skatin' (Uh-huh)
But she's sippin' star constellation (Shit)
For real, her squirt game was so like 2Pac out of court run towards camera (Uh-huh)
My response to that was just, "Check please"
Fuck that, my man, you can't let these (Moments)
Pass you by like "tick tock"
So I'm smackin' the bottom like flip flops
Made her alarm ring (She screams)
And now we done, we passed the test
So now lay down to rest
And wait for the mornin' hangover that comes


Clocks on the wall
Talk to watches on the wrist
It's the moments we relive
It's the moments like this
When it's time to get ill
We be so ahead of time
It's the moments we achieve
Best believe it's the moments


Main event, yellow, red
Black, white, dirty
Moments
Main event, yellow, red
Black, white dirty
Moments
Shiver down my backbone


Plastic on the ceiling
Plastic on the ceiling
Plastic on the ceiling
Plastic on the ceiling
Plastic on the ceiling
Plastic on the ceiling
Plastic on the ceiling
Plastic on the ceiling
So now lay down to rest
And wait for the mornin' hangover that comes


Clocks on the wall
Talk to watches on the wrist
It's the moments we relive
It's the moments like this
When it's time to get ill
We be so ahead of time
It's the moments we achieve
Best believe it's the moments
Moments
Moments
Moments
Moments


I'm talkin' about the Kool Klown Klan
Kool Klown Klan
I'm talkin' about the Kool Klown Klan
I need to step out for a fresh of breath air after that""",
    },
    "GZ_09": {
        "title":  "Andromeda",
        "artist": "Gorillaz",
        "lyrics": """When the passing looks to die for
Take it in your heart now, love her
When the case is out
And tired and sodden
Take it in your heart
Take it in your heart


Back to when it was cool
'Cause there's no substitute
Who even knows the truth?
The truth, the truth


Take it in your heart now, love her
Take it in your heart (Heart, heart, heart)
Take it in your heart
Take it in your heart (Heart, heart, heart)
Where it all goes down


Outside, cold and ghosting out with jet lag (Ooh)
I took it to the right man (Yeah, yeah)
Took it all back (All back)
When the courts were closing
It was Bobby gracing
I know that
I put it to the right
 man
He put it back


Talk to the crowds
Stacks of lights come streaming back
Make it for the best times
Growing pains, good times
Good times, good times
Good times, good times
Good times, good times


Take it in your heart now, love her (Good times, good times)
Take it in your heart (Heart, heart, heart)
Take it in your heart
Take it in your heart
Where it all goes down


Andromeda
Andromeda, Andromeda
Take it in your heart now, love her
(Andromeda, Andromeda, Andromeda, Andromeda)
Take it in your heart
Take it in your heart
Where it all goes down""",
    },
    "GZ_10": {
        "title":  "Tranz",
        "artist": "Gorillaz",
        "lyrics": """Oscillate yourself tonight
When you're in your bed
Assimilate the dopamine
Passing through your head


When you get back on a Saturday night
And the room is caving in
Do you look like me? Do you feel like me?
Do you turn into your effigy?


Do you dance like this forever?


See yourself in Cupid's lake
Chipped in your head
Do you indicate to satellites
Passing by the edge?


When you get back on a Saturday night
And your head is caving in
Do you look like me? Do you feel like me?
Do you turn into your effigy?


Do you dance like this forever?
Do you dance like this forever?


Do you look like me?
Do you burn like me?
Do you look like me?
Do you burn like me?
Do you look like me?
Do you burn like me?
Do you turn into your effigy?


Do you dance like this forever?
Do you dance like this forever?


(Do you dance?)
(Do you dance?)
(Do you dance?)
(Do you dance?)""",
    },
    "GZ_11": {
        "title":  "Hollywood",
        "artist": "Gorillaz",
        "lyrics": """Where the beautiful people at?
I said where the beautiful people at?
Beautiful people, clap your hands (yeah)
Freaky people, clap your hands
Geeky people, clap your hands
Everybody, clap your hands


Hollywood is alright
Hollywood is vagrant
Jealousy is in gunfire
It makes you kill the vibe
(She's a wonderful thing)
Jealousy and dark times
Sinking on the web
There’s more to love than that
Jealousy is vibe down
Jealousy is vibe down


(Hahaha, yeah)
I'ma go walk
All the way to the hills
But you never know what's real
So you have to be prepared
You have to be ready
You have to be ready
'Cause she can be a bitch
And it's a wonderful thing
Hollywood (Hollywood)
She's so seductive
She's got me looking for that dream
I bow down
She knows how to do it
Exactly the way I like it


Hollywood is alright
Hollywood is vagrant
Jealousy is in gunfire
It makes you kill the vibe
(She's a wonderful thing)
Jealousy and dark times
Sinking on the web
There’s more to love than that
Jealousy is vibe down
Jealousy is vibe down


Man I came through with that big fat chain on my neck
Little did they know, no sweat
So I dimmed out, rimmed out and cracked the glass
Twenty-five pounds, can you match that bag?
'Cause if you not, raise up
I got a deal to make
And a couple bad bitches
I've been achin' to break
Wakin' and bake
I put the cake on the plate
Jealousy and me? Oh, we're making a date
I'ma vibe with this, Hollywood, nigga I'ma survive this shit
I do that, did that, blow your fuckin' wig back
Forreal-a, gorilla, who loves goin' bareback
They wanna eye me down, tie me down, knock me off
But I'm a lion in the dogg pound
Now, how that sound?


Hollywood is alright
Hollywood is vagrant
Jealousy is in gunfire
It makes you kill the vibe
(She's a wonderful thing)
Jealousy and dark times
Sinking on the web
There’s more to love than that
Jealousy is vibe down
Jealousy is vibe down


You're just what I need
(And it's a wonderful thing)
In this city of dreams
(And it's a wonderful thing)
You know how to ride me
(And it's a wonderful thing)
You know how to excite me
(And it's a wonderful thing)


She's a wonderful thing
She's a wonderful thing""",
    },
    "GZ_12": {
        "title":  "New Gold",
        "artist": "Gorillaz",
        "lyrics": """But in the magic cove, there's a pretty one
I asked her where it goes 'cause I really want
I wonder if she knows that we're underwater
That's the way it goes in this city wonder


Moved to the spot, I'm one of a few
A whole lot of everything, but nothin' to do
Tilted in a Tesla, partner, ex-wrestler
He dates Francesca, they on the Xannies
Liposuction schedulеd for Granny
She want to save some, add to hеr fanny
Girls' trip, Miami at the end of the year
Polluted-filled skies, tryin' to think clear
I heard the bad news while I was sheddin' a beer
Watch out from the coast, Paul Revere
We all play a part in the devil's cheer
Run to the hills 'cause the end is near


But in the magic cove, there's a pretty one
I asked her where it goes 'cause I really want
I wonder if she knows that we're underwater
That's the way it goes in this city wonder


Yo, a desolate city where it hurts to smile
Ran into the Reverend, says it's been a while
I'm reining in a rando', she's a social scandal
Gave ourselves a handout when it's too much to bear
ABC boys raided the mayor
Like Shaun, he's a Ryder, took on the dare
Now he's singin' like a birdy, pullin' on his hair
Trendin' on Twitter's what some of us live for
Friendship's here, but now fuckin' revolving door
All of this a joke? Pauly Shore
Bullshit keeps comin', maybe I'm a matador
What are we livin' for?


Are we all losin' our minds?
Because life got in the way (Hey, hey, hey)
They will be here just in time
Your replacement is here to stay (Ah-ah-ah-ah)


New gold, fool's gold
Everythin' will disappear (
New gold
)
Someone's out here
Who traveled far too many years (
New gold
)
To nowhere, nowhere
Nothin' here is ever real (
New gold
)
New gold, fool's gold (
New gold
)
Everythin' will disappear, 
disappear
Disappear, disappear, disappear
Disappear, disappear, disappear
Disappear, disappear, disappear
Disappear, disappear, disappear


But in the magic cove, there's a pretty one
I asked her where it goes 'cause I really want
I wonder if she knows that we're underwater
That's the way it goes in this city wonder
But in the magic cove, there's a pretty one (New gold)
I asked her where it goes 'cause I really want
I wonder if she knows that we're underwater
That's the way it goes in this city wonder (Ah-ah-ah-ah)
(New gold, fool's gold)
But in the magic cove, there's a pretty one
(Everythin' will disappear)
I asked her where it goes 'cause I really want (New gold)
(Someone's out here)
I wonder if she knows that we're underwater
(Who traveled far too many years)
That's the way it goes in this city wonder (New gold)
(To nowhere, nowhere)
But in the magic cove, there's a pretty one
(Nothin' here is ever real)
I asked her where it goes 'cause I really want (New gold)
(New gold, fool's gold)
I wonder if she knows that we're underwater (New gold)
(Everythin' will disappear)
That's the way it goes in this city wonder""",
    },
}
