# Auto-generated by 03_build_schema.py — do not edit manually.
# Artist: Harry Styles  |  Code: HS
# Songs included: 12  |  Missing: 0

HS_SCHEMA = {
    "HS_01": {
        "title":  "As It Was",
        "artist": "Harry Styles",
        "lyrics": """Come on, Harry, we wanna say goodnight to you


Holdin' me back
Gravity's holdin' me back
I want you to hold out the palm of your hand
Why don't we leave it at that?
Nothin' to say
When everything gets in the way
Seems you cannot be replaced
And I'm the one who will stay, oh-oh-oh


In this world, it's just us
You know it's not the same as it was
In this world, it's just us
You know it's not the same as it was
As it was, as it was
You know it's not the same


Answer the phone
"Harry, you're no good alone
Why are you sitting at home on the floor?
What kind of pills are you on?"
Ringin' the bell
And nobody's coming to help
Your daddy lives by himself
He just wants to know that you're well, oh-oh-oh


In this world, it's just us
You know it's not the same as it was
In this world, it's just us
You know it's not the same as it was
As it was, as it was
You know it's not the same


Go home, get ahead, light-speed internet
I don't wanna talk about the way that it was
Leave America, two kids follow her
I don't wanna talk about who's doin' it first


(Hey)
As it was
You know it's not the same as it was
As it was, as it was""",
    },
    "HS_02": {
        "title":  "Watermelon Sugar",
        "artist": "Harry Styles",
        "lyrics": """Tastes like strawberries on a summer evenin'
And it sounds just like a song
I want more berries and that summer feelin'
It's so wonderful and warm


Breathe me in, breathe me out
I don't know if I could ever go without
I'm just thinking out loud
I don't know if I could ever go without


Watermelon sugar high
Watermelon sugar high
Watermelon sugar high
Watermelon sugar high
Watermelon sugar


Strawberries on a summer evenin'
Baby, you're the end of June
I want your belly and that summer feelin'
Getting washed away in you


Breathe me in, breathe me out
I don't know if I could ever go without


Watermelon sugar high
Watermelon sugar high
Watermelon sugar high
Watermelon sugar high
Watermelon sugar high
Watermelon sugar high
Watermelon sugar high
Watermelon sugar high


I just wanna taste it, I just wanna taste it
Watermelon sugar high


Tastes like strawberries on a summer evenin'
And it sounds just like a song
I want your belly and that summer feelin'
I don't know if I could ever go without


Watermelon sugar high
Watermelon sugar high
Watermelon sugar high (Sugar)
Watermelon sugar high (Sugar)
Watermelon sugar high
Watermelon sugar high
Watermelon sugar high
Watermelon sugar high


I just wanna taste it, I just wanna taste it (Eh-eh-eh)
Watermelon sugar high
I just wanna taste it, I just wanna taste it (Ooh, yeah)
Watermelon sugar high
Watermelon sugar""",
    },
    "HS_03": {
        "title":  "Adore You",
        "artist": "Harry Styles",
        "lyrics": """Walk in your rainbow paradise (Paradise)
Strawberry lipstick state of mind (State of mind)
I get so lost inside your eyes
Would you believe it?


You don't have to say you love me
You don't have to say nothing
You don't have to say you're mine


Honey (Ah-ah-ah)
I'd walk through fire for you
Just let me adore you
Oh, honey (Ah-ah-ah)
I'd walk through fire for you
Just let me adore you
Like it's the only thing I'll ever do
Like it's the only thing I'll ever do


You're wonder under summer sky (Summer sky)
Brown skin and lemon over ice
Would you believe it?


You don't have to say you love me
I just wanna tell you somethin'
Lately, you've been on my mind


Honey (Ah-ah-ah)
I'd walk through fire for you
Just let me adore you
Oh, honey (Ah-ah-ah)
I'd walk through fire for you
Just let me adore you
Like it's the only thing I'll ever do
Like it's the only thing I'll ever do


It's the only thing I'll ever do
It's the only thing I'll ever do
It's the only thing I'll ever do
It's the only thing I'll ever do
It's the only thing I'll ever do
It's the only thing I'll ever do
It's the only thing I'll ever do
It's the only thing I'll ever do


I'd walk through fire for you
Just let me adore you
Oh, honey (Ah-ah-ah)
I'd walk through fire for you
Just let me adore you
Like it's the only thing I'll ever do (Ah-ah-ah)
(It's the only thing I'll ever do, it's the only thing I'll ever do)
I'd walk through fire for you (It's the only thing I'll ever do)
Just let me adore you
Oh, honey (Ah-ah-ah), oh, honey
(It's the only thing I'll ever do, it's the only thing I'll ever do)
I'd walk through fire for you (It's the only thing I'll ever do)
Just let me adore you (It's the only thing I'll ever do)


Ooh, ooh
Oh, honey
Ooh, ooh
Just let me adore you
Like it's the only thing I'll ever do""",
    },
    "HS_04": {
        "title":  "Golden",
        "artist": "Harry Styles",
        "lyrics": """Ha
(Da-da-da-da, da, da-da-da-da)
(Da-da-da-da, da, da-da-da-da)
(Da-da-da-da, da, da-da-da-da)
(Da-da-da-da, da, da-da-da-da)


Golden, golden, golden as I open my eyes
Hold it, focus, hoping, take me back to the light
I know you were way too bright for me
I'm hopeless, broken, so you wait for me in the sky
Browns my skin just right
You're so golden


(Da-da-da-da, da, da-da-da-da)
(Da-da-da-da, da, da-da-da-da)
You're so golden
(Da-da-da-da, da, da-da-da-da)
I'm out of my head and I know that you're scared
Because hearts get broken
(Da, da-da-da-da)


I don't wanna be alone
I don't wanna be alone when it ends
Don't wanna let you know
I don't wanna be alone
But I, I can feel it take a hold (I can feel it take a hold)
I can feel you take control (I can feel you take control)
Of who I am and all I've ever known
Lovin' you's the antidote
Golden


(Da-da-da-da, da, da-da-da-da)
(Da-da-da-da, da, da-da-da-da)
You're so golden
(Da-da-da-da, da, da-da-da-da)
I don't wanna be alone
(Da-da-da-da, da, da-da-da-da)
You're so golden
(Da-da-da-da, da, da-da-da-da)
(Da-da-da-da, da, da-da-da-da)
You're so golden
(Da-da-da-da, da, da-da-da-da)
I'm out of my head and I know that you're scared
Because hearts get broken
(Da-da-da-da, da, da-da-da-da)


(Golden, golden, golden, golden)
(Golden, golden, golden, golden)
(Golden, golden, golden, golden)
(Golden, golden, golden, golden)
(Golden, golden, golden, golden)
(Golden, golden, golden, golden)
(Golden, golden, golden, golden)
And I know that you're scared because I'm so open


(Da-da-da-da, da, da-da-da-da)
(Da-da-da-da, da, da-da-da-da)
You're so golden
(Da-da-da-da, da, da-da-da-da)
I don't wanna be alone
(Da-da-da-da, da, da-da-da-da)
You're so golden
(Da-da-da-da, da, da-da-da-da)
You're so golden
(Da-da-da-da, da, da-da-da-da)
You're so golden
(Da-da-da-da, da, da-da-da-da)
I'm out of my head and I know that you're scared
Because hearts get broken
(Da-da-da-da, da, da-da-da-da)


(Da-da-da-da, da, da-da-da-da)
(Da-da-da-da, da, da-da-da-da)
(Da-da-da-da, da, da-da-da-da)
(Da-da-da-da)""",
    },
    "HS_05": {
        "title":  "Lights Up",
        "artist": "Harry Styles",
        "lyrics": """What do you mean?
I'm sorry by the way
Never coming back down
Can't you see?
I could, but wouldn't stay
Wouldn't put it like that
What do you mean?
I'm sorry by the way
Never coming around
It'd be so sweet if things just stayed the same
La-da-da-da-da


All the lights couldn't put out the dark
Runnin' through my heart
Lights up and they know who you are
Know who you are
Do you know who you are? (Oh)


Shine, step into the light
Shine, so bright sometimes
Shine, I'm not ever going back
Shine, step into the light
Shine, so bright sometimes
Shine, I'm not ever going back
Shine, step into the light
Shine, so bright sometimes
Shine, I'm not ever (Ooh)


What do you mean?
I'm sorry by the way
Never going back now
It'd be so sweet if things just stayed the same
La-da-da-da-da
La-da-da-da-da
La-da-da-da-da (Oh)
La-da-da-da-da (Oh)
La-da-da-da-da (Oh)


All the lights couldn't put out the dark
Runnin' through my heart
Lights up and they know who you are
Know who you are
Do you know who you are?""",
    },
    "HS_06": {
        "title":  "Sign of the Times",
        "artist": "Harry Styles",
        "lyrics": """Just stop your crying, it's a sign of the times
Welcome to the final show
I hope you're wearing your best clothes
You can't bribe the door on your way to the sky
You look pretty good down here
But you ain't really good


If we never learn we've been here before
Why are we always stuck and running from
The bullets, the bullet?
We never learn, we've been here before
Why are we always stuck and running from
Your bullets, a bullet?


Just stop your crying, it's a sign of the times
We gotta get away from here
We gotta get away from here
Just stop your crying, it'll be alright
They told me that the end is near
We gotta get away from here


Just stop your crying, have the time of your life
Breaking through the atmosphere
Things look pretty good from here
Remember everything will be alright
We can meet again somewhere
Somewhere far away from here


We never learn, we've been here before
Why are we always stuck and running from
The bullets, the bullets?
We never learn, we've been here before
Why are we always stuck and running from
The bullets, the bullets?


Just stop your crying, it's a sign of the times
We gotta get away from here
We gotta get away from here
Stop your crying, baby, it'll be alright
They told me that the end is near
We gotta get away from here


We never learn, we've been here before
Why are we always stuck and running from
Your bullets, the bullets?
We never learn, we've been here before
Why are we always stuck and running from
Your bullets, your bullets?


We don't talk enough
We should open up
Before it's all too much
Will we ever learn?
We've been here before
It's just what we know


Stop your crying, baby, it's a sign of the times
We gotta get away
We got to get away, we got to get away
We got to get away, we got to get away
We got to, we got to run
We got to, we got to run
We got to, we got to run away""",
    },
    "HS_07": {
        "title":  "Falling",
        "artist": "Harry Styles",
        "lyrics": """I'm in my bed
And you're not here
And there's no one to blame but the drink in my wandering hands
Forget what I said
It's not what I meant
And I can't take it back, I can't unpack the baggage you left


What am I now? What am I now?
What if I'm someone I don't want around?
I'm falling again, I'm falling again, I'm fallin'
What if I'm down? What if I'm out?
What if I'm someone you won't talk about?
I'm falling again, I'm falling again, I'm fallin'


You said you cared, and you missed me too
And I'm well aware I write too many songs about you
And the coffee's out at the Beachwood Cafe
And it kills me 'cause I know we've run out of things we can say


What am I now? What am I now?
What if I'm someone I don't want around?
I'm falling again, I'm falling again, I'm fallin'
What if I'm down? What if I'm out?
What if I'm someone you won't talk about?
I'm falling again, I'm falling again, I'm fallin'


And I get the feeling that you'll never need me again (Oh)


What am I now? What am I now?
What if you're someone I just want around?
I'm falling again, I'm falling again, I'm fallin'
What if I'm down? What if I'm out?
What if I'm someone you won't talk about?
I'm falling again, I'm falling again, I'm fallin'""",
    },
    "HS_08": {
        "title":  "Treat People With Kindness",
        "artist": "Harry Styles",
        "lyrics": """Maybe we can
Find a place to feel good
And we can treat people with kindness
Find a place to feel good


I've got a good feeling
I'm just takin' it all in
Floating up and dreamin'
Droppin' into the deep end


And if we're here long enough
They'll sing a song for us (
Ooh
)
And we'll belong


Maybe we can
Find a place to feel good
And we can treat people with kindness
Find a place to feel good


Given second chances
I don't need all the answers
Feeling good in my skin
I just keep on dancin'


And if we're here long enough
We'll see it's all for us (Ooh)
And we'll belong


Maybe we can
Find a place to feel good
And we can treat people with kindness
Find a place to feel good


And it's just another day (And it's just another day)
And if our friends all pass away (Oh-oh, oh-oh)
It's okay (It's okay, it's okay)
It's okay (It's okay, it's okay, yeah)
Hey
Here we go now


Maybe we can
Find a place to feel good
And we can treat people with kindness
Find a place to feel good


All we ever want is automatic all the time
All we ever want is auto all of the time
All we ever want is automatic all the time
All we ever want is auto all of the time
Maybe we can (All together now, one more time)
Find a place to feel good (Oh yeah)
And we can treat people with kindness (Just a little bit of kindness)
Find a place to feel good (Ow)""",
    },
    "HS_09": {
        "title":  "Late Night Talking",
        "artist": "Harry Styles",
        "lyrics": """Things haven't been quite the same
There's a haze on the horizon, babe
It's only been a couple of days and I miss you, mmm, yeah
When nothing really goes to plan
You stub your toe or break your camera
I'll do everything I can to help you through


If you're feeling down, I just wanna make you happier, baby
Wish I was around, I just wanna make you happier, baby


We've been doin' all this late-night talkin'
'Bout anything you want until the morning
Now you're in my life
I can't get you off my mind


I've never been a fan of change
But I'd follow you to any place
If it's Hollywood or Bishopsgate, I'm coming, too


If you're feeling down, I just wanna make you happier, baby
Wish I was around, I just wanna make you happiеr, baby


We've been doin' all this late-night talkin'
'Bout anything you want until thе morning
Now you're in my life
I can't get you off my mind


Can't get you off my mind
Can't get you off my mind (Can't get you off my mind)
I won't even try (I won't even try)
To get you off my mind (Get you off my mind)


We've been doin' all this late-night talkin'
'Bout anything you want until the morning
Now you're in my life
I can't get you off my mind


Can't get you off my mind (All this late-night talking)
Can't get you off my mind (All this late-night talking)
I won't even try (All this late-night talking)
Can't get you off my— (All this late-night talking)""",
    },
    "HS_10": {
        "title":  "Music for a Sushi Restaurant",
        "artist": "Harry Styles",
        "lyrics": """Ba, ba-ba
Ba-ba, ba-ba


Green eyes, fried rice, I could cook an egg on you
Late night, game time, coffee on the stove, yeah (Oh)
You're sweet ice cream, but you could use a Flake or two
Blue bubblegum twisted 'round your tongue


I don't want you to get lost
I don't want you to go broke
I want you


It's 'cause I love you, babe
In every kind of way
Just a little taste
You know I love you, babe


Ba, ba-ba
Ba-ba, ba-ba
(You know I love you, babe)
Ba, ba-ba
Ba-ba, ba-ba


"Excuse me, a green tea?"
Music for a sushi restaurant
From ice on rice
Scuba-duba-dubub-boo (Oh)
Music for a sushi restaurant
Music for a sushi restaurant
Music for whatever you want
Scuba-duba-dubub-boo (Oh)


I'm not going to get lost
I'm not going to go broke
Staying cool
(You know I love you, babe)


Ba, ba-ba
Ba-ba, ba-ba
(You know I love you, babe)
Ba, ba-ba
Ba-ba, ba-ba


(Ba, ba-ba, ba-ba, ba-ba)
If the stars were edible
And our hearts were never full
(Ba, ba-ba, ba-ba, ba-ba)
Could we live with just a taste?
Just a taste


Ba, ba-ba (It's 'cause I love you, babe)
(In every kind of way)
Ba-ba (Just a little taste)
(You know I love you, babe)


Ba, ba-ba
Ba-ba, ba-ba
(You know I love you, babe)
Ba, ba-ba
Ba-ba, ba-ba""",
    },
    "HS_11": {
        "title":  "Matilda",
        "artist": "Harry Styles",
        "lyrics": """You were riding your bike to the sound of "It's No Big Deal"
And you're trying to lift off the ground on those old two wheels
Nothing 'bout the way that you were treated ever seemed especially alarming till now
So you tie up your hair and you smile like it's no big deal


You can let it go
You can throw a party full of everyone you know
And not invite your family 'cause they never showed you love
You don't have to be sorry for leavin' and growin' up, mmm


Matilda, you talk of the pain like it's all alright
But I know that you feel like a piece of you's dead insidе
You showed me a power that is strong еnough to bring sun to the darkest days
It's none of my business, but it's just been on my mind


You can let it go
You can throw a party full of everyone you know
And not invite your family 'cause they never showed you love
You don't have to be sorry for leavin' and growin' up
You can see the world, following the seasons
Anywhere you go, you don't need a reason
'Cause they never showed you love
You don't have to be sorry for doin' it on your own


You're just in time, make your tea and your toast
You framed all your posters and dyed your clothes, ooh
You don't have to go
You don't have to go home
Oh, there's a long way to go
I don't believe that time will change your mind
In other words, I know they won't hurt you anymore
As long as you can let them go


You can let it go
You can throw a party full of everyone you know
You can start a family who will always show you love
You don't have to be sorry for doin' it on your own
You can let it go
You can throw a party full of everyone you know
You can start a family who will always show you love
You don't have to be sorry, no""",
    },
    "HS_12": {
        "title":  "Cinema",
        "artist": "Harry Styles",
        "lyrics": """You got, you got the cinema


It's you
And I'm not gettin' over it
Darling, is it cool
If I'm stubborn when it comes to this?
I guess we're in time
If you're getting yourself wet for me
I guess you're all mine
When you're sleeping in this bed with me


I just think you're cool
I dig your cinema
Do you think I'm cool, too?
Or am I too into you?


Tell me what you want and you got it, love
I want all of you, gimme all you got
That's cinema
That's cinema, uh-huh


It's you
Don't know why, but it feels so right to me
Something in the way you move
I like it when you dance for me (I just think it's—)
You all the time (Time, time)
In doses at night (Night, night)
No roof on the drive
Dust off the high
And go to sleep (Go to sleep, go to sleep)


I just think you're cool
I dig your cinema
Do you think I'm cool, too?
Or am I too into you?
I just think you're cool (Co-cool)
I dig your cinema (Cinema)
Do you think I'm cool, too?
Or am I too into you? (Cinema)
Cinema


You got, you got
I bring the pop, you pop
You got, you got
I bring the pop
You got, you got the cinema
I bring the pop to the cinema, you pop
You got, you got the cinema
You got, you got the cinema
I bring the pop to the cinema
You pop when we get intimate
You got, you got the cinema
You got, you got the cinema (Cinema)
I bring the pop to the cinema
You pop when we get intimate (Baby, you're cinema)
You got, you got the cinema
You got, you got the cinema
I bring the pop to the cinema
You pop when we get intimate (Baby, you're cinema)
You got, you got the cinema
You got, you got the cinema
I bring the pop to the cinema
You pop when we get intimate (Baby, you're cinema)
You got, you got the cinema
You got, you got the cinema (Cinema)
I bring the pop to the cinema
You pop when we get intimate""",
    },
}
