# Auto-generated by 03_build_schema.py — do not edit manually.
# Artist: Kendrick Lamar  |  Code: KL
# Songs included: 15  |  Missing: 0

KL_SCHEMA = {
    "KL_01": {
        "title":  "HUMBLE.",
        "artist": "Kendrick Lamar",
        "lyrics": """Nobody pray for me
It been that day for me
Way (Yeah, yeah)


Ayy, I remember syrup sandwiches and crime allowances
Finesse a nigga with some counterfeits, but now I'm countin’ this
Parmesan where my accountant lives, in fact, I'm downin' this
D’ussé with my boo bae, tastes like Kool-Aid for the analysts
Girl, I can buy your ass the world with my paystub
Ooh, that pussy good, won't you sit it on my taste bloods?
I get way too petty once you let me do the extras
Pull up on your block, then break it down, we playin' Tetris
A.m. to the p.m., p.m. to the a.m., funk
Piss out your per diem, you just gotta hate 'em, funk
If I quit your BM, I still ride Mercedes, funk
If I quit this season, I still be the greatest, funk
My left stroke just went viral
Right stroke put lil' baby in a spiral
Soprano C, we like to keep it on a high note
It's levels to it, you and I know


Bitch, be humble (Hold up, bitch)
Sit down (Hold up, lil'— hold up, lil' bitch)
Be humble (Hold up, bitch)
Sit down (Hold up, sit down, lil’— sit down, lil’ bitch)
Be humble (Hold up, hold up, hold up, hold up, lil' bitch)
Bitch, sit down (Hold up, lil’ bitch)
Be humble (Hold up, bitch)
Sit down (Hold up, hold up, hold up, hold up)
Be humble (Hold up, hold up, hold up, hold up, lil'—)
Sit down (Hold up, lil' bitch)
Be humble (Hold up, bitch)
Sit down (Hold up, sit down, lil'— sit down, lil’ bitch)
Be humble (Hold up, hold up, hold up, hold up, lil' bitch)
Bitch, sit down (Hold up, lil' bitch)
Be humble (Hold up, bitch)
Sit down (Hold up, hold up, hold up, hold up)


Who that nigga thinkin' that he frontin' on Man-Man? (Man-Man)
Get the fuck off my stage, I'm the Sandman (Sandman)
Get the fuck off my dick, that ain't right
I make a play fucking up your whole life
I'm so fuckin' sick and tired of the Photoshop
Show me somethin' natural like afro on Richard Pryor
Show me somethin' natural like ass with some stretch marks
Still'll take you down right on your mama couch in Polo socks
Ayy, this shit way too crazy, ayy, you do not amaze me, ayy
I blew cool from AC, ayy, Obama just paged me, ayy
I don't fabricate it, ayy, most of y'all be fakin', ayy
I stay modest 'bout it, ayy, she elaborate it, ayy
This that Grey Poupon, that Evian, that TED Talk, ayy
Watch my soul speak, you let the meds talk, ayy
If I kill a nigga, it won't be the alcohol, ayy
I'm the realest nigga after all


Bitch, be humble (Hold up, bitch)
Sit down (Hold up, lil'— hold up, lil' bitch)
Be humble (Hold up, bitch)
Sit down (Hold up, sit down, lil'— sit down, lil' bitch)
Be humble (Hold up, hold up, hold up, hold up, lil' bitch)
Bitch, sit down (Hold up, lil' bitch)
Be humble (Hold up, bitch)
Sit down (Hold up, hold up, hold up, hold up)
Be humble (Hold up, hold up, hold up, hold up, lil'—)
Sit down (Hold up, lil' bitch)
Be humble (Hold up, bitch)
Sit down (Hold up, sit down, lil'— sit down, lil' bitch)
Be humble (Hold up, hold up, hold up, hold up, lil' bitch)
Bitch, sit down (Hold up, lil' bitch)
Be humble (Hold up, bitch)
Sit down (Hold up, hold up, hold up, hold up)""",
    },
    "KL_02": {
        "title":  "DNA.",
        "artist": "Kendrick Lamar",
        "lyrics": """I got, I got, I got, I got—
Loyalty, got royalty inside my DNA
Cocaine quarter piece, got war and peace inside my DNA
I got power, poison, pain, and joy inside my DNA
I got hustle, though, ambition flow inside my DNA
I was born like this, since one like this, immaculate conception
I transform like this, perform like this, was Yeshua new weapon
I don't contemplate, I meditate, then off your fucking head
This that put-the-kids-to-bed
This that I got, I got, I got, I got—
Realness, I just kill shit ’cause it's in my DNA
I got millions, I got riches buildin' in my DNA
I got dark, I got evil that rot inside my DNA
I got off, I got troublesome heart inside my DNA
I just win again, then win again, like Wimbledon, I serve
Yeah, that’s him again, the sound that engine in is like a bird
You see fireworks and Corvette tire skrrt the boulevard
I know how you work, I know just who you are
See, you's a, you's a, you's a—
Bitch, your hormones prolly switch inside your DNA
Problem is, all that sucker shit inside your DNA
Daddy prolly snitched, heritage inside your DNA
Backbone don't exist, born outside a jellyfish, I gauge
See, my pedigree most definitely don't tolerate the front
Shit I've been through prolly offend you, this is Paula's oldest son
I know murder, conviction, burners, boosters, burglars, ballers, dead Redemption, scholars, fathers dead with kids
And I wish I was fed forgiveness
Yeah, yeah, yeah, yeah, soldier’s DNA (
I’m a soldier's DNA
)
Born inside the beast, my expertise checked out in second grade
When I was nine, on sale motel, we didn’t have nowhere to stay
At twenty-nine, I've done so well, hit cartwheel in my estate
And I'm gon' shine like I’m supposed to, antisocial extrovert
And excellent mean the extra work
And absentness what the fuck you heard
And pessimists never struck my nerve
And Nazareth gonna plead his case
The reason my power's here on Earth
Salute the truth, when the prophet say




I-I got loyalty, got royalty inside my DNA
This is why I say that hip hop has done more damage to young African Americans than racism in recent years
I-I got loyalty, got royalty inside my DNA
I live a better life, I'm rollin' several dice, fuck your life
I-I got loyalty, got royalty inside my DNA
I live a be-, fuck your life
Five, four, three, two, one
This is my heritage, all I'm inheritin'
Money and power, the mecca of marriages


Tell me somethin'
You motherfuckers can't tell me nothin'
I'd rather die than to listen to you
My DNA not for imitation
Your DNA an abomination
This how it is when you in the Matrix
Dodgin' bullets, reapin' what you sow
And stackin' up the footage, livin' on the go
And sleepin' in a villa
Sippin' from a Grammy, walkin' in the buildin'
Diamond in the ceilin', marble on the floors
Beach inside the window, peekin' out the window
Baby in the pool, godfather goals
Only Lord knows I've been goin' hammer
Dodgin' paparazzi, freakin' through the cameras
Eat at Four Daughters, Brock wearin' sandals
Yoga on a Monday, stretchin' to Nirvana
Watchin' all the snakes, curvin' all the fakes
Phone never on, I don't conversate
I don't compromise, I just penetrate
Sex, money, murder, these are the breaks
These are the times, level number nine
Look up in the sky, ten is on the way
Sentence on the way, killings on the way
Motherfucker, I got winners on the way
You ain't shit without a body on your belt
You ain't shit without a ticket on your plate
You ain't sick enough to pull it on yourself
You ain't rich enough to hit the lot and skate
Tell me when destruction gonna be my fate
Gonna be your fate, gonna be our faith
Peace to the world, let it rotate
Sex, money, murder, our DNA""",
    },
    "KL_03": {
        "title":  "Alright",
        "artist": "Kendrick Lamar",
        "lyrics": """Alls my life, I has to fight, nigga
Alls my life, I—
Hard times like, "Yah"
Bad trips like, "Yah"
Nazareth
I'm fucked up, homie, you fucked up
But if God got us, then we gon' be alright


Nigga, we gon' be alright
Nigga, we gon' be alright
We gon' be alright
Do you hear me, do you feel me? We gon' be alright
Nigga, we gon' be alright
Huh? We gon' be alright
Nigga, we gon' be alright
Do you hear me, do you feel me? We gon' be alright


Uh, and when I wake up
I recognize you're looking at me for the pay cut
But homicide be looking at you from the face down
What MAC-11 even boom with the bass down?
Schemin', and let me tell you 'bout my life
Painkillers only put me in the twilight
Where pretty pussy and Benjamin is the highlight
Now tell my mama I love her, but this what I like, Lord knows
Twenty of 'em in my Chevy, tell 'em all to come and get me
Reapin' everything I sow, so my karma comin' heavy
No preliminary hearings on my record
I'm a motherfuckin' gangster in silence for the record, uh
Tell the world I know it's too late
Boys and girls, I think I've gone cray
Drown inside my vices all day
Won't you please believe when I say


Wouldn't you know
We been hurt, been down before, nigga
When our pride was low
Lookin' at the world like, "Where do we go?" Nigga
And we hate po-po
Wanna kill us dead in the street for sure, nigga
I'm at the preacher's door
My knees gettin' weak and my gun might blow
But we gon' be alright


Nigga, we gon' be alright
Nigga, we gon' be alright
We gon' be alright
Do you hear me, do you feel me? We gon' be alright
Nigga, we gon' be alright
Huh? We gon' be alright
Nigga, we gon' be alright
Do you hear me, do you feel me? We gon' be alright


What you want you, a house⁠? You, a car?
Forty acres and a mule? A piano, a guitar?
Anything, see my name is Lucy, I'm your dog
Motherfucker, you can live at the mall
I can see the evil, I can tell it, I know it's illegal
I don't think about it, I deposit every other zero
Thinkin' of my partner, put the candy paintin' on the Regal
Diggin' in my pocket, ain't a profit big enough to feed you
Every day, my logic get another dollar just to keep you
In the presence of your chico, ah
I don't talk about it, be about it, every day, I sequel
If I got it, then you know you got it, Heaven, I can reach you
Pat Dawg, Pat Dawg, Pat Dawg, my dog, that's all
Bick back and Chad, I trap the bag for y'all
I rap, I black on track, so rest assured
My rights, my wrongs, I write 'til I'm right with God


Wouldn't you know
We been hurt, been down before, nigga
When our pride was low
Lookin' at the world like, "Where do we go?" Nigga
And we hate po-po
Wanna kill us dead in the street for sure, nigga
I'm at the preacher's door
My knees gettin' weak, and my gun might blow
But we gon' be alright


Nigga, we gon' be alright
Nigga, we gon' be alright
We gon' be alright
Do you hear me, do you feel me? We gon' be alright
Nigga, we gon' be alright
Huh? We gon' be alright
Nigga, we gon' be alright
Do you hear me, do you feel me? We gon' be alright


I keep my head up high
I cross my heart and hope to die
Lovin' me is complicated
Too afraid of a lot of changes
I'm alright, and you're a favorite
Dark nights in my prayers


I remembered you was conflicted
Misusing your influence, sometimes I did the same
Abusing my power, full of resentment
Resentment that turned into a deep depression
Found myself screamin' in the hotel room
I didn't wanna self-destruct
The evils of Lucy was all around me
So I went runnin' for answers""",
    },
    "KL_04": {
        "title":  "Swimming Pools (Drank)",
        "artist": "Kendrick Lamar",
        "lyrics": """Pour up (Drank), head shot (Drank)
Sit down (Drank), stand up (Drank)
Pass out (Drank), wake up (Drank)
Faded (Drank), faded (Drank)


Now, I done grew up round some people livin' their life in bottles
Granddaddy had the golden flask, backstroke every day in Chicago
Some people like the way it feel, some people wanna kill their sorrow
Some people wanna fit in with the popular, that was my problem
I was in a dark room, loud tunes, lookin' to make a vow soon
That I'ma get fucked up, fillin' up my cup, I see the crowd mood
Changin' by the minute and the record on repeat
Took a sip, then another sip, then somebody said to me


"Nigga, why you babysittin' only two or three shots?
I'ma show you how to turn it up a notch
First, you get a swimming pool full of liquor, then you dive in it
Pool full of liquor, then you dive in it
I wave a few bottles, then I watch 'em all flock
All the girls wanna play Baywatch
I got a swimming pool full of liquor and they dive in it
Po-pool full of liquor, I'ma dive in it"


Pour up (Drank), head shot (Drank)
Sit down (Drank), stand up (Drank)
Pass out (Drank), wake up (Drank)
Faded (Drank), faded (Drank)


Okay, now open your mind up and listen me, Kendrick
I am your conscience, if you do not hear me, then you will be history, Kendrick
I know that you're nauseous right now 
and I'm hopin' to lead you to victory, Kendrick
If I take another one down, I'ma drown in some poison, abusin' my limit
I think that I'm feelin' the vibe, I see the love in her eyes
I see the feelin', the freedom is granted as soon as the damage of vodka arrived
This how you capitalize, this is parental advised, and apparently, I'm over-influenced
By what you are doin', I thought I was doin' the most 'til someone said to me


"Nigga, why you babysittin' only two or three shots?
I'ma show you how to turn it up a notch
First, you get a swimming pool full of liquor, then you dive in it
Pool full of liquor, then you dive in it
I wave a few bottles, then I watch 'em all flock
All the girls wanna play Baywatch
I got a swimming pool full of liquor and they dive in it
Po-pool full of liquor, I'ma dive in it"


Pour up (Drank), head shot (Drank)
Sit down (Drank), stand up (Drank)
Pass out (Drank), wake up (Drank)
Faded (Drank), faded (Drank)


I ride, you ride, bang
One chopper, one hundred shots, bang
Hop out, do you bang?
Two chopper, two hundred shots, bang
I ride, you ride, bang
One chopper, one hundred shots, bang
Hop out, do you bang?
Two chopper, two hundred shots, bang


Nigga, why you babysittin' only two or three shots?
I'ma show you how to turn it up a notch
First, you get a swimming pool full of liquor, then you dive in it
Pool full of liquor, then you dive in it
I wave a few bottles, then I watch 'em all flock
All the girls wanna play Baywatch
I got a swimming pool full of liquor and they dive in it
Po-pool full of liquor, I'ma dive in it


Pour up (Drank), head shot (Drank)
Sit down (Drank), stand up (Drank)
Pass out (Drank), wake up (Drank)
Faded (Drank), faded (Drank)


Sherane
Sherane (Pool full of— and we-and we dive in it, in-in it)
Sherane, Sherane
(Wat-watch 'em all flock) Aw, man
(Girls wanna play, play, play) Sherane
Where is she takin' me? (I got)
Where is she takin' me? (Po-pool full of liquor, I'ma dive in—)


All I—, all I—, all I—
All I have in life is my new appetite for failure
And I got hunger pain that grow insane, tell me, do that sound familiar?
If it do, then you're like me, makin' excuse that your relief
Is in the bottom of a bottle and the greenest indo leaf
As the window open, I release everything that corrode inside of me
I see you jokin', why you laugh? Don't you feel bad? I probably sleep
And never ever wake up, never ever wake up, never ever wake up
In God I trust, but just when I thought I had enough


They stomped the homie out over a bitch?
K-Dot, you good, blood?
Now we can drop— yeah, we can drop you back off
That nigga's straight, man, that nigga ain't trippin'
We gon' do the same ol' shit
I'ma pop a few shots, they gon' ru— they run opposite way
Fall right in ****'s lap
And he gon' tear they ass up, simple as that
And I hope that bitch that set him up out there, we gon' pop that bitch too
Wait hold up, ayy, I see somebody
*Car door opens and gunshots are fired*
Aha, got them niggas
K-Dot, you good? ****, you good?
Yeah, blood, I'm good, Dave, you good? Dave?
Dave, say somethin'
Dave?
These bitch-ass niggas killed my brother""",
    },
    "KL_05": {
        "title":  "Money Trees",
        "artist": "Kendrick Lamar",
        "lyrics": """Uh, me and my niggas tryna get it, ya bish (Ya bish, ya bish)
Hit the house lick, tell me, is you with it, ya bish? (Ya bish, ya bish)
Home invasion was persuasive (Was persuasive, was persuasive)
From nine to five, I know it's vacant, ya bish (Ya bish, ya bish)
Dreams of livin' life like rappers do (Like rappers do, like rappers do)
Back when condom wrappers wasn't cool (They wasn't cool, they wasn't cool)
I fucked Sherane and went to tell my bros (Tell my bros, tell my bros)
Then Usher Raymond, "Let It Burn" came on ("Let Burn" came on, "Let Burn" came on)
Hot sauce all in our Top Ramen, ya bish (Ya bish, ya bish)
Park the car, then we start rhymin', ya bish (Ya bish, ya bish)
The only thing we had to free our mind (Free our mind, free our mind)
Then freeze that verse when we see dollar signs (See dollar signs, see dollar signs)
You lookin' like an easy come-up, ya bish (Ya bish, ya bish)
A silver spoon, I know you come from, ya bish (Ya bish, ya bish)
And that's a lifestyle that we never knew (We never knew, we never knew)
Go at a reverend for the revenue


It go Halle Berry or hallelujah
Pick your poison, tell me what you doin'
Everybody gon' respect the shooter
But the one in front of the gun lives forever
(
The one in front of the gun, forever
)
And I been hustlin' all day, this-a-way, that-a-way
Through canals and alleyways, just to say
Money trees is the perfect place for shade
And that's just how I feel, nah, nah
A dollar might just fuck your main bitch
That's just how I feel, nah
A dollar might say fuck them niggas that you came with
That's just how I feel, nah, nah
A dollar might just make that lane switch
That's just how I feel, nah
A dollar might turn to a million and we all rich
That's just how I feel


Dreams of livin' life like rappers do (Like rappers do, like rappers do)
Bump that new E-40 after school (Way after school, way after school)
You know, "Big Ballin' With My Homies" (My homies)
Earl Stevens had us thinkin' rational (Thinkin' rational, that's rational)
Back to reality, we poor, ya bish (Ya bish, ya bish)
Another casualty at war, ya bish (Ya bish, ya bish)
Two bullets in my Uncle Tony head (My Tony head, my Tony head)
He said one day I'll be on tour, ya bish (Ya bish, ya bish)
That Louis Burgers never be the same (Won't be the same, won't be the same)
A Louis belt'll never ease that pain (Won't ease that pain, won't ease that pain)
But I'ma purchase when that day is jerkin' (That day is jerkin', day is jerkin')
Pull off at Church's with Pirellis skrrtin' (Pirellis skrrtin', Pirellis skrrtin')
Gang signs out the window, ya bish (Ya bish, ya bish)
Hopin' all of 'em offend you, ya bish (Ya bish, ya bish)
They say your hood is a pot of gold (A pot of gold, a pot of gold)
And we gon' crash it when nobody's home


It go Halle Berry or hallelujah
Pick your poison, tell me what you doin'
Everybody gon' respect the shooter
But the one in front of the gun lives forever
(
The one in front of the gun, forever
)
And I been hustlin' all day, this-a-way, that-a-way
Through canals and alleyways, just to say
Money trees is the perfect place for shade
And that's just how I feel, nah, nah
A dollar might just fuck your main bitch
That's just how I feel, nah
A dollar might say fuck them niggas that you came with
That's just how I feel, nah, nah
A dollar might just make that lane switch
That's just how I feel, nah
A dollar might turn to a million and we all rich
That's just how I feel


Be the last one out to get this dough? No way
Love one of you bucket-headed hoes? No way
Hit the streets, then we break the code? No way
Hit the brakes when they on patrol? No way
Be the last one out to get this dough? No way
Love one of you bucket-headed hoes? No way
Hit the streets, then we break the code? No way
Hit the brakes when they on patrol? No way


'Magine Rock up in them projects where them niggas pick your pockets
Santa Claus don't miss them stockings, liquors spillin', pistols poppin'
Bakin' soda, yola whippin', ain't no turkey on Thanksgivin'
My homeboy just domed a nigga, I just hope the Lord forgive him
Pots with cocaine residue, every day, I'm hustlin'
What else is a thug to do when you eatin' cheese from the government?
Gotta provide for my daughter 'nem, get the fuck up out my way, bish
Got that drum and I got them bands just like a parade, bish
Drop that work up in the bushes, hope them boys don't see my stash
If they do, tell the truth, this the last time you might see my ass
From the gardens where the grass ain't cut, them serpents lurkin', blood
Bitches sellin' pussy, niggas sellin' drugs, but it's all good
Broken promises, steal your watch and tell you what time it is
Take your J's and tell you to kick it where a Foot Locker is
In the streets with a heater under my dungarees
Dreams of me gettin' shaded under a money tree


It go Halle Berry or hallelujah
Pick your poison, tell me what you doin'
Everybody gon' respect the shooter
But the one in front of the gun lives forever
(
The one in front of the gun, forever
)
And I been hustlin' all day, this-a-way, that-a-way
Through canals and alleyways, just to say
Money trees is the perfect place for shade
And that's just how I feel


Kendrick, just bring my car back, man, I, I called in for another appointment
I figured you weren't gonna be back here on time anyway, look
Shit, shit, I just wanna get out the house, man
This man is on one, he feelin' good than a motherfucker
Shit, I'm tryna get my thing goin' too (
Girl, I want your body
)
I'm going over to Merlin house, just bring my car back (
I want your body
)
Shit, he faded, he feelin' good, look, listen to him
'Cause you got a big ol' fat ass
Girl, girl, I want your body
I want your body, 'cause of that big ol' fat ass, girl
See, he high as hell (
I want your body, 'cause of that big ol'—
)
Shit, he ain't even trippin' off them dominoes no more, just bring the car back
Did somebody say dominoes?""",
    },
    "KL_06": {
        "title":  "m.A.A.d city",
        "artist": "Kendrick Lamar",
        "lyrics": """If Pirus and Crips all got along
They'd probably gun me down by the end of this song
Seem like the whole city go against me
Every time I'm in the street, I hear, "Yawk, yawk, yawk, yawk"


Man down, where you from, nigga?
Fuck who you know—where you from, my nigga?
Where your grandma stay, huh, my nigga?
This m.A.A.d city I run, my nigga


Brace yourself, I'll take you on a trip down memory lane
This is not a rap on how I'm slingin' crack or move cocaine
This is cul-de-sac and plenty Cognac and major pain
Not the drill sergeant, but the stress that weighin' on your brain
It was me, L Boog, and Yan Yan, YG Lucky ride down Rosecrans
It got ugly, wavin' yo' hand out the window — check yourself
Uh, Warriors and Conans, hope euphoria can slow dance
With society, the driver seat, the first one to get killed
Seen a light-skinned nigga with his brains blown out
At the same burger stand where **** hang out
Now this is not a tape recorder sayin' that he did it
But ever since that day, I was lookin' at him different
That was back when I was nine, Joey packed the nine
Pakistan on every porch is fine, we adapt to crime
Pack a van with four guns at a time
With the sliding door, fuck is up?
Fuck you shootin' for if you ain't walkin' up, you fuckin' punk?
Pickin' up the fuckin' pump, pickin' off you suckers
Suck a dick or die or sucker punch
A wall of bullets comin' from AK's, AR's, "Ayy, y'all, duck"
That's what mama said when we was eatin' that free lunch
Aw man, goddamn, all hell broke loose
You killed my cousin back in '94, fuck yo' truce
Now crawl your head in that noose
You wind up dead on the news
Ain't no peace treaty, just piecin' BGs up to pre-approve
Bodies on top of bodies, IVs on top of IVs
Obviously the coroner between the sheets like the Isleys
When you hop on that trolley, make sure your color's correct
Make sure you're corporate, or they'll be callin' your mother collect
They say the governor collect all of our taxes, except
When we in traffic and tragic happens, that shit ain't no threat
You movin' backwards if you suggest that you sleep with a TEC
Go buy a chopper and have a doctor on speed dial, I guess
​m.A.A.d. city


Man down, where you from, nigga?
Fuck who you know—where you from, my nigga?
Where your grandma stay, huh, my nigga?
This m.A.A.d city I run, my nigga


If Pirus and Crips all got along
They'd probably gun me down by the end of this song
Seem like the whole city go against me
Every time I'm in the street, I hear, "Yawk, yawk, yawk"




Wake yo' punk-ass up
It ain't nothin' but a Compton thang
G-yeah, real simple and plain
Let me teach you some lessons about the street
(Smoke somethin', nigga?)
Hood ('Sup, cuz?)
It ain't nothin' but a Compton thang
G-yeah, how we do


Fresh outta school 'cause I was a high school grad'
Sleepin' in the livin' room of my mama's pad
Reality struck, I seen the white car crash
Hit the light pole, two niggas hopped out on foot and dashed (Watch out, cuz)
My pops said I needed a job, I thought I believed him
Security guard for a month and ended up leavin'
In fact, I got fired 'cause I was inspired by all of my friends
To stage a robbery, the third Saturday I clocked in
Projects tore up, gang signs get thrown up (Sup?)
Cocaine laced in marijuana
And they wonder why I rarely smoke now
Imagine if your first blunt had you foamin' at the mouth
I was straight tweakin', the next weekend we broke even
I made allegiance that made a promise to see you bleedin'
You know the reasons, but still'll never know my life
Kendrick a.k.a. "Compton's Human Sacrifice"


G-yeah, cocaine, weed
Niggas been mixin' shit since the '80s, loc
Sherm sticks, butt-nakeds
Dip, make a nigga flip
Cluck heads all up and down the block and shit
One time's crooked and shit
Block a nigga in
Alondra, Rosecrans, Bullis, it's Compton


I'm still in the hood, loc, g-yeah, that's cool
Shit, the hood took me under, so I follow the rules
But, g-yeah, that's like me, I grew up in the hood where they bang
And niggas that rep colors is doin' the same thang
Pass it to the left, so I can smoke on me
A couple drive-bys in the hood lately, g-yeah
Couple of IV's with the fuckin' spray-can
Shots in the crowd, then everybody ran
Crew I'm finna slay, the street life I crave
Shots hit the enemy, hearts turn brave
Mount up, regulators in the whip
Down the boulevard with the pistol grip, g-yeah
Trip, we in the hood still
So, loc, grab a strap 'cause, g-yeah, it's so real, g-yeah
Deal with the outcome, a strap in the hand
And a bird and ten grand's where a mothafucka stand


If I told you I killed a nigga at sixteen, would you believe me?
Perceive me to be innocent Kendrick you seen in the street
With a basketball and some Now and Laters to eat?
If I mentioned all of my skeletons, would you jump in the seat?
Would you say my intelligence now is great relief?
And it's safe to say that our next generation maybe can sleep
With dreams of bein' a lawyer or doctor
Instead of boy with a chopper that hold the cul-de-sac hostage
Kill 'em all if they gossip
The Children of the Corn, they vandalizin' the option
Of livin' a lie, drown their body with toxins
Constantly drinkin' and drive
Hit the powder, then watch this flame that arrive in his eye
Listen, coward, the concept is aim and then bang it and slide
Out that bitch with deposit, a price on his head, the tithes
Probably go to the projects
I live inside the belly of the rough, Compton, USA
Made me an Angel on Angel Dust, what?


*Scratches*
M.A.A.d city
Compton


Nigga, pass Dot the bottle, damn
You ain't the one that got fucked up
What you holdin' it for?
Niggas always actin' unsensitive and shit
Nigga, that ain't no word
Nigga, shut up
Hey, Dot, you good, my nigga?
Don't even trip
Just lay back and drink that""",
    },
    "KL_07": {
        "title":  "Backseat Freestyle",
        "artist": "Kendrick Lamar",
        "lyrics": """Uh, Martin had a dream
Martin had a dream
Kendrick have a dream


All my life, I want money and power
Respect my mind or die from lead shower
I pray my dick get big as the Eiffel Tower
So I can fuck the world for seventy-two hours


Goddamn, I feel amazin', damn, I'm in the Matrix
My mind is livin' on cloud nine and this 9 is never on vacation
Start up that Maserati and, vroom, vroom, I'm racin'
Poppin' pills in the lobby and I pray they don't find her naked
And I pray you niggas is hatin', shooters go after Judas
Jesus Christ, if I live life on my knees, ain't no need to do this
Park it in front of Lueders, next to that Church's Chicken
All you pussies is losers, all my niggas is winnin', screamin'


All my life, I want money and power
Respect my mind or die from lead shower
I pray my dick get big as the Eiffel Tower
So I can fuck the world for seventy-two hours


Goddamn, I got bitches (Okay), damn, I got bitches (Okay)
Damn, I got bitches (Yeah), wifey, girlfriend, and mistress
All my life, I want money and power
Respect my mind or die from lead shower


I got twenty-five lighter on my dresser, yes, sir
Put fire to that ass, body cast on a stretcher
And her body got that ass that a ruler couldn't measure
And it make me cum fast, but I never get embarrassed
And I recognize you have what I've been wantin' since that record
That Adina Howard had, pop it fast to impress her
She rollin', I'm holdin' my scrotum, imposin'
This voice here is golden, so fuck y'all, I goes in, and


All my life, I want money and power
Respect my mind or die from lead shower
I pray my dick get big as the Eiffel Tower
So I can fuck the world for seventy-two hours


Goddamn, I got bitches, damn, I got bitches
Damn, I got bitches, wifey, girlfriend, and mistress
All my life, I want money and power
Respect my mind or, nigga, it's go time


I roll in dough with a good grind
And I run that ho with a baton
That's a relay race with a bouquet
They say, "K, you gon' marry mines"
Biatch, no way, biatch, no way
Biatch, no way, biatch, okay
I'm never livin' life confined
It's a failure even if I'm blind
I can tell you who, what, when, where
How to sell your game right on time
Biatch, go play, biatch, go play
Biatch, go play, biatch, I look like O.J.
Killin' everything from pussy to a motherfuckin' Hit-Boy beat
She pussy poppin' and I got options like an audible, I be
C-O-M-P-T-O-N, I win, then ball at your defeat
C-O-M-P-T-O-N, my city mobbin' in the street, yellin'


All my life, I want money and power
Respect my mind or die from lead shower
I pray my dick get big as the Eiffel Tower
So I can fuck the world for seventy-two hours


Goddamn, I got bitches, damn, I got bitches
Damn, I got bitches, wifey, girlfriend, and mistress
All my life, I want money and power
Respect my mind or die from lead shower


Let it run, Ali
Martin had a dream
Martin had a dream
Kendrick have a dream""",
    },
    "KL_08": {
        "title":  "King Kunta",
        "artist": "Kendrick Lamar",
        "lyrics": """I got a bone to pick
I don't want you monkey-mouth motherfuckers
Sittin' in my throne again
Ayy, ayy, nigga, what's happenin'?
K-Dot back in the hood, nigga
I'm mad (
He mad
), but I ain't stressin'
True friends, one question


Bitch, where you when I was walkin'?
Now I run the game, got the whole world talkin'
King Kunta, everybody wanna cut the legs off him
Kunta, black man taking no losses, oh yeah
Bitch, where you when I was walkin'?
Now I run the game, got the whole world talkin'
King Kunta, everybody wanna cut the legs off him
When you got the yams (
What's the yams?
)


The yam is the power that be
You can smell it when I'm walkin' down the street
(
Oh yes, we can, oh yes, we can
)
I can dig rappin', but a rapper with a ghostwriter?
What the fuck happened? (
Oh no
)
I swore I wouldn't tell, but most of y'all sharing bars
Like you got the bottom bunk in a two-man cell (
A two-man cell
)
Something's in the water (
Something's in the water
)
And if I gotta brown-nose for some gold
Then I'd rather be a bum than a motherfuckin' baller (Oh yeah!)


Bitch, where you when I was walkin'?
Now I run the game, got the whole world talkin'
King Kunta, everybody wanna cut the legs off him
King Kunta, black man taking no losses, oh yeah
Bitch, where you when I was walkin'?
Now I run the game, got the whole world talkin'
King Kunta, everybody wanna cut the legs off him
When you got the yams (What's the yams?)


The yam brought it out of Richard Pryor
Manipulated Bill Clinton with desires
Twenty-four-seven, three-sixty-five days times two
I was contemplatin' gettin' off stage
Just to go back to the hood, see my enemy and say (Oh yeah)


Bitch, where you when I was walkin'?
Now I run the game, got the whole world talkin'
King Kunta, everybody wanna cut the legs off him
Kunta, black man taking no losses, oh yeah
Bitch, where you when I was walkin'?
Now I run the game, got the whole world talkin'
King Kunta, everybody wanna cut the legs off him


You goat-mouth mammyfucker
I was gonna kill a couple rappers, but they did it to themselves
Everybody's suicidal, they ain't even need my help
This shit is elementary, I'll probably go to jail
If I shoot at your identity and bounce to the left
Stuck a flag in my city, everybody's screamin', "Compton!"
I should probably run for mayor when I'm done, to be honest
And I put that on my momma and my baby boo too
Twenty million walkin' out the court buildin', woo-woo!
Aw, yeah, fuck the judge
I made it past twenty-five, and there I was
A little nappy-headed nigga with the world behind him
Life ain't shit but a fat vagina
Screamin', "Annie, are you okay? Annie, are you okay?"
Limo tinted with the gold plates
Straight from the bottom, this the belly of the beast
From a peasant to a prince to a motherfuckin' king (
Oh yeah
)


Bitch, where you when I was walkin'?
By the time you hear the next pop
The funk shall be within you
Now I run the game, got the whole world talkin'
King Kunta, everybody wanna cut the legs off him
King Kunta, black man taking no losses, oh yeah
Bitch, where you when I was walkin'?
Now I run the game, got the whole world talkin'
King Kunta, everybody wanna cut the legs off him


Funk, funk, funk, funk, funk, funk, funk, funk, funk, funk, funk
We want the funk
We want the funk
Now if I give you the funk, you gon' take it?
We want the funk
Now if I give you the funk, you gon' take it?
We want the funk
Now if I give you the funk, you gon' take it?
We want the funk
Do you want the funk?
We want the funk
Do you want the funk?
We want the funk
Now if I give you the funk, you gon' take it?
We want the funk


I remember you was conflicted, misusing your influence""",
    },
    "KL_09": {
        "title":  "Bitch, Don't Kill My Vibe",
        "artist": "Kendrick Lamar",
        "lyrics": """I am a sinner
Who's probably gonna sin again
Lord, forgive me, Lord, forgive me
Things I don't understand
Sometimes, I need to be alone
Bitch, don't kill my vibe, bitch, don't kill my vibe
I can feel your energy from two planets away
I got my drink, I got my music, I would share it, but, today, I'm yellin'
Bitch, don't kill my vibe, bitch, don't kill my vibeBitch, don't kill my vibe, bitch, don't kill my vibe


Look inside of my soul and you can find gold and maybe get rich
Look inside of your soul and you can find out it never exist
I can feel the changes
I can feel a new life, I always knew life can be dangerous
I can say that I like a challenge and you tell me it's painless
You don't know what pain is
How can I paint this picture when the colorblind is hangin' witcha?
Fell on my face and awoke with a scar, another mistake livin' deep in my heart
Wear it on top of my sleeve in a flick, I can admit that it did look like yours
Why you resent every makin' of his? Tell me your purpose is petty again
But even a small lighter can burn a bridge, even a small lighter can burn a bridge


I can feel the changes
I can feel the new people 'round me just wanna be famous
You can see that my city found me, then put me on stages
To me, that's amazin'
To you, that's a quick check, with all disrespect, let me say this


I am a sinner
Who's probably gonna sin again
Lord, forgive me, Lord, forgive me
Things I don't understand
Sometimes, I need to be alone
Bitch, don't kill my vibe, bitch, don't kill my vibe
I can feel your energy from two planets away
I got my drink, I got my music, I would share it, but, today, I'm yellin'
Bitch, don't kill my vibe, bitch, don't kill my vibeBitch, don't kill my vibe, bitch, don't kill my vibe


I'm tryna keep it alive and not compromise the feelin' we love
You're tryna keep it deprived and only cosign what radio does
And I'm lookin' right past ya
We live in a world, we live in a world on two different axles
You live in a world, you livin' behind the mirror
I know what you're scared of, the feeling of feeling emotions inferior
This shit is vital, I know you had to, this shit is vital, I know you had to
Die in a pitiful vain, tell me a watch and a chain is way more believable
Give me a feasible gain, rather a seasonal name, I'll let the people know
This is somethin' you can blame on yourself, you can remain stuck in a box
I'ma break out and then hide every lock, I'ma break out and then hide every lock


I can feel the changes
I can feel the new people 'round me just wanna be famous
You can see that my city found me, then put me on stages
To me, that's amazin'
To you, that's a quick check, with all disrespect, let me say this


I am a sinner
Who's probably gonna sin again
Lord, forgive me, Lord, forgive me
Things I don't understand
Sometimes, I need to be alone
Bitch, don't kill my vibe, bitch, don't kill my vibe
I can feel your energy from two planets away
I got my drink, I got my music, I would share it, but, today, I'm yellin'
Bitch, don't kill my vibe, bitch, don't kill my vibeBitch, don't kill my vibe, bitch, don't kill my vibe


Bitch, don't kill my vibe
You ain't heard the coast like this in a long time, don't you see that long line?
And they waitin' on Kendrick like the first and the fifteenth
Threes in the air, I can see you are in sync
Hide your feelings, hide your feelings, now, what you better do
I'll take your girlfriend 
then put that pussy on the pedestal


Bitch, don't kill my vibe, bitch, don't kill my vibeWalk out the door and they scream, "It's alive"
My New Year's resolution is to stop all the pollution
Talk too motherfuckin' much, I got my drink, I got my music
I say, bitch, don't kill my vibe, bitch, don't kill my vibe
Bitch, don't kill my vibe, bitch, don't kill my vibe


K-Dot, get in the car, nigga
Come on, we finna roll out
Nigga, I got a pack of Blacks and a beat CD
Get your freestyles ready""",
    },
    "KL_10": {
        "title":  "Poetic Justice",
        "artist": "Kendrick Lamar",
        "lyrics": """Every second, every minute, man, I swear that she can get it
Say if you a bad bitch, put your hands up high
Hands up high, hands up high
Tell 'em dim the lights down right now, put me in the mood
I'm talkin' 'bout dark room, perfume
Go, go


(
In the thundering rain
)
I recognize your fragrance, hol' up, you ain't never gotta say shit, uh
And I know your taste is a little bit, mmm, high maintenance, uh
Everybody else basic, you live life on an everyday basis
With poetic justice, poetic justice
If I told you that a flower bloomed in a dark room, would you trust it?
I mean, I write poems in these songs dedicated to you when
You're in the mood for empathy, it's blood in my pen
Better yet, where your friends and 'em? I really wanna know you all
I really wanna show you off, fuck that
Pour up plenty of champagne, cold nights when you curse this name
You called up your girlfriends and y'all curled in that little bitty Range, I heard that
She wanna go and party, she wanna go and party
Nigga, don't approach her with that Atari
Nigga, that ain't good game, homie, sorry
They say conversation rule a nation, I can tell
But I could never right my wrongs 'less I write it down for real, PS


(
An-an-an-an-anytime
)
You can get it, you can get it, you can get it, you can get it (
And any place
)
And I know just, know just, know just, know just, know just what you want
Poetic justice, put it in a song, alright
(
An-an-an-an-anytime
)
You can get it, you can get it, you can get it, you can get it (
And any place
)
And I know just, know just, know just, know just, know just what you want
Poetic justice, put it in a song, alright


(
In the thundering rain
)
I really hope you play this 'cause, oh, girl, you test my patience
With all these seductive photographs and all these one-off vacations you've been takin'
Clearly a lot for me to take in, it don't make sense
Young East African girl, you too busy fuckin' with your other man
I was tryna put you on game, put you on a plane
Take you and your mama to the motherland, I could do it
Maybe one day, when you figure out you're gonna need someone
When you figure out it's alright here in the city and you don't run from where we come from
That sound like poetic justice, poetic justice
You were so new to this life, but goddamn, you got adjusted
I mean, I write poems in these songs, dedicated to the fun sex
Your natural hair and your soft skin and your big ass in that sundress, ooh
Good God, what you doin' that walk for?
When I see that thing move, I just wish we would fight less and we would talk more
And they say communication save relations, I can tell
But I can never right my wrongs unless I write 'em down for real, PS


(
An-an-an-an-anytime
)
You can get it, you can get it, you can get it, you can get it (
And any place
)
And I know just, know just, know just, know just, know just what you want
Poetic justice, put it in a song, alright
(
An-an-an-an-anytime
)
You can get it, you can get it, you can get it, you can get it (
And any place
)
And I know just, know just, know just, know just, know just what you want
Poetic justice, put it in a song, alright


(
In the thundering rain
)
Every time I write these words, they become a taboo
Makin' sure my punctuation curve, every letter here's true
Livin' my life in the margin and that metaphor was proof
I'm talkin' poetic justice, poetic justice
If I told you that a flower bloomed in a dark room, would you trust it?
I mean, you need to hear this
Love is not just a verb, it's you lookin' in the mirror
Love is not just a verb, it's you lookin' for it, maybe, call me crazy, we can both be insane
A fatal attraction is common, and what we have common is pain
I mean, you need to hear this
Love is not just a verb and I can see power steerin'
Sex drive when you swerve, I want that interference, it's coherent, I can hear it, mhm
That's your heartbeat, it either caught me or it called me, mhm
Read slow and you'll find gold mines in these lines
Sincerely, yours truly, and right before you go blind, PS


(
An-an-an-an-anytime
)
You can get it, you can get it, you can get it, you can get it (
And any place
)
And I know just, know just, know just, know just, know just what you want
Poetic justice, put it in a song


I'm gon' ask you one more time, homie
Where is you from? Or it is a problem
Ayy, ayy, ayy, ayy, ayy, ask him if he over here for Sherane
Ayy, you over here for Sherane, homie?
I don't care who this nigga over here for
If he don't tell me where he from, it's a wrap, I'm sorry
Hold up, hold up, hold up, hold up, we gon' do it like this, okay?
I'ma tell you where I'm from, okay?
You gon' tell me where you from, okay?
Or, or, or where your grandma stay
Where your mama stay, or where your daddy stay, okay?
Fuck all this talkin'
As a matter fact, get out the van, homie
Get out the car 'fore I snatch you out that motherfucker, homie""",
    },
    "KL_11": {
        "title":  "These Walls",
        "artist": "Kendrick Lamar",
        "lyrics": """I remember you was conflicted, misusing your influence
Sometimes, I did the same


If these walls could talk
If these walls could talk
If these walls could talk
If these walls could talk
If these walls could talk
If these walls could talk—
Sex


She just wanna close her eyes and sway
With you, with you, with you (
Ah, come on
)
Exercise her right to work it out
It's true, it's true, it's true
Shout out to the birthday girls
Say hey (Hey), say hey (Hey, 
ah, girl
)
Everyone deserves a night to play (Play)
She plays, only when you tell her no


If these walls could talk
I can feel your reign when it cries, gold lives inside of you
If these walls could talk
I love it when I'm in it, I love it when I'm in it
 (
Oh, oh, oh, oh, oh
)
Oh, oh


These walls could talk, they'd tell me to swim good
No boat, I float better than he would
No life jacket, I'm not the God of Nazareth
But your flood can be misunderstood
Walls tellin' me they full of pain, resentment
Need someone to live in 'em just to relieve tension
Me, I'm just a tenant
Landlord said these walls vacant more than a minute
These walls are vulnerable, exclamation
Interior pink, color coordinated
I interrogated every nook and cranny
I mean, it's still amazing, before, they couldn't stand me
These walls wanna cry tears
These walls happier when I'm here
These walls never could hold up
Every time I come around, demolition might crush


If these walls could talk
I can feel your reign when it cries, gold lives inside of you
If these walls could talk
I love it when I'm in it, I love it when I'm in it
 (
Oh, oh, oh, oh, oh
)
Oh, oh


These walls could talk, they'd tell me to go deep
Yellin' at me continuously, I can see
Your defense mechanism is my decision
Knock these walls down, that's my religion
Walls feelin' like they ready to close in
I suffocate, then catch my second wind
I resonate in these walls
I don't know how long I can wait in these walls
I've been on the streets too long
Lookin' at you from the outside in
They sing the same old song
About how they walls always the cleanest
I beg to differ, I must've missed them
I'm not involved, I'd rather diss 'em
I'd rather call on you, put your wall up
'Cause when I come around, demolition gon' crush


If these walls could talk
I can feel your reign when it cries, gold lives inside of you
If these walls could talk
I love it when I'm in it, I love it when I'm in it
 (
Oh, oh, oh, oh, oh
)
Oh, oh




If your walls could talk, they'd tell you it's too late
Your destiny accepted your fate
Burn accessories and stash 'em on the yard
Take the recipe, the Bible and God
Wall tellin' you that commissary is low
Race wars happenin', no callin' CO
No callin' your mother to save you
Homies to say you're irrepetible, not acceptable
Your behavior is Sammy the Bull like
A killer that turned snitch
Walls is tellin' me you a bitch
You pray for appeals hopin' the warden would afford them
That sentence so important
Walls tellin' you to listen to "Sing About Me"
Retaliation is strong, you even dream 'bout me
Killed my homeboy and God spared your life
Dumb criminal got indicted same night
So when you play this song, rewind the first verse
About me abusin' my power so you can hurt
About me and her in the shower whenever she horny
About me and her in the after hours of the morning
About her baby daddy currently servin' life
And how she think about you until we meet up at night
About the only girl cared about you when you asked her
And how she fuckin' on a famous rapper
Walls can talk (Talk)


I remember you was conflicted
Misusing your influence
Sometimes I did the same
Abusing my power, full of resentment
Resentment that turned into a deep depression
Found myself screaming in a hotel room""",
    },
    "KL_12": {
        "title":  "i",
        "artist": "Kendrick Lamar",
        "lyrics": """Is this mic on?
 (
Hey, move this way, this way
)
Hey, hey, hey, turn the mic up, c'mon, c'mon
Is the mic on or not? I want the mic
We're bringin' up nobody, nobody
Nobody but the number one rapper in the world
He done traveled all over the world
He came back just to give you some game
All of the little boys and girls, come up here
(Ah, one two, one two, what's happenin', fool?)
Come right here, this is for you, come on out
I done been through a whole lot (
Kendrick Lamar
)
Trial, tribulation, but I know God
The Devil wanna put me in a bow tie (
Make some noise, brother
)
Pray that the holy water don't go dry, yeah, yeah
As I look around me
So many motherfuckers wanna down me
But enemigo never drown me
In front of a dirty double-mirror they found me


And I love my (
I love myself
)
Huh, when you lookin' at me, ah, tell me what do you see? (
I love myself
)
Ah, I put a bullet in the back of the back of the head of the poli' (
I love myself
)
Uh, illuminated by the hand of God, boy, don't seem shy (
I love myself
)
One day at a time, huh


They wanna say it's a war outside, bomb in the street
Gun in the hood, mob of police
Rock on the corner with a line for the fiend
And a bottle full of lean and a model on the scheme, uh
These days of frustration keep 
y'all on tuck and rotation
 (Come to the front)
Yeah, I duck these cold faces, post up fi-fie-fo-fum basis
Dreams of reality's peace (
Oh, yeah
)
Blow steam in the face of the beast
Sky could fall down, wind could cry now
Look at me, motherfucker, I smile


And I love my (
I love myself
)
Uh, and when you lookin' at me, ah, tell me what do you see? (
I love myself
)
Ah, I put a bullet in the back of the back of the head of the poli' (
I love myself
)
Uh, illuminated—
All y'all come to the front, y'all come up to the front (
I love myself
)
Baby, what about you? Come on


(
Crazy, what you gon' do?
)
Lift up your head and keep movin' (
Keep movin'
), turn the mic up
(
Haunt you
)
Peace to fashion police, I wear my heart
On my sleeve, let the runway start
You know the miserable do love company
What do you want from me and my scars?
Everybody lack confidence, everybody lack confidence
How many times my potential was anonymous?
How many times the city making me promises?
So I promise this, nigga


I love myself
Uh, and when you lookin' at me, ah, tell me what do you see? (
I love myself
)
Ah, I put a bullet in the back of the back of the head of the poli' (
I love myself
)
Huh, illuminated by the hand of God, boy don't seem shy
(
I love myself
)


Huh (Walk my bare feet), huh (Walk my bare feet)
Huh (Down, down valley deep), huh (Down, down valley deep)
(I love myself) Huh (Fi-fie-fo-fum), huh (Fi-fie-fo-fum)
(I love myself) Huh (My heart undone), one, two, three


I went to war last night
With an automatic weapon, don't nobody call a medic
I'ma do it 'til I get it right (
Oh, no
)
I went to war last night (
Night, night, night, night, woo
)
I've been dealin' with depression ever since an adolescent
Duckin' every other blessin', I can never see the message
I could never take the lead, I could never bob and weave
From a negative and lettin' them annihilate me
And it's evident I'm movin' at a meteor speed
Finna run into a buildin', lay my body—


(*Offstage argument*)
Ayy, hold on, woah, woah, stop all this
Not on my, not while I'm up here
Not on my time, kill the music, not on my time
We could save that shit for the streets
We could save that shit, this for the kids, bro
2015, niggas tired of playin' victim, dog
Niggas ain't trying to play vic— TuTu, how many niggas we done lost?
How many, Yan-Yan, how many we lost?
No, for real, answer the que— how many niggas we done lost, bro?
This, this year alone?
Exactly, so we, we ain't got time to waste time, my nigga
Niggas gotta make time, bro
The judge make time, you know that, the judge make time, right?
The judge make time so it ain't shit
It shouldn't be shit for us to come out here and appreciate the little bit of life we got left, dog
On the dead homies, Charlie P, you know that, bro, you know that
Right, it's man— it's mando, right, it's mando
And I s— and I, and I, and I say this because I, I love you niggas, man
I love all my niggas, bro
Exac— enough said, enough said
And we gon' get back to the show and move on, because that shit petty, my nigga
Mic check, mic check, mic check, mic check, mic check
We gon' do some acapella shit before we get back to a—
All my niggas listen, listen to this
I promised Dave I'd never use the phrase "fuck nigga"
He said, "Think about what you saying, 'Fuck niggas'
No better than Samuel on Django
No better than a white man with slave boats"
Sound like I needed some soul searchin'
My pops gave me some game in real person
Retraced my steps on what they never taught me
Did my homework fast before government caught me
So I'ma dedicate this one verse to Oprah
On how the infamous, sensitive N-word control us
So many artists gave her an explanation to hole us
Well, this is my explanation straight from Ethiopia
N-E-G-U-S, definition: royalty, king royalty, wait, listen
N-E-G-U-S, description: black emperor, king, ruler, now let me finish
The history books overlooked the word and hide it
America tried to make it to a house divided
The homies don't recognize we been usin' it wrong
So I'ma break it down and put my game in a song
N-E-G-U-S, say it with me, or say it no more
Black stars can come and get me
Take it from Oprah Winfrey, tell her she right on time
Kendrick Lamar, by far, realest Negus alive

​​​​​​​​​​​​​​​​​""",
    },
    "KL_13": {
        "title":  "Die Hard",
        "artist": "Kendrick Lamar",
        "lyrics": """I pop the pain away, I slide the pain away
I pop the pain away, I slide the pain away
I picked you up when you fell and cut your knee
Told you not to cry and held you close to me


I hope I'm not too late
To set my demons straight
I know I made you wait
But how much can you take?
I hope you see the God in me
I hope you can see
And if it's up, stay down for me
Yeah


Shimmy, shimmy, cocoa puff
Serafina, flame in us
Where I'd be without your love
Rest your wings and trust, I feel you
Deep, I feel, deep, I feel (I know we're feelin' deep)
Deep, I feel, deep, too (I know we're feelin' too deep)
Deep, I feel, deep, I feel (I know we're feelin' deep)
Deep, I feel, deep, you (I know we're feelin')


Do you love me? Do you trust me?
Can I trust you? Don't judge me
I'ma die hard, it gets ugly
Too passionate, it gets ugly
Mmm, ah-ah
I wonder where I lost my way?
Mmm, ah-ah
Been waiting on your call all day
Tell me you in my corner right now
When I fall short, I'm leanin' on you to cry out
We all got enough to lie about
My truth too complicated to hide now
Can I open up? Is it safe or not?
I'm afraid a little, you relate or not?
Have faith a little, I might take my time
Ain't no savin' face this time


I hope I'm not too late
To set my demons straight
I know I made you wait
But how much can you take?
I hope you see the God in me
I hope you can see
And if it's up, stay down for me
Yeah


Shimmy, shimmy, cocoa puff
Serafina, flame in us
Where I'd be without your love
Rest your wings and trust, I feel you
Deep, I feel, deep, I feel (
I know we're feelin' deep
)
Deep, I feel, deep, too (
I know we're feelin' too deep
)
Deep, I feel, deep, I feel (
I know we're feelin' deep
)
Deep, I feel, deep, you (
I know we're feelin'
)


I got some regrets
I-I-I-I-I-I-I
But my past won't keep me from my best
I-I-I-I-I-I-I
Subtle mistakes felt like life or death
I-I-I-I-I-I-I
I wanna see the family stronger
I wanna see the money longer
You know that I'd die for you
I get emotional about life
The lost ones keepin' me up at night
The world be reminding me it's danger
I'll still risk it all for a stranger
If I told you who I am, would you use it against me?
Right or wrong, no stone, just love to send me


I hope I'm not too late
To set my demons straight
I know I made you wait
But how much can you take?
I hope you see the God in me
I hope you can see
And if it's up, stay down for me
Yeah


Baby, you make me
Pray for London
Yeah
'Cause if I won it all without you involved
(Fucking love you)
I guess it's all for nothing""",
    },
    "KL_14": {
        "title":  "Rich Spirit",
        "artist": "Kendrick Lamar",
        "lyrics": """Takin' my baby to school, then I pray for her
'Cause you bitches ain't never been cool, writin' testament
Paintin' pictures, put me in the Louvre, that's a definite
Universal shift, I'm in a groove
And celebrity do not mean integrity, you fool
I'm a good man, shake your hand, firm grip rule
Seventy-two wins, lost ten, ballin' with the flu
More than two M's for a show, but add another two
Hmm, lil' Man-Man, the big mans
The GT Dyno flippin' the kickstand, ooh


Rich nigga, broke phone (
Ah
)
Tryna keep the balance, I'm stayin' strong (
Ooh
)
Stop playin' with me 'fore I turn you to a song (
Yeah
)
Stop playin' with me 'fore I turn you to a song (
Ooh
)
Ayy, bitch, I'm attractive (Ah)
Can't fuck with you no more, I'm fastin', ugh (
Ooh
)
Bitch, I'm attractive (Ah, ah, ah, ah)
Can't fuck with you no more, I'm fastin', ugh


The morality can wait, feedback on low latency, I'm glitching from the face
As my thoughts grow sacredly, I'm runnin' out of space
Ask Whitney, she okay, never mind a hundred K
Why you lyin' on Benjamin? He turnin' in his grave
I'd be lyin' if I said I wouldn't give this shit away
The aloof Buddha, I'm Christ with a shooter
Praise to Muhammad, I might nigga noose ya
AP, Michael Friedman, my friends cooler
Primary, so the resale value stupid
I would never live my life on a computer
IG'll get you life for a chikabooya
More power to ya, love 'em from a distance
Why you always in the mirror more than the bitches?
And my cousin tried to sue me like he got the privilege
But I didn't lose sleep 'cause I got the spirit, ayy (Ooh)


Rich nigga, broke phone (
Ah
)
Tryna keep the balance, I'm stayin' strong (
Ooh
)
Stop playin' with me 'fore I turn you to a song (
Yeah
)
Stop playin' with me 'fore I turn you to a song (
Ooh
)
Ayy, bitch, I'm attractive (
Ah
)
Can't fuck with you no more, I'm fastin', ugh (
Ooh
)
Bitch, I'm attractive (Ah, ah, ah, ah)
Can't fuck with you no more, I'm fastin', ugh


Dun-duh, dun-duh, dun-duh, duh, dum
Dun-duh-duh, duh, duh
Dun-duh, dun-duh, dun-duh, dun-duh, dun


Frat brother, real nigga, that brother
We just upped the score, give me dap, brother
Spirit medium, I don't rap, brother
We headed there now, are you strapped, brother?
Ayy, peacemaker, but I'm not naive, brother
Ayy, gotta watch your homies and police, brother
Ayy, clout chasing hell of a disease, brother
I'm fasting four days out the week, brother
I pray to God that you realize the entourage is dead
I pray to God that you not lackin' when you off the meds
I pray to God she know them Cabo trips don't last forever
Bet she argue with her momma, go and get them kids
I pray to God you actually pray when somebody dies
Thoughts and prayers, way better off timelines
False claimin' not cute, I'm mortified
The New Earth in hot pursuit, two-hundred lives


Rich nigga, broke phone (
Ah
)
Tryna keep the balance, I'm stayin' strong (
Ooh
)
Stop playin' with me 'fore I turn you to a song (
Yeah
)
Stop playin' with me 'fore I turn you to a song (
Ooh
)
Ayy, bitch, I'm attractive (Ah)
Can't fuck with you no more, I'm fastin', ugh (
Ooh
)
Bitch, I'm attractive (Ah, ah, ah, ah)
Can't fuck with you no more, I'm fastin', ugh


Dun-duh, dun-duh, dun-duh, duh, dum
Dun-duh-duh, duh, duh
Dun-duh, dun-duh, dun-duh, dun-duh, dun""",
    },
    "KL_15": {
        "title":  "N95",
        "artist": "Kendrick Lamar",
        "lyrics": """Hello, new world, all the boys and girls
I got some true stories to tell
You're back outside, but they still lied
Woah, yeah


Take off the foo-foo, take off the clout chase, take off the Wi-Fi
Take off the money phone, take off the car loan, take off the flex and the white lies
Take off the weird-ass jewelry, I'ma take ten steps, then I'm takin' off top five
Take off them fabricated streams and them microwave memes, it's a real world outside (Take that shit off)
Take off your idols, take off the runway, I take off to Cairo (Take that shit off)
Take off to Saint-Tropez, five-day stay, take a quarter mil', hell if I know (Take that shit off)
Take off the front flag, take off perception, take off the cop with the eye patch (Take that shit off)
Take off the unloyal, take off the unsure, take off decisions I lack (Take it off)
Take off the fake deep, take off the fake woke, take off the, "I'm broke, I care" (Take it off)
Take off the gossip, take off the new logic that if I'm rich, I'm rare (Take it off)
Take off the Chanel, take off the Dolce, take off the Birkin bag (Take it off)
Take all that designer bullshit off, and what do you have?


Bitch, huh, huh, ugh, you ugly as fuck (You outta pocket)
Huh, two ATMs (Hah, hah, hah, hah), you steppin' or what? (You outta pocket)
Huh, who you think they talk about? Talk about us (You outta pocket; shoot, shoot, shoot)
Who you think they copy off? (Brrt, brrt, brrt, brrt, brrt) Copy off us (Get back in pocket)


The world in a panic, the women is stranded, the men on a run
The prophets abandoned, the law take advantage, the market is crashin', the industry wants
Niggas and bitches to sleep in a box while they makin' a mockery followin' us
This ain't Monopoly, watchin' for love, this ain't monogamy, y'all gettin' fucked
Jumpin' on what the hell is that? I gotta relax when I feel (Huh, facts)
All my descendants, they come in my sleep and say I am too real (Huh, facts)
I'm done with the sensitive, takin' it personal, done with the black and the white, the wrong and the right
You hopin' for change and clericals, I know the feelings that came with burial's cries


Bitch, huh, huh, ugh, you ugly as fuck (You outta pocket)
Huh, two ATMs (Hah, hah, hah, hah, hah), you steppin' or what? (You outta pocket)
Huh, who you think they talk about? Talk about us (You outta pocket; shoot, shoot, shoot)
Who you think they copy off? (Brrt, brrt, brrt, brrt) Copy off us


Servin' up a look, dancin' in a drought
Hello to the big stepper, never losin' count
Ventin' in the safe house
Ventin' in the sa—


Can I vent all my truth? I got nothin' to lose, I got problems and pools, I can swim on my faith
Cameras movin' whenever I'm movin', the family suin' whatever I make
Murder is stackin', the president actin', the government taxin' my funds in the bank
Homies attractin' the feds when I'm brackin', look at my reaction, my pupils on skates (Hold up, hold up)
Let's think about this for a second (Let's go)
Tell me what you would do for aesthetic (Let's go)
Would you sell your soul on credit? (
Let's go
)
Would you sell your bro for leverage? (
Let's go
)
Where the hypocrites at?
What community feel they the only ones relevant? (
Let's go
)
Where the hypocrites at?
What community feel they the only ones relevant? (
Let's go
)


Huh, huh, huh, you outta pocket, yeah, you outta pocket (This shit hard)
You entertain the mediocre, need to stop it (This shit hard)
You entertainin' old friends when they toxic (This shit hard)
What your life like? Bullshit and gossip (This shit hard)
What the fuck is cancel culture, dog?
Say what I want about you niggas, I'm like Oprah, dog
I treat you crackers like I'm Jigga, watch, I own it all
Oh, you worried 'bout a critic? That ain't protocol (Bitch)""",
    },
}
