# Auto-generated by 03_build_schema.py — do not edit manually.
# Artist: LCD Soundsystem  |  Code: LCD
# Songs included: 12  |  Missing: 0

LCD_SCHEMA = {
    "LCD_01": {
        "title":  "All My Friends",
        "artist": "LCD Soundsystem",
        "lyrics": """That's how it starts
We go back to your house
You check the charts
And start to figure it out
And if it's crowded, all the better
Because we know we're gonna be up late
But if you're worried about the weather
Then you picked the wrong place to stay
That's how it starts


And so it starts
You switch the engine on
We set controls for the heart of the sun
One of the ways that we show our age
And if the sun comes up, if the sun comes up
If the sun comes up and I still don't wanna stagger home
Then it's the memory of our betters
That are keeping us on our feet


You spent the first five years trying to get with the plan
And the next five years trying to be with your friends again
Oh, you're talking forty-five turns just as fast as you can
Yeah, I know it gets tired, but it's better when we pretend


It comes apart
The way it does in bad films
Except the part
Where the moral kicks in
Though when we're running out of the drugs
And the conversation's grinding away
I wouldn't trade one stupid decision
For another five years of life


Oh, you drop the first ten years just as fast as you can
And the next ten people who are trying to be polite
When you're blowing eighty-five days in the middle of France
Yeah, I know it gets tired, only where are your friends tonight?




And to tell the truth
Oh, this could be the last time
So here we go
Like a sales force into the night
And if I'm made a fool, if I'm made a fool
If I'm made a fool on the road, there's always this
And if I'm sued into submission
I can still come home to this


And with a face like a dad and a laughable stand
You can sleep on the plane or review what you said
When you're drunk and the kids look impossibly tan
You think over and over, "Hey, I'm finally dead"
Oh, if the trip and the plan come apart in your hand
You can turn it on yourself, you ridiculous clown
You'll forget what you meant when you read what you said
And yeah, we knew you were tired, but then


Where are your friends tonight?
Where are your friends tonight?
Where are your friends tonight?
If I could see all my friends tonight
If I could see all my friends tonight
If I could see all my friends tonight
If I could see all my friends tonight""",
    },
    "LCD_02": {
        "title":  "Daft Punk Is Playing at My House",
        "artist": "LCD Soundsystem",
        "lyrics": """Ha-ow! Ow!
(Ow! Ohh)


Well, Daft Punk is playing at my house, my house
I'll show you the ropes kid, show you the ropes
I got a bus and a trailer at my house, my house
I'll show you the ropes kid, show you the ropes
I bought fifteen cases for my house, my house
All the furniture, it's in the garage
Well, Daft Punk is playing at my house, my house
You got to set them up kid, set them up


You got to set 'em up (Ooh, ooh, yeah!)
You got to set 'em up (Ooh, ooh, yeah!)
You got to set them up, set them up


Well, Daft Punk is playing at my house, my house
I waited seven years and fifteen days
There's every kid for miles at my house, my house
And the neighbors can't call the police
There's a fist fight brewin' at my house, my house
Because the jocks can't get in the door
When Daft Punk is playing at my house, my house
You got to set them up kid, set them up


You got to set 'em up (Ooh, ooh, yeah!)
You got to set 'em up (Ooh, ooh, yeah!)
You got to set them up, set them up
You got to set 'em up (Ooh, ooh, yeah!)
You got to set 'em up (Ooh, ooh, yeah!)
You got to set them up, set them up
(Solo!)




Well, everybody's lined up in my house, my house
And Sarah's girlfriend is working the door
Got everybody's PA in my house, my house
All the robots, ah, descend from the bus
There's a freak out brewing in my house, my house
In the basement
'Cause Daft Punk is playing at my house, my house
You got to set them up kid, set them up


You got to set 'em up (Ooh, ooh, yeah!)
You got to set 'em up (Ooh, ooh, yeah!)
You got to set them up, set them up
You got to set 'em up (Ooh, ooh, yeah!)
You got to set 'em up (Ooh, ooh, yeah!)
You got to set them up, set them up


And never, never let them go
No never, never, never let them go
Never, never, never let them go
Let 'em go
Never, never, never let them go
Oh never, never, never let them go
Never, never, never let them go
Let them go
Downtown""",
    },
    "LCD_03": {
        "title":  "I Can Change",
        "artist": "LCD Soundsystem",
        "lyrics": """Tell me a line make it easy for me
Open your arms
Dance with me until I feel all right
It's good in the dark, good in the dark
But into the lover's light
Here comes another fight
So ring the alarm, ring the alarm
Bore me and hold me and cling to my arm
Here it comes, here it comes
And what you're asking me now, disastrous now
Hoping and hoping and hoping
The feeling goes away


Never change, never change, never change, never change
Never change, never change, never change
This is why I fell in love
Never change, never change, never change, never change
Never change, never change, never change
That's just who I fell in love with


This is the time the very best time
So give me a line and take me home
Take me over

Dashing the hopes, dashing the hopes
And smashing the pride
The morning's got you on the ropes
And love is a murderer, love is a murderer
But if she calls you tonight
Everything is all right
Yeah, we know
And love is a curse shoved in a hearse
Love is an open book to a verse of your bad poetry
And this is coming from me


But I can change, I can change, I can change, I can change
I can change, I can change, I can change
If it helps you fall in love
(oh)


And I can change, I can change, I can change, I can change
I can change, I can change, I can change
If it helps you feel real love


Turn on the light, make it easy for me
Feel the divide, fumble in the kitchen
'Til it's right
What an awful sight
But there's love in your eyes
Love in your eyes, love in your eyes
But maybe that's just your love of fights
All night!


I can change, I can change, I can change, I can change
I can change, I can change, I can change
If it helps you fall in love


I can change, I can change, I can change, I can change
I can change, I can change, I can change
If it helps you fall in love
(in love)""",
    },
    "LCD_04": {
        "title":  "Drunk Girls",
        "artist": "LCD Soundsystem",
        "lyrics": """(Drunk girls
Drunk girls
Drunk girls
Drunk girls)

(Drunk girls)
Drunk girls cause a couple of heart attacks
(Drunk girls)
Drunk girls are unusually mild
(Drunk boys)
Drunk boys keep in pace with the pedophiles
(Drunk girls)
Drunk girls are boringly wild
(Drunk girls)
Drunk girls get invitations from nations
(Drunk girls)
They got the patience of a millions of saints
(Drunk boys)
They steal, they steal from the cupboards
(Drunk girls)
Drunk girls like to file complaints


(Drunk girls)
Drunk girls are like a night of simplicity
(Drunk girls)
They need a lover who is smarter than me
Well (drunk boys)
Drunk boys, we walk like pedestrians
(Drunk girls)
Drunk girls wait an hour to pee
(Drunk girls)
Drunk girls know that love is an astronaut
(Drunk girls)
It comes back, but it's never the same
(Drunk boys)
Drunk boys, drunk boys, drunk boys, drunk boys
(Drunk boys have such beautiful feelings)
(Drunk girls)
Drunk girls can be just as insane


Oh oh oh
I believe in waking up together
So oh oh
That means making eyes across the room


(Drunk girls)
Just 'cause I'm shallow doesn't mean that I'm heartless
(Drunk girls)
Just 'cause I'm heartless doesn't mean that I'm mean but
(Drunk boys)
Sometimes love gives us too many options
(Drunk girls)
Just 'cause you're hungry doesn't mean that you're lean
(Drunk girls)
I've heard lies that could curdle your heartstrings
(Drunk girls)
A couple truths, maybe burn out your eyes but
(Drunk boys)
Drunk boys leave their irons in the fireplace
(Drunk girls)
'Cause drunk girls give them too many tries


Drunk girls, drunk girls, drunk girls, drunk girls
Drunk girls, drunk girls, drunk girls, drunk girls
Drunk girls, drunk girls, drunk girls, drunk girls
Drunk girls, drunk girls, drunk girls, drunk


Oh oh oh
I believe in waking up together
Oh oh oh
I believe I'm waking up, but no promises
No oh oh
I believe in waiting out the weather
Oh oh oh
I believe in making eyes across the room
(The day becomes the night)
Oh oh oh
I believe in waking up together
(The day becomes the night)
Oh oh oh
I believe in waking up together
(The day becomes the night)
Oh oh oh
I believe in waking up together
(The day becomes the night)
But still, be honest with me, honestly, honestly
Unless it hurts my feelings!


Hey!
Hey!
Hey!
Hey!
Uh""",
    },
    "LCD_05": {
        "title":  "Someone Great",
        "artist": "LCD Soundsystem",
        "lyrics": """I wish that we could talk about it
But there, that's the problem
With someone new, I couldn't start it
Too late for beginnings
The little things that made me nervous
Are gone in a moment
I miss the way we used to argue
Locked in your basement


I wake up and the phone is ringing
Surprised, as it's early
And that should be the perfect warning
That something's the problem
To tell the truth, I saw it coming
The way you were breathing
But nothing can prepare you for it
The voice on the other end, end


The worst is all the lovely weather
I'm stunned it's not raining
The coffee isn't even bitter
'Cause then, what's the difference?
There's all the work that needs to be done
It's late for revision
There's all the time and all the planning
And songs to be finished


And it keeps coming, and it keeps coming
And it keeps coming 'til the day it stops
And it keeps coming, and it keeps coming
And it keeps coming 'til the day it stops


I wish that we could talk about it
But there, that's the problem
With someone new, I couldn't start it
Too late for beginnings
You're smaller than my wife imagined
Surprised you were human
There shouldn't be this radio silence
But what are the options?


When someone great is gone, when someone great is gone
When someone great is gone, when someone great is gone
When someone great is gone, when someone great is gone
When someone great is gone, when someone great is gone


We're saved for the moment
Yes, we're saved for the moment""",
    },
    "LCD_06": {
        "title":  "North American Scum",
        "artist": "LCD Soundsystem",
        "lyrics": """Oh, oh, oh
Oh, oh, oh, oh
Oh, oh, oh
Oh, oh


Oh, I don't know, I don't know, oh, where to begin
We are North Americans
And for those of you who still think we're from England
We're not, no
We’ve been on planes and on trains 'til we think we might die
Far from North America
Where the buildings are old and you might have lots of mimes
Uh-huh, oh, oh
I hate the feelin' when you're lookin' at me that way
'Cause we're North Americans
But if we act all shy, it'll make it okay
Makes it go away
Oh, I don't know, I don't know, oh, where to begin
When we're North American
But in the end, make the same mistakes all over again
Come on, North Americans


(Ah-ah) Oh, oh, oh, oh
We are North American scum
(Ah-ah) Oh, oh, oh
We're from North America


And all the kids, all the kids don’t wanna make a scene
Here in North America
When all your kids get to read it in your magazines
We don't have those
So where's the love? Where's the love? Where's the love?
Where's the love? Where's the love, tonight?
But there's no love, man, there's no love when the kids are uptight
Uh, uh
So throw a party ‘til the cops come in and bust it up
Let's go, North Americans
Oh, you were planning it? I didn't mean to interrupt
Sorry
I did it once and my parents got pretty upset
Freaked out in North America
But then I said, "The more I do it, the better it gets"
That's my North America


(Ah-ah) Oh, oh, oh, oh
We are North American scum
(Ah-ah) Oh, oh, oh
We're from North America
(Ah-ah) Oh, oh, oh, oh
We are North American scum
(Ah-ah) Oh, oh, oh
We are North American


New York's the greatest if you get someone to pay the rent
Wahoo, North America
And it's the furthest you can live from the government
Uh-huh, huh
Some fat American Christians might disagree
Here in North America
But New York's the only place we keep them off the street
Ooh, ooh
Now, we can't have parties like in Spain where they go all night
Shut down in North America
Or like Berlin where they go another night, alright
Uh-huh, uh-huh
You see, I love this place that I've grown to know
Alright, North America
And yeah, I know you wouldn't touch us with a ten-foot pole
'Cause we're North Americans


(Ah-ah) Oh, oh, oh, oh
We are North American scum
(Ah-ah) Oh, oh, oh
We are North Americans
(Ah-ah) Oh, oh, oh, oh
We are North American scum
(Ah-ah) Oh, oh, oh
We love North America


(Ah-ah) Take me back to the states, man
North American scum
(Ah-ah) Where we can be in any one of a million new bands
North America
(Ah-ah) Where the DJ gigs aren't as fun
Here in North American scum
(Ah-ah) But don't blame the Canadians
Look out, North America""",
    },
    "LCD_07": {
        "title":  "Call the Police",
        "artist": "LCD Soundsystem",
        "lyrics": """We all, we all, we all, we all know this is nothing
We all, we all, we all, we all know this is nothing
We all, we all, we all, we all know this is nothing
This is nowhere
We all, we all, we all, we all know this is nowhere
There is no one
Here

It moves like a virus and enters our skin
The first sign divides us, the second is moving to Berlin
But that's not the state I'm in
The air is thin but that's not the state

The old guys are frightened and frightening to behold
The kids come out fighting and still doing what they're told
But you're waking a monster that will drive you from your hoary holes of gold
And your body will get cold

And we don't waste time with love
It's just death from above

Your head is on fire, your hands are getting weak
We all, we all get stupid in the heat
You've basted your brains with the shatter and the speed and defeat up on the street
And this is nowhere

The early years were boring
The quiet, unhappy punk
See mother was a cripple and my father was a drunk but gentle man
So we do the best we can

This is the plan
Wear your makeup like a man

'Cause we don't waste time with love
Yeah, we don't waste time with love
It's just a push and a shove

Well, there's a full-blown rebellion but you're easy to confuse
By trigger kids and fakers and some questionable views
Oh, call the cops, call the preachers!
Before they let us and they lose
When oh, we all start arguing the history of the Jews
You got nothing left to lose
Gives me the blues

And we don't waste time with love
And we don't waste time with love

So call the police
Yeah, call the police
Yeah, call the police
Yeah, call the police
Go, call the police
Go, call the police
Just text the cops
Yeah, call the police
You're crazy, man
Yeah, call 'em up
Just call the police
The first in line
They're gonna eat the rich""",
    },
    "LCD_08": {
        "title":  "American Dream",
        "artist": "LCD Soundsystem",
        "lyrics": """Wake up with somebody near you
And at someone else's place
You took acid and looked in the mirror
Watched the beard crawl around on your face
Oh, the revolution was here
That would set you free from those bourgeoisie
In the morning everything's clearer
When the sunlight exposes your age


But that's okay
And that's okay


Grab your clothes and head to the doorway
If you dance out, no one complains
Find the place where you can be boring
Where you won't need to explain
That you're sick in the head and you wish you were dead
Or at least instead of sleeping here you prefer your own bed, come on
You just suck at self-preservation
Versus someone else's pain


So you feel drained
And insane
And insane


He was leather and you were screaming
Swinging chains against the stage
And you couldn't know he was leaving
But now more will go with age, you know
So get up and stop your complaining
You know that you're the only one who's been destroying all the fun
Look what happened when you were dreaming
Then punch yourself in the face
So you kiss and you clutch but you can't fight that feeling
That your one true love is just awaiting your big meeting
So you never even asked for names
You just look right through them as if you already came


It's a drug of the heart and you can't stop the shaking
'Cause the body wants what it's terrible at taking, oh
And you can't remember the meaning
But there's no going back against this California feeling


Dream
(sha-bang, sha-bang)
American dream
(sha-bang, sha-bang)
American dream
(sha-bang, sha-bang)
American dream
(sha-bang, sha-bang)""",
    },
    "LCD_09": {
        "title":  "Oh Baby",
        "artist": "LCD Soundsystem",
        "lyrics": """Oh baby
Oh baby
You're having a bad dream
Here in my arms


Oh sugar
You came to me
Could all be a bad thing
Doing you harm
Oh oh oh


Oh lover
You run from me
We move like a bad scene
Shot in the dark


Oh, but please
Please wake me
But my love lies patiently
Please baby, please
And my love life waits for me


Oh love
You came to me
You were having a bad time
There in your home


Oh sugar
Give in to me
You're just having a bad dream
Ringing alarms


Oh, but please
Please shake me
But my love sits patiently
Please, baby, please
And my love plays wait and see


Oh, I'm on my knees
Yeah, I'm on my knees
I promise I'm clean
But my love life waits


And you're already gone
Yeah, you're already gone
You're already home
And my love life stumbles on


Oh baby
Lean into me
There's always a side door
Into the dark
Into the dark""",
    },
    "LCD_10": {
        "title":  "Tonite",
        "artist": "LCD Soundsystem",
        "lyrics": """Everybody's singing the same song
It goes "tonight, tonight, tonight, tonight, tonight, tonight"
I never realized these artists thought so much about dying

But truth be told we all have the same end
Could make you cry, cry, cry, cry, cry
But I'm telling you
This is the best news you're getting all week

Oh sure it's ruling the airwaves
Or what remains of the airwaves
And we're frankly thankful for the market psychology you're hipping us to

And all the hits are saying the same thing
There's only tonight, tonight, tonight, tonight, tonight, tonight
And life is finite
But shit, it feels like forever
It feels like forever

Oh is everybody feeling the same stuff?
We're all wild
Except for you
And you know who you are
This is a love song

And you're getting older
I promise you this; you're getting older
And there's improvements unless
You're such a winner
That the future's a nightmare
And there's nothing I can do
Nothing anyone can do about this

And oh, I'm offering you a chance to get even
But oh, you know very well the dialect of negation
Sure enemies haunt you with spit and derision
But friends are the ones who can put you in an exile
But that's not right

And you're too sharp to be used
Or you're too shocked from being used
By these bullying children of the fabulous
Raffling off limited edition shoes

And what's it you do again?
Oh I'm a reminder
The hobbled veteran of the disk shop inquisition
Set to parry the cocksure of mem-stick filth
With my own late era middle-aged ramblings
Every lover favors the same things
It's all "touch me, touch me, touch me, touch me tonight"
We maybe realize what it is we need before we die

And luck is always better than skill at things
We're flying blind
Oh good gracious
I sound like my mom

But out of the little rooms and onto the streets
You've lost your internet and we've lost our memory
We had a paper trail that led to our secrets
But embarrassing pictures have now all been deleted
By versions of selves that we thought were the best ones
'Til versions of versions of others repeating
Come laughing at everything we thought was important
While still making mistakes that you thought you had learned from
And reasonable people know better than you
That cost in the long run but they don't know the short game
And terrible people know better than you
The use and abuse of the wants of dear listener
So you will be badgered and taunted and told that
You're missing a party that you'll never get over
You hate the idea that you're wasting your youth
That you stood in the background oh until you got older
But that's all lies
That's all lies

It's gonna have to be good enough, I can't do this anymore, my brain won't work""",
    },
    "LCD_11": {
        "title":  "Change Yr Mind",
        "artist": "LCD Soundsystem",
        "lyrics": """I ain't seen anyone for days
I still have yet to leave the bed
It's impossible
Feeling safe with it now
I'm impossible
Getting used to it now

I've just got nothing left to say
I'm in no place to get it right
And I'm not dangerous now
The way I used to be once
I'm just too old for it now
At least that seems to be true

I have a penny for your thoughts
If you could keep them to yourself
About you slipping away
I feel you slipping away
Don't want to hear it all now
Of how I'm slipping away

I can't make you a promise
We're not professionals
But if you don't like what it feels like
And if you don't
Don't like where it's been
It could be over if you change your mind
If you change your mind
If you change your mind
If you change your mind
If you change your mind
If you change your mind
You can change your mind
You can change your mind""",
    },
    "LCD_12": {
        "title":  "How Do You Sleep?",
        "artist": "LCD Soundsystem",
        "lyrics": """Standing on the shore, facing east
I can't feel you

Standing on the shore, facing east
Your impermanence
You're taking water
Listing lazily out of view

I remember when we were friends
I remember calling you friend

Standing on the shore my ear aimed east
I can't hear you
I can't hear you anymore
I can't hear you
I can't hear you anymore

I still remember
Laughing and fighting
I still remember

Standing on the shore, watching for you
You're painted into a corner
Whatever fits in your pockets; you'll get your due
Just like before
With all the others

You warned me about the cocaine
Then dove straight in
Yeah, you warned me about the cocaine
Then dove straight in

In hiding, where there's more for you
There's more for you
There's more for you
There's more for you
There's more for you
There's more for you
There's more for you
There's more for you
There's more for you
There's more for you
There's more for you
There's more for you
There's more for you
There's more for you
There's more for you
There's more for you
There's more for you
There's more for you
There's more for you
There's more for you

Standing on the shore, getting old
You left me here
Amid the vape clouds

I must admit, I miss the laughing
But not so much you

One step forward
One step forward
One step forward
And six steps back
And six steps back
And six steps back
And six steps back
And six steps back
And six steps back
And six steps back
And six steps back

Standing on the floor, facing you
I can't see you, your impermanence
This place is empty
Empty of you

And if I see you, it's like nothing went wrong
Yeah, if we meet again tomorrow
It's just like nothing went wrong

But there I go
Erasing our chances
Just by asking
"How do you sleep?"
(One step forward
One step forward
One step forward)

And six steps back
And six steps back
And six steps back
And six steps back
And six steps back
And six steps back
And six steps back
And six steps back""",
    },
}
