# Auto-generated by 03_build_schema.py — do not edit manually.
# Artist: Tyler, the Creator  |  Code: TC2
# Songs included: 12  |  Missing: 0

TC2_SCHEMA = {
    "TC2_01": {
        "title":  "See You Again",
        "artist": "Tyler, the Creator",
        "lyrics": """Okay, okay, okay, okay, okay, okay, o—


You live in my dream state
Relocate my fantasy
I stay in reality
You live in my dream state
Any time I count sheep
That's the only time we make up, make up
You exist behind my eyelids, my eyelids
Now, I don't wanna wake up


20/20, 20/20 
visions
Cupid hit me, Cupid hit me with 
precision, I
Wonder if you look 
both ways 
when you cross 
my mind
 (Yeah)
I said, I said
I'm 
sick of, sick of, sick of, sick of chasing
You're the one that's always running through my 
daydream, I
I can only see 
your face
 when I close 
my eyes
(Uh-huh)


Can I get a kiss? (
Ah
)
And can you make it last forever? (
I said
)
I said I'm 'bout to go to war (
Uh-huh
)
And I don't know if I'ma see you again
Can I get a kiss? (Can I?)
And can you make it last forever? (Can you?)
I said I'm 'bout to go to war ('Bout to)
And I don't know if I'ma see you again
Ayy, switch it up


I said (Oh), okay, okay, okay (Oh), okey-dokey, my infatuation (Woo)
Is translatin' to another form of, what you call it? (Love)
(Oh) Oh, yeah, oh, yeah, oh, yeah (Oh), I ain't met you, I've been lookin' (Woo)
Stop the waitin' 'fore I stop the chasin', like a alcoholic
"You don't understand me"  – What the fuck do you mean?
It's them rose-tinted cheeks, yeah, it's them dirt-colored eyes (Yeah) (Woo)
Sugar-honey iced tea, bumblebee on the scene
Yeah, I'd give up my bakery to have a piece of your pie
Ugh


20/20, 20/20 
visions
Cupid hit me, Cupid hit me with 
precision, I
Wonder if you look 
both ways 
when you cross 
my mind
I said, I said
I'm 
sick of, sick of, sick of, sick of chasing
You're the one that's always running through my 
daydream, I
I can only see 
your face
 when I close 
my eyes
So


Can I get a kiss? (Can I get a kiss?)
And can you make it last forever? (Make it last forever)
I said I'm 'bout to go to war ('Bout to go to war)
I don't know if I'ma see you again (See you again)
Can I get a kiss? (Can I?)
And can you make it last forever? (Can you?)
I said I'm 'bout to go to war ('Bout to)
And I don't know if I'ma see you again


Okay, okay, okay, okay, okay, okay, okay, o—
(
La-la-la, la-la-la-la
)
Okay, okay, okay, okay, okay, okay, okay, o—
(
La-la-la, la-la-la
)
Okay, okay, okay, okay, okay, okay, okay, o—
(
La-la-la, la-la-la-la
)
Okay, okay, okay, okay, okay, o—
(
La-la-la, la-la—
)
One more time?""",
    },
    "TC2_02": {
        "title":  "EARFQUAKE",
        "artist": "Tyler, the Creator",
        "lyrics": """For real, for real this time
For real, for real, for real this time
Bitch, I cannot fall short
For real, for real, for real this time (Uh, yeah)
For real, for real, for real this time


'Cause you make my earth quake
Oh, you make my earth quake
Riding around, your love be shakin’ me up
And it's making my heart break
'Cause you make my earth quake (Earthquake, ooh)
Oh, you make my earth quake
Riding around, your love be shakin’ me up
And it's making my heart break


Don't leave, it's my fault
Don't leave, it's my fault
Don't leave, it's my fault (Girl)
’Cause when it all comes crashing down, I’ll need you


'Cause you make my earth quake
Oh, you make my earth quake
Riding around, you’re telling me something is bad
And it's making my heart break
'Cause you make my earth quake
Oh, you make my earth quake (
Earthquake, yeah
)
Riding around, your love be shakin' me up
And it’s making my heart break (
You already know
)


We ain't gotta ball, D-Rose, huh
I don't give a fuck 'bout nothin', huh
Breathin' like fuck my lungs, huh
Just might call my lawyer, huh
Plug gon' set me up, huh (Yeah)
Bitch, don't set me up (Okay)
I'm with Tyler, yeah (Slime)
He ride like the car, huh
And she wicked, huh, yeah
Like Woah Vicky, huh, yeah (Like Woah Vicky)
Oh my God, hold up, um
These diamonds not Tiffany, huh, yeah (Woah, woah)
So in love (I been so in love)
So in love (I been so in love)


Don't leave, it's my fault (Fault)
Don't leave, it's my fault
Don't leave, it's my fault (Igor, ayy)
'Cause when it all comes crashing down, I'll need you (Ayy, ayy)


'Cause you make my earth quake
I don't want no confrontation, no
And you don't want my conversation (
I don't want no conversation
)
I just need some confirmation on how you feel, for real (
For real
)
You don't want no complication, no
I don't want no side information (I don't want no side information)
I just need to know what's happening 'cause I'm for real (For real)


I said don't leave, it's my fault (One)
I said don't leave, it's my fault (Two, two)
Don't leave, it's, it's my fault, girl (Three, three, three)
Don't, do-do-do-do-do, I'll need—""",
    },
    "TC2_03": {
        "title":  "Enjoy Right Now Today",
        "artist": "Tyler, the Creator",
        "lyrics": """One, two, three, four""",
    },
    "TC2_04": {
        "title":  "I THINK",
        "artist": "Tyler, the Creator",
        "lyrics": """(Four, four, four, four)
(Four, skate, four, skate, four, skate, four, skate)


I don't know where I’m going (Skate)
But I know what I'm showing (Four)
Feelings, that's what I’m pouring (Skate)
What the fuck is your motive? (Four)
Man, I wish you would call me (Skate)
By your name 'cause I'm sorry (Four)
This is not apology (Skate)
You are such a distraction (Four)
That's what T on, aw (Skate)
Fuckin' up my ambiance, pause (Four)
You drive me cuckoo and not car (Skate)
'Cause I want you like Leon Ware (Fuck that)
Okay, say again it (Fuck that)
Okay, wait a minute (Woah)
I dread that shit, I am Anwar (Skate)
Curiosity killed the feline, gone (Four, skate)


I think I've fallen in love (Skate)
This time I think it's for real (Four, skate)
I think I’ve fallen in love (Four, skate)
This time I think it’s for real
 (Four)
How can I tell you? (Skate) How can I tell you? (Four)
How can I tell you? (Skate) How can I tell you? (Four)
How can I tell you? (Skate) How can I tell you? (Four)
How can I tell you? (Skate) How can I tell you? (Four)


I notice that you're there, but I’m always in your hair
And you're always under my microscope (Four)


Waste of bread, I need your attention (Skate)
I'm off balance, I need some fixin' (Four)
I’m your puppet, you are Jim Henson (Skate, four)


Fallen in love now (Skate)
I think I've fallen in love
 (Four)
Fell in love now (Skate)
This time I think it's for real
 (Four)
I think I'm in love now (Skate)
I think I've fallen in love (Four)
I think I'm in love now (Skate)
This time I think it's for real (Four, four)
How can I tell you? (Shut the fuck up)
How can I tell you? (Four)
How can I tell you? (You fuckin' bitch)
How can I tell you? (Four)
How can I tell you? (Skate)
How can I tell you? (Four)
How can I tell you?
Take 'em to the bridge


(Four, four, four)
Four, four, four, four (Four, skate)


I think I've fallen in love
 (Four)
Fell in love now (Skate)
This time I think it's for real
 (Four)
I think I'm in love now (Skate)
I think I've fallen in love
 (Four, skate)
This time I think it's for real (Oh, oh, yeah, yeah)


(Four, skate, four, skate)""",
    },
    "TC2_05": {
        "title":  "NEW MAGIC WAND",
        "artist": "Tyler, the Creator",
        "lyrics": """Sometimes you gotta close a door to open a window


I saw a photo, you looked joyous
My eyes are green, I eat my veggies
I need to get her out the picture
She's really fuckin' up my frame
She's not developed like we are


Like magic, like magic, like magic, gone
New magic, new magic, new magic wand (Ayy)
Like magic, like magic, like magic, gone (Gone, nigga)
New magic (Woo), new magic, new magic wand


My buddy said I'm on the spectrum
Don't call me selfish, I hate sharin'
This 60-40 isn't workin'
I want a hundred of your time, you're mine


Please don't leave me now
Please don't leave me now (
Don't leave
)
Please don't leave me now
Please don't leave me now (
Don't leave
)
Please don't leave me now (
Don't leave
)
(Like magic, like magic, like magic, gone)
Please don't leave me now (I can make her leave)
(New magic, new magic, new magic wand)
Please don't leave me now (
Don't leave
)
(Like magic, like magic, like magic, gone)
Please don't leave me now
(New magic, new magic, new magic wand)


I wanna be found, passenger in your car (
Don't leave
)
You wanna give me mixed signals, don't park (I can make her leave)
She's gonna be dead, I just got a magic wand (
Don't leave
)
We can finally be together


You roll the dice, hit a seven, sure you right
Beginner's luck? You not my first, who gives a fuck?
Your other one? Evaporate, we celebrate
You under oath, now pick a side and if you don't
(Run, run, run, run)
I'll pick you both
(Run, run, run, run)
It's not a joke, murder she wrote


Ayo, take one look in the mirror, implications so clear
I live life with no fear, except for the idea
That one day you won't be here
I will not fetch the ball
Eyes are green, I eat my vegetables
It has nothin' to do with that broad
But if it did, guarantee she'd be gone, well
I got a plan, but the walkin' depends
If you can't understand, I'm a hawk in the gym
Eyes on the prize, got weight on my chest
That I need to get off, I ain't talkin' to them
Can't be in the picture if it got no frame
And let the world know 'cause I ain't got no shame
Blow the whole spot up, 'cause I ain't—
I wanna share last names, I wanna be your number one
Not the other one, keep it on the low
I'm in my right mind, keep it on a high
Janis Joplin spillin' feelings, now I'm out here moppin' 'em
Four on the floor, pack up your bags, we hit the store
Grab our supplies, no need for masks, bust through the door
Get the job done like retirement, I admit you look concerned
New magic wand""",
    },
    "TC2_06": {
        "title":  "WUSYANAME",
        "artist": "Tyler, the Creator",
        "lyrics": """Something real, yeah
Baby
Oh nah, we don't do backpack
Haha, my pick up line and shit
Yeah, yeah, yeah, yeah, yeah
I got your bitch movin'
Call me when you get lost


Aw, you look malnourished (
Malnourished
)
Let's get some bread, fry it in egg yolk and drown it in syrup (
Drown it in syrup
)
You pick a spot, I pick a tail number and we could be tourists (
Ooh, yeah
)
Let's go to Cannes and watch a couple indie movies that you never heard of (
Baby
)
Listen to bands, groove and we dance
Disco in France, smell some perfume, head in the wind (In the wind)
We can switch off
I can show you how you can really exfoliate skin
If you got a man, you should cut it off
Get your passport 'cause we runnin' off (Run off)
We can sit and talk
You can tell me everything that's on your chest, baby, get it off
You are my type, you a bright light
I'm like a moth, this is not a game (
This is not a game
)
But before we start (Before I say)


What's your name, girlfriend, what's your name? (Check it out)
(What's your name?)
What's your name, girlfriend, what's your name? (Tell me)
What's your name, girlfriend, what's your name? (Check it out)
(Oh, what's your name?)
What's your name, girlfriend, what's your name? (Oh, girl)
Yeah


What is your name, what do you bring? (Yeah)
I think that I got what you need
And I'm willin' to do anything that you please (Baby)
I'm tryna get down to the root of the apple
The deepest I could in them jeans
McLaren like Sonic, can't speak, no
No, you can't hit my lean, no (Baby)
Baby, tell me where the piece go, 'cause I'm lost
Your body compared to the fashion
I hope you ain't proud of the shit that I bought (
Baby
)
'Cause money, it don't mean a thing
I value the times that I take you out
One minute, it's a beautiful scene
Then it probably end with me bein' took out, woah-oh
Think slow, 'cause I move fast (Oh, me)


What's your name, girlfriend, what's your name? (Check it out)
(Oh, what's your name?)
What's your name, girlfriend, what's your name? (Tell me)
What's your name, girlfriend, what's your name? (Tell me)
(Oh, what's your name?)
What's your name, girlfriend, what's your name? (Yeah)
(Oh-oh)
Yeah


Since when did I bring a C5?
I wanna know your name
I feel like I had your name
Oh-oh, oh, oh, ooh, ooh
Stop playin' and let me pay your momma debt off, haha""",
    },
    "TC2_07": {
        "title":  "Lumberjack",
        "artist": "Tyler, the Creator",
        "lyrics": """Rolls-Royce pull up, Black boy hop out
Shoutout to my mother, and my father didn't— (
Hold up
)
"Oh, my God, I never seen nothin' like this"
Haha, that's what my mom was sayin'
She, she was cryin' and shit
It was, she was just like, "This shit is beautiful"
It was a beautiful moment
You alway– you always keep the picnic blankets in the back
'Cause you, you never know (
Gangsta Grillz
)
You never know where the fuck you gon' end up at
(Okay, haha, let's go, now we ready)


Rolls-Royce pull up, Black boy hop out
Shoutout to my mother, and my father didn't pull out
MSG sell out, fuck these niggas yap 'bout?
Whips on whips, my ancestors got they backs out (
Yeah, oh
)
Too far? Five hundred stacks for the hood (I dare you, nigga)
Call me lumbеrjack 'cause I wish a nigga would race (Uh-huh, 
right)
Do it like I? This thе wish-a-nigga-could face (Uh)
They ain't gettin' paper like they should, wait
(You niggas woulda, coulda, shoulda, oh, shit)


Niggas ain't really on the type of shit he on
I hit Drizzy and told him I had a milli' for him (
Oh shit
)
I own my companies full, told 'em to keep the loan
I took that gold bitch home, niggas was big mad (Ugh, 
oh shit
)
I put that bitch on the shelf to let it ventilate
And bought another car 'cause I ain't know how to celebrate (
Top shelf, nigga
)
That big boy, that big bitch for all weather
It never rain in Cali', came with an umbrella (
Ooh
)


Rolls-Royce pull up, Black boy hop out (
Man, what the fuck?
)
Shoutout to my mother, and my father didn't pull out
MSG sell out, fuck these niggas yap 'bout? (
Sold out
)
Good credit score, this card really can't max out (
Wow
)
Too far? Five hundred stacks for the hood
Call me lumberjack 'cause I wish a nigga would race (Uh-huh)
Nigga this the face, man I wish a nigg— (It's the face)
It's different, it's really different (Catch up, niggas)


Ayo, I might just sled in Utah, LA is too warm
My nigga tall, he look like a bitch, I call him Mulan (
Hey, oh
)
Salad colored emerald on finger, the size of croutons
Niggas can not fuck with performance of magic (
Oh
), new wand (
Nigga
)
That's my nuance, used to be the weirdo (Ah)
Used to laugh at me, listen to me with their ears closed
Used to treat me like that boy off Malcolm in the Middle  (
Why I'm motherfuckin' rich
)
Now I'm zero, zero, zero, zero, zero, zero (
That's six
)


Rolls-Royce pull up (Zero), Black boy hop out (
That's seven
)
Nah, I can't take this shit no more, man, I quit
That's it, I quit, I swear to God, nigga
Fuck niggas talking to me about? Close y'all fuckin' faces
Quality Wednesday music
Wish-a-nigga-could face
(Them stones is cloudy, nigga) Oh yeah, you asked for it
(Fuckin' crumbs) Wish-a-nigga-would face
Fuck you mean, nigga?""",
    },
    "TC2_08": {
        "title":  "911 / Mr. Lonely",
        "artist": "Tyler, the Creator",
        "lyrics": """(Call me, call me, call me) Uh
(Call me, call me, call me) Uh
(Call me, call me, call me) Ah
(Call me, call me, call me)
(Call me) How you doin'?
(Call me) My name is Lonely, nice to meet you
Here's my number
You can reach me, woo!


(Call me)
911, call me some time
(You should call me)
911, call me some time
911 (You should call me, oh)
911 (Call me)


Aw, yeah, yeah, yeah, yeah
My thirst levels are infinity and beyond
Sippin' on that lemonade, I need a Beyoncé
Can't see straight, these shades are Céline Dion (Woo)
Sucks you can't gas me up, shout out to Elon
Musk, yeah, I got a sold-out show
Crowd wild out but don't matter 'cause you not front row
I've been lookin' for a keeper, listen to the speaker
If you fit description, hit me on my beeper
At that 911


Call me some time (
Yeah;
 
ring, ring, ring
)
Please bang my line, you know I'll answer (
Click
)
Call me some time (
Ring, ring, ring
)
Please bang my line


Call me
911, call me some time
You should call me
911, call me some time
911 (
You should call me, oh
)
911, (
You should call me
)


Chirp, chirp (Yeah)
Chirp, chirp
Woke up in the 'burbs, 'burbs, with the birds, birds
Where you used to come and get me with the swerve, swerve
These days, you gotta find time
Even the nightline
Work line
Dial nine


Five car garage
Full tank of the gas
But that don't mean nothin', nothin'
Nothin', nothin', without you shotgun in the passenger
I'm the loneliest man alive
But I keep on dancing to throw 'em off
I'm gon' run out of moves 'cause I can't groove to the blues
If you know any DJs, tell 'em to call me at 911...




I can't even lie, I've been lonely as fuck
Old lonely-ass nigga
I can't even lie, I've been lonely as fuck
For real, you need to go somewhere, like, get some bitches or something
I can't even lie, I've been lonely as fuck
Old weird ass nigga
I can't even lie, I've been
Lonely, lonely, lonely, lonely


They say the loudest in the room is weak
That's what they assume, but I disagree
I say the loudest in the room
Is prolly the loneliest one in the room (That's me)
Attention seeker, public speaker
Oh my God, that boy there is so fuckin' lonely (Woo)
Writin' songs about these people
Who do not exist, he's such a fuckin' phony (Woo)
One thing I know is that I wanna
Win so bad, but I'm not Chicago
My heart is low, it's real low, it's so low
You can't lift me up, I'm like Gallardo
From the start, it's been real dark
It's been so dark, I guess that you could call me charbroiled, huh (Hahaha)
I'm playin' like Hasbro
I'm really Saari, call me Arto
Crashed the McLaren, bought me a Tesla
I know you sick of me talkin' 'bout cars (Skrrt)
But what the fuck else do you want from me?
That is the only thing keepin' me company
Purchase some things until I'm annoyed
These items is fillin' the void (Void)
Been fillin' it for so long
I don't even know if it's shit I enjoy (Ohh, woo)
Current battle as an adult
My partner is a shadow
I need love, do you got some I could borrow?
Fuck it, I could find some tomorrow
But that never comes (Nah)
Like a vasectomy, what have I done? (
Ohh
)
I got the talent, the face and the funds
Found myself long ago but I haven't found someone (Who)
Mirror, mirror on the wall (Who)
The loneliest of them all (Me)
Cupid actin' stupid
Do you got another number I could call?
Never had a pet
(I never had a pet)
There's more fish in the sea
But I never had a goldfish to begin with
I never had a dog
So I've never been good with bitches
'Cause I never threw a ball, fetch
I never had a pet, that's where it stems from, I bet
Treat me like direct deposit (-Posit)
Check in on me sometime (Okay)
Ask me how I'm really doin'
So I never have to press that 911


Oh
Oh, shit
Fuck
Oh
Shit
Oh
Damn, damn""",
    },
    "TC2_09": {
        "title":  "Who Dat Boy",
        "artist": "Tyler, the Creator",
        "lyrics": """Yo, who dat boy? Who him is?
Him that ni-gga, I swear
Stand out guy, him don't need no chair
Well, where the fuck him at? 'Cause nigga, I'm right here
I don't shop at the mall, all y'all just
Dumb mothafucka, I'm a goddamn artist
You can give me some markers and I'll draw you a closet
And you know that it's GOLF, bitch, gonna make the deposit
Nigga fresh to death like he got dressed in a coffin
Cons, overalls, and a striped shirt
The boy drips swag like a broken faucet
It's runnin', nigga, I'm runnin' shit
That cherry be the bomb like he ran in Boston
Won't stop 'til the cops surround him
One nigga jiggy and the other awesome
With his fuckin' face blown off, that's how they found him
It's Young T


Who dat boy? Who him is?
Who dat boy? Who him is?
Nigga, who dat boy? Who him is?
Who dem boys? Nigga, who dem is, nigga?
Why you niggas feel like that?
Mad 'cause a nigga neck chill like that
You mad 'cause a nigga push wheel like that?
Why you puttin' bad vibes in the air like that?


Nigga, who dem boys? (Who dem is?)
Nigga, who dem is?
Who else step in this bitch this jig?
Who else your bitch say got a bick this big?
Who else came through with a wrist this flick?
Nigga, Guess my pants, do my dance
Spin around, bitch, you could kiss my ass
Never seen a nigga in this much Raf
Still doin' math when I miss my class
Was it Summertime '06, had the Number (N)ine
Nigga, never mind, was another time before Vince
Had the Gucci gold tips with the letterman
Nigga, dollar sign was my favorite number at the time
Fresh freshmen 'til they skipped my ass
Senior citizen, don't forget my pass
Been that nigga and you knew that there
Make the dick disappear, how she do that there?


Who dat boy? Who him is?
Who dat boy? Who him is?
Nigga, who dat boy? Who him is?
Who dem boys? Nigga, who dem is, nigga?
Why you niggas feel like that?
Mad 'cause a nigga neck chill like that
You mad 'cause a nigga push wheel like that?
Why you puttin' bad vibes in the-?


Fuck the rap, I'm tryna own a planet
From my other fuckin' business ventures
These niggas these days
Actin' like some bitches, like they're fuckin' with ya (yeah)
Teeth is glistenin', Jesus, ChristmasHe just shittin', she exquisite, bitches be expensive
(Yeah, let 'em know, nigga) And I don't even need attention
WANG$AP on the bumper sticker, fuck you niggas
Fuck global warming, my neck is so frío
I'm currently lookin' for '95 Leo
My mom say she worried because I'm so ill
I should stay in bed, but got too much bread
To make, she said watch my weight
So I stayed home and start eatin' some meals
Get out of my way güey, boy, that's McLaren
That's 0 to 60 in 2 point nueve, I'm gone


Oh, fuck""",
    },
    "TC2_10": {
        "title":  "Gone Gone / Thank You",
        "artist": "Tyler, the Creator",
        "lyrics": """Comparing scars before dinner
Jump off the roof into the mirror
Felt like summer to my December
Was it my August? Shit, I don't remember
(Two, three, go)
I know my temperature was set
You finally flew south
The bird gon' leave the nest, you're so chromatic
At least I had it (Uh)
Instead of never
Or maybe I'm too dramatic
(Two, three, go)


Whether it's rain or shine, I know I'm fine for now
My love's gone, my love's gone
My love's gone, oh, gone
(Two, three, go)
Or maybe it's just a dream that I can't seem to wake up from
My love's gone, my love's gone
My love's gone, gone


Gone, gone, gone, gone, gone


I know love is, is all I got
I just hope to God she got good taste
Could put you on some shit you never seen
Could play a couple songs that you could dance to
I hope you know she can't compete with me


Whether it's rain or shine, I know I'm fine for now
My love's gone, my love's gone
My love's gone, oh, gone
Or maybe it's just a dream that I can't seem to wake up from
My love's gone, my love's gone
My love's gone, oh, gone


You kept me goin', the Band-Aid is falling off now (Keep)
You kept me goin', the Band-Aid is falling off now (Keep)
You keep me goin', the Band-Aid is falling off now (Gone, gone, gone)
Going away, and now I'm scarred for life


My love is gone (Gone), my love is gone (Gone)
My love is gone (It's gone), my love is gone


Ayo (My love is gone)
It's poison in that gumbo
Emotion, feel Dumbo
Ask me where my love go
That bitch walked outside the front door (
My love is gone
)
Knock, knock, knock, knock (Who is it?)
I'm not shocked, I brought this on me
It's my fault, you gon' leave
Lesson taught, see
The weatherman told me it wasn't rainin'
My stupid ass brought umbrellas
I got a glimpse of your cloud and felt better
Now it's 90 degrees, and all the tricks up my sleeve
Is drenched in sweat and delusion because I jet to conclusions
You got your thing, I got nothing but memories
I know your secrets, nigga (Yeah)
I'm not bitter or nothing, I understand that
Everybody making a choice according to plan and
We had two different blueprints, but understood influence
You opened up early on, I thought I had a permit
You started buildin' a bridge and turned it into a fence
Then my buildin' got tore down all because of your new tenant
I'll just buy up some new shit, never down with a lease
You never lived in your truth, I'm just happy I lived in it
But I finally found peace, so peace
(Need me to do it over? Everything)


I hate wasted potential, that shit crushes your spirit
It really does, it crushes your soul




Thank you for the love
Thank you for the joy
But I don't ever wanna fall in love again
Thank you for the time
Thank you for your mind, mind
But I don't ever wanna fall in love again


(Got my eye)
I said go, go


Thank you for the love
Thank you for the joy
But I don't ever wanna fall in love again
Thank you for the time
Thank you for your mind, mind
But I don't ever wanna fall in love again


Again, again
Again, again
(Got my eye)""",
    },
    "TC2_11": {
        "title":  "Foreword",
        "artist": "Tyler, the Creator",
        "lyrics": """Bitch, fuck! (Uh, uh, fuck)
You have a question?


How many cars can I buy 'til I run outta drive?
How much drive can I have until I run outta road?
How much road can they pave until I run outta land?
How much land can it be until I run in the ocean?
Niggas go with the motions and all the plans
See, I was never into the beaches and all the sands
See, I was in the woods with flowers, rainbows, and posies
Fallin' outta my pocket, but y'all want to know if I swam to cool down
How much cooler can I get until I run out of fans?
How many fans can I have until they turn on the AC?
If the AC blow up, well then I'm TNT, I'm gone


I'm gone and I'm finished
And I ain't seen my friends in a minute
Guessing nothing lasts forever
Yeah, nothing lasts forever
Nothing sticks together
Sick of sitting in doubt
Please let me figure this out, out


Shout out to the girls that I led on
For occasional head and always keepin' my bed warm
And tryin' their hardest to keep my head on straight
And keepin' me up enough 'til I had thought I was airborne
How many raps can I write 'til I get me a chain?
How many chains can I wear 'til I'm considered a slave?
How many slaves can it be 'til Nat Turner arise?
How many riots can it be until them Black lives matter?
Niggas click-clack splatter, (Pew) pew that nigga
Life a game of basketball, you better shoot that nigga
'Cause if that cop got trigger, he better pull (Yeah)
'Cause when I get pulled over, I usually play it cool (Skrt)
'Cause I know what I'm drivin' is usually paid in full
And my ego and possessions will not let me be one (Nah)
Because I got a mansion, my mansion got some rooms
Them rooms got some windows and my windows got some views (Yup)
Them views get some stares and my backyard does too
And if you walk to the bottom, you'll prolly see a pool
You better not drown, keep them ten toes up
'Cause if them ten toes down, that mean that you fucked up
And that's what I swim in


And if I drown and don't come back
Who's gonna know? (Maybe then I'll know)
And if I crash and don't come back
Who's gonna know? (Maybe then I'll know)
And if I fall and don't come back
Who's gonna know? (Maybe then I'll know)
I'm wondering if I don't come back
Maybe then I'll know
Don't come back
Don't come back
Ayy, don't come back
Don't come back
No, no""",
    },
    "TC2_12": {
        "title":  "MASSA",
        "artist": "Tyler, the Creator",
        "lyrics": """Whatever your shit is, man, do it
Whatever bring you that immense joy, do that, that's your luxury
The greatest thing that ever happened to me was
Bein' damn near twenty and leavin' Los Angeles for the first time
I got out my bubble, my eyes just wide
My passport is the most valuable—


Massa couldn't catch me, my legs long than a bitch
Got too much self-respect, I wash my hands 'fore I piss
They try to talk me—, ehm, I'ma just go


Yeah, when I turned twenty-three, that's when pubеrty finally hit me
My facial hair started growin', my clothing ain't really fit mе
That caterpillar went to cocoon, do you get me?
See, I was shiftin', that's really why 
Cherry Bomb
 sounded so shifty
My taste started changin' from what it was when they met me
But first impression is everything, ain't wanna let me go
Always curious as a child and askin' questions, so
I ain't give no fucks, if, and, buts if they accept me
Yo, my boy Skateboard P gave me that speech in Italy session, um
Thankfully, by hour three it detoured perspective, um
Thoughts changed so rapid, turned to butterfly, 
Flower Boy
 happened
All the bees buzzed me, the bugs screamed they loved me
First time I private airlined, accolades, song got airtime
Grew into my style, body, and feelings, and fixed my hairline
Calmed down in front of cameras, business hit tens of millions
I'm not that little boy y'all was introduced to at one-nine
Mom was in the shelter when "Yonkers" dropped, I don't say it (I don't say it)
When I got her out, that's the moment I knew I made it (Yeah, yeah)
I don't come from money, they deny it
Since I don't mirror the stereotypical products of my environment
Eight figures in taxes taken, that shit is stupid
A flower gets its petal, they pluck it, but never use it
It's still potholes in the schools, where does it go?
It's still loopholes that I use, nobody knows


Massa couldn't catch me, my legs long than a bitch
Got too much self-respect, I wash my hands 'fore I piss
They try to talk me up, but I keep short like Caesar
Eyes open if I pray 'cause I can't trust God either, uh


Seein' that we only get one life to live
How far do you really wanna take it?
Don't let 'em ever tell you nothin' you can't do


Yeah, I purchase more wheels when I feel like I'm third-wheelin'
My favorite part of the double R is the bird ceilin'
The panoramic view of the sky and the sun beamin'
That ray of light show that nobody is front-seatin'
I'm on the hunt for perfect but decent is what I been on
I know she fell in love, but commitment is not my end goal
And all my friends that did got too comfy, a little chubby
And that drive to make that money dried up when that nose was runny
We ain't gotta pay attention to the stuff that he battles
Everyone I ever loved had to be loved in the shadows
Tug-of-war with X and Y felt like a custody battle
Felt like the boat goin' down, it felt like I'm missin' a paddle
Might buy that crib in Seattle covered in grass, lackin' gravel (Yeah)
It come with two boats and cattle, I'm livin' sweet, ain't you heard? (Ain't you heard, nigga?)
This perspective from the beak of a bird
You hope I peak, you take my peace
You gon' see me and run like thieves in the night
I'm paranoid, I sleep with a gun
The heat on my dungaroos because they beefin' for fun
I'm vegan for now, I'm conscious, know my hands meet when I bow
I'm grateful, you niggas hateful, you eat at me, you got a plate full
You can't relate to these things I say to these instrumentals
Whether it's wealth talk or shit that's painful
I paint full pictures of my perspective on these drum breaks
Just for you to tell me it's not good from your lunch break


Holiday season
A vision you have to understand from perspective
Check your resources, nigga""",
    },
}
