# Auto-generated by 03_build_schema.py — do not edit manually.
# Artist: Tyler Childers  |  Code: TC
# Songs included: 15  |  Missing: 0

TC_SCHEMA = {
    "TC_01": {
        "title":  "Whitehouse Road",
        "artist": "Tyler Childers",
        "lyrics": """Early in the mornin' when the sun does rise
Layin' in the bed with bloodshot eyes
Late in the evenin' when the sun sinks low
That's about time my rooster crows
I got women up and down this creek
And they keep me goin' and my engine clean
Run me ragged but I don't fret
'Cause there ain't been one slow me down, none yet


Get me drinkin' that moonshine
Get me higher than the grocery bill
Take my troubles to the high-wall
Throw 'em in the river and get your fill
We've been sniffin' that cocaine
Ain't nothin' better when the wind cuts cold
Lord, it's a mighty hard livin'
But a damn good feelin' to run these roads


I got people try to tell me, Red
Keep this livin' and you'll wind up dead
Cast your troubles on the Lord of lords
Or wind up layin' on a coolin' board
But I got buddies up White House Road
And they keep me strutting when my feet hang low
Rotgut whiskey gonna ease my pain
An' all this runnin's gonna keep me sane


Get me drinkin' that moonshine
Get me higher than the grocery bill
Take my troubles to the high-wall
Throw 'em in the river and get your fill
We've been sniffin' that cocaine
Ain't nothin' better when the wind cuts cold
Lord it's a mighty hard livin'
But a damn good feelin' to run these roads
It's a damn good feelin' to run these roads


When you lay me in the cold hard clay
Won't you sing them hymns while the banjo plays?
You can tell them ladies that they ought not frown
'Cause there ain't been nothin' ever held me down


Lawmen, women or a shallow grave
Same ol' blues just a different day


Get me drinkin' that moonshine
Get me higher than the grocery bill
Take my troubles to the high-wall
Throw 'em in the river and get your fill
We've been sniffin' that cocaine
Ain't nothin' better when the wind cuts cold
Lord it's a mighty hard livin'
But a damn good feelin' to run these roads
It's a damn good feelin' to run these roads
It's a damn good feelin' to run these roads""",
    },
    "TC_02": {
        "title":  "Lady May",
        "artist": "Tyler Childers",
        "lyrics": """I'm a stone's throw from the mill
And I'm a good walk to the river
When my workin' day is over
We'll go swim our cares away
Put your toes down in the water
And a smile across your face
And tell me that you love me
Lovely Lady May


Now I ain't the sharpest chisel
That your hands have ever held
But darlin' I could love you well
'Til the roll is called on high
I've seen my share of trouble
And I've held my weight in shame
But I'm baptized in your name
Lovely Lady May


Lord the wind can leave you shiverin'
As it waltzes o'er the leaves
It's been rushin' through my timber
'Til your love brought on the spring
Now the mountains all are blushin'
And they don't know what to say
'Cept a good long line of praises
For my lovely Lady May


Now I ain't the toughest hickory
That your ax has ever fell
But I'm a hickory just as well
I'm a hickory all the same
I came crashin' through the forest
As you cut my roots away
And I fell a good long ways
For my lovely Lady May""",
    },
    "TC_03": {
        "title":  "Feathered Indians",
        "artist": "Tyler Childers",
        "lyrics": """Well, my buckle makes impressions
On the inside of her thigh
There are little feathered Indians
Where we tussled through the night
If I'd known she was religious
Then I wouldn't have came stoned
To the house of such an angel
Too fucked up to get back home


Lookin' over West Virginia
Smokin' Spirits on the roof
She asked "Ain't anybody told ya
That them things are bad for you?"
I said, "Many folks have warned me
There's been several people try
But up 'til now, there ain't been nothin'
That I couldn't leave behind"


Hold me close, my dear
Sing your whisperin' song
Softly in my ear
And I will sing along
Honey, tell me how your love runs true
And how I can always count on you
To be there when the bullets fly
I'd run across the river just to hold you tonight


Well, my heart is sweatin' bullets
From the circles it has raced
Like a little feathered Indian
Callin' out the clouds for rain
I'd go runnin' through the thicket
I'd go careless through the thorns
Just to hold her for a minute
Though it'd leave me wantin' more


Hold me close, my dear
Sing your whispering song
Softly in my ear
And I will sing along
Honey, tell me how your love runs true
And how I can always count on you
To be there when the bullets fly
I'd run across the river just to hold you tonight""",
    },
    "TC_04": {
        "title":  "All Your'n",
        "artist": "Tyler Childers",
        "lyrics": """Drivin' through the road work, oh, the work they took forever on
The road cones blur like mem'ries of the miles we shared between
The place you learned to say your prayers, the place I took to prayin'
Loadin' in and breakin' down my road dog door deal dreams
Long before we ever met, I made up my direction
Long before I knew the half of half I'm sure of now
Though I'd say it ain't the way that you'd have gone about it
You follow me and lead me on and never let me down


So I'll love you 'til my lungs give out, I ain't lyin'
I'm all your'n and you're all mine
There ain't two ways around it
There ain't no tryin' 'bout it
I'm all your'n and you're all mine


Fried morels and fine hotels and all that in the middle
Every bite and curtain drawn, I wanna taste with you
Goddess in my Days Inn pen, the muse I ain't refusin'
The part of me that ain't around I'm always talking to


So I'll love you 'til my lungs give out, I ain't lyin'
I'm all your'n and you're all mine
There ain't two ways around it
There ain't no tryin' 'bout it
I'm all your'n and you're all mine


So I'll love you 'til my lungs give out, I ain't lyin'
I'm all your'n and you're all mine
There ain't two ways around it
There ain't no tryin' 'bout it
I'm all your'n and you're all mine
No, there ain't two ways around it
There ain't no tryin' 'bout it
I'm all your'n and you're all mine""",
    },
    "TC_05": {
        "title":  "Hard Way",
        "artist": "Tyler Childers",
        "lyrics": """?""",
    },
    "TC_06": {
        "title":  "Universal Sound",
        "artist": "Tyler Childers",
        "lyrics": """Up in Pocahontas in the Cranberry Glades
Ain’t got bars, nor the charge to call her anyways
My mind’s a mile a minute
And my thoughts, they bark like hounds
I focus on my breathing and the universal sound


I think about my darlin' girl sleepin' all alone
I pray the stars will shoot her all the wishes she can hold
On the day that I return I aim to lay her down
But right now I am focused on the universal sound


I think about tobacco juice and mason jars of shine
I think about the vices I’ve let take me over time
I recall when I's a baby, I didn’t need nothin' around
But a little bitty rattler and the universal sound


I'd close my eyes
It was all so clear
It was all right then
It was all right here


I focus on my breathin’ and the universal sound
I let it take me over from the toenails to the crown
Of the body that I’m in 'til they put me in the ground
And I return to the chorus of the universal sound


I’ve been up on the mountain
And I’ve seen his wondrous grace
I’ve sat there on a barstool and I’ve looked him in the face
He seemed a little haggard, but it did not slow him down
He was hummin' to the neon of the universal sound""",
    },
    "TC_07": {
        "title":  "House Fire",
        "artist": "Tyler Childers",
        "lyrics": """You can set my house on fire, baby
You can turn it into cinder and smoke
'Cause this house is mighty cold and I feel like
Melting all the snow away


You see these boots I'm wearing
They're tough enough to go
And they will take many a road to reach you
Honey, won't you light the way?


You can set my house on fire, baby
You can turn it into cinder and smoke
'Cause this house is mighty cold and I feel like
Melting all the snow away


You see this train I'm riding
It's burnin' up the coal
And its wheels are bound to roll right by you
Honey, won't you jump my train?


You can set my house on fire, baby
You can turn it into cinder and smoke
'Cause this house is mighty cold and I feel like
Melting all the snow away


You can set my house on fire, baby
You can turn it into cinder and smoke
'Cause this house is mighty cold and I feel like
Melting all the snow away
You can set my house on fire, baby""",
    },
    "TC_08": {
        "title":  "Creeker",
        "artist": "Tyler Childers",
        "lyrics": """In a small corner bar, he sits there a-drinkin'
Lost as a ball in a field full of corn
Further away than he ever imagined
That he'd ever end up from the place he was born
Now no more forlorn has a Creeker drank whiskey
Than the one that you see out the side of your eye
Drinkin' alone as he looks out the window
At all of the strangers on the corner outside


And he'd rather be dead than alive one more minute
In this Godforsaken town
When he was a kid, Lord, he'd never a'dreamt it
All the ways that the city can bring a country boy down


Now they knew not his name and he knew not their faces
And he knew not the how nor the reason for why
You could ever wake up and wanna keep on a-livin'
In a place where a friend is such a hard thing to find
And for everyone you meet, there's a whole mess of people
Tryin' like hell to pull you on down
To the level they're on and the trouble they're tendin'
In the mess that they've made, in the gutter they found


And he'd rather be dead than alive one more minute
In this Godforsaken town
When he was a kid, Lord, he'd never a'dreamt it
All the ways that the city can bring a country boy down


Some fellas do drugs and things of that nature
Some fellas chase girls to hang on their arm
Some fellas get by on practically nothin'
Some fellas get pissed in a small corner bar


And they'd rather be dead than alive one more minute
In this Godforsaken town
When they were all kids, Lord, they'd never a'dreamt it
All the ways that the city can bring a country boy down""",
    },
    "TC_09": {
        "title":  "Shake the Frost",
        "artist": "Tyler Childers",
        "lyrics": """You remind me of a Sunday
Back home in ol' Kentucky
With the church choirs just beltin' to the pines
And I love you like the mountains
Love's the way the mornin' opens
To a soft and bright greetin' from the sun


So if it'd make you stay
I wouldn't act so angry all the time
I wouldn't keep it all inside
And I'd let you know how much I loved you every day
So darlin' will you stay right here and shake this frost off of my bones


Well I used to ride a Mustang
And I'd run that thing on high hopes
'Til they raised the price of dreams so high I couldn't pay
So I let that car just sit there
When I should've took you driving
With the windows down while the music played


So if it'd make you stay
I wouldn't act so angry all the time
I wouldn't keep it all inside
And I'd let you know how much I loved you every day
So darlin' will you stay right here and shake this frost off of my bones


Darlin' will you stay right here and shake this frost off of my bones""",
    },
    "TC_10": {
        "title":  "Follow You to Virgie",
        "artist": "Tyler Childers",
        "lyrics": """Back before these calloused hands and all this work
We used to sit up at the flats
Actin' like we'd live forever
Gettin' high and skippin' class
Yeah, I reckon we were heathens
But in her eyes we were saints
Now you're callin' all the boys home
'Cause heaven's angels carried her away


So I will follow you to Virgie
Although it hurts me so
To lay to rest this mountain beauty
That the Lord's called home
And I can see her up in glory
I can see her through the pines


Back when all us boys were tryin'
To make sense of all these strings
I can see her in the corner
Just singin' along to all our crazy dreams


And I will follow you to Virgie
Although it hurts me so
To lay to rest this mountain beauty
That the Lord's called home
And I can see her up in glory
I can see her through the pines


And I will follow you to Virgie
'Cause that's what us boys are for
To help you out when you get weary
And you can't go no more
And can't you see her up there, Cody?
I can see her through the pines
Sayin' "Boys be good"""",
    },
    "TC_11": {
        "title":  "Banded Clovis",
        "artist": "Tyler Childers",
        "lyrics": """Tina Nolan had a man with a good place for siftin’
He invited me diggin’, so I picked up my screen
And a shovel to dig and a jar of shine
He traded me fair for a bottle of wine
His brother’s Barnes Mountain wine


We trudged through the snow straight up the hillside
Took a ridge for a while, then we slowly went down
To an overhang hid from the ridgeline
We bent o'er our handles and we bit in the ground
The dark and bloody ground


Was a bitch to break ground but the wine kept us goin'
The moonshine was flowin' and keepin' us warm
'Cause you can’t hold a girl with a fistful of shovel
Got to find your fire in the company of corn


We dug for a while then it all turned to ashes
Found a bunch of broke flint and a few bits of bone
Then I heard Jesse yell o'er the pile he was siftin’
Shook the hills like the angels were callin’ us home
Jesse, Zachary come home


It was banded as hell, it was fluted and clovis
It was hot as the pistol I kept on my side
I was fiendin’ so fierce, I was broke ass and busted
I pulled out my pistol and I took Jesse’s life


A clovis like that is a hard point to find
Makes pills swift to come by with a good chunk of change
Left over for burn on whatever meanness
Whatever woman is comin' my way
Darlin' come my way


I sit in this cell for the banded clovis
I stole off of Nolan when I killed'm that day
I reckon the chase of the pills and the powder
Corn liquor and women are the culprits to blame""",
    },
    "TC_12": {
        "title":  "Nose on the Grindstone",
        "artist": "Tyler Childers",
        "lyrics": """Daddy worked like a mule minin' Pike County coal
He messed up his back, couldn't work anymore
He said, "One of these days you'll get out of these hills
Keep your nose on the grindstone and out of the pills"


"See, the ways of this world will just bring you to tears
Keep the Lord in your heart and you'll have nothin' to fear
Live the best that you can and don't lie and don't steal
Keep your nose on the grindstone and out of the pills"


Well, Daddy I've been tryin', I just can't catch a break
There's too much in this world I can't seem to shake
But I remembеr your words, Lord, they bring me to chills
"Keep your nose on thе grindstone and out of the pills"


"Now keep in mind that a man's just as good as his word
It takes twice as long to build bridges you've burnt
And there's hurt you can cause time alone cannot heal
Keep your nose on the grindstone and out of the pills"


Well daddy I've been tryin', I just can't catch a break
There's too much in this world I can't seem to shake
But I remember your words, Lord, they bring me to chills
"Keep your nose on the grindstone and out of the pills"
"Keep your nose on the grindstone"""",
    },
    "TC_13": {
        "title":  "Country Squire",
        "artist": "Tyler Childers",
        "lyrics": """Well tonight, I'm up in Chillicothe
Down-wind from the paper mill
I’m out here spittin' on the sidewalk
Taking in the factory smells
Head and nose, she tends to smokin' out the window
In the air, that gas pipe leak
I wonder if she’s cringing at the same time
Thinking pretty thoughts of me


I was up for hours this morning
Pulling traps before I said goodbye
I plan to tan myself a fox hide
And hang it on my darling bride
'Cause they tell me that it's gonna be a big one
And the snow is settin' in
And I don't want her cold while I ain't at home
The way that I have been


Spending my nights in a bar room, Lord
Turnin' them songs into two-by-fours
Dreaming 'bout the day that I’m sitting by the fire
Huddled with my honey in the Country Squire


Well tomorrow, we hit the country music highway
On our way to Circleville
We’re off to do some weekend warring
While we sing and drink our fill
And when I ain't out playing on my six-string
With the nickels I acquire
I’m trying to fix her up a castle
It's called the Country Squire


It's a 24-foot-long vessel
That measures eight feet wide
It's a 53-year-old camper
It’s made to pull behind
And I've gutted to the studs and the rafters
And I'm building back piece by piece
I'm trying to fix her up a temple
My Lady of the Estill Springs


Spending my nights in a bar room, Lord
Turnin' them songs into two-by-fours
Dreaming 'bout the day that I'll sit by the fire
Huddled with my honey in our Country Squire


One day, I aim to have myself a family
And a cabin on the hill
And I might have to come off of the highway
To help with the family bills
But when the kids have got a little older
On the day that I retire
I'll take her somewhere warm for the winter
Pulling our Country Squire


Spending my nights in a bar room, Lord
Turnin' them songs into two-by-fours
Dreaming 'bout the day that I'll sit by the fire
Huddled with my honey in our Country Squire
Dreaming 'bout the day that I'll sit by the fire
Huddled with my honey in our Country Squire""",
    },
    "TC_14": {
        "title":  "Ever Lovin' Hand",
        "artist": "Tyler Childers",
        "lyrics": """They got my favorite lotion here
Something in a hotel I admire
I got the pictures that you sent me
And how they fill me with desire
Tonight, we've all got our own rooms
I’m about to burn mine down
'Cause I miss you somethin' fierce
In this quaint New England town
I read the texts you whispered plain
Everything you aim to do
I sure do like the way you think
That’s the way I'm thinking too
I see it play out in my mind
You and I unite as one
The van don't leave 'til 10 AM
And we've only just begun


This one here goes out to you
Lord, wherever you may be
When you're reaching for the fruit
I pray you'll fondly think of me
It gets so hard out on the road
But I'm going alone ’cause I’m your man
I have got you on my mind
And my ever lovin' hand


For a moment, you were here
A moment passed and you were gone
Leavin’ me to clean the mess
That you clearly helped to cause
When the boys ask how I slept
I'll just look 'em in the eye
Tell them all you'd come to visit
I didn’t get a wink of sleep all night


This one here goes out to you
Lord, wherever you may be
When you're reaching for the fruit
I pray you'll fondly think of me
It gets so hard out on the road
But I'm going alone 'cause I'm your man
I have got you on my mind
And my ever lovin' hand
It gets so hard out on the road
But I'm going alone 'cause I'm your man
I have got you on my mind
And my ever lovin' hand""",
    },
    "TC_15": {
        "title":  "Matthew",
        "artist": "Tyler Childers",
        "lyrics": """He works the night shift at the depot
With a pistol and a light
And he guards them rusty missiles
Counting whitetail to pass the time
And he's worked there for a long while
Since he came home from overseas
Helping Kilcoran fight the good fight
And bring Baghdad to its knees
And it was hotter than the mountain
But it weren't so he couldn't stand
And it weren't so much the heat wave
Nearly as much as all the sand


Now his daddy, he's a log man
With a good leg and a fake
That he got off of a buddy
And a shitshot that he made
And he worked them hands to splinters
And he raised them young'uns right
On a little bit of scripture
And an acreage of paradise
And he'd go out on the weekend
And he played like Clarence White
If Clarence had had a real job
And picked the guitar when there was time


Keeps a trap line in the winter
Keeps a line wet in the spring
On a lock wall, fishing muskie
With his eldest and Steve
And they swap tales about their raisin'
And they tell the awfulest lies
And they go home when they've a notion
And the muskie quit to bitin'""",
    },
}
