# Auto-generated by 03_build_schema.py — do not edit manually.
# Artist: Taylor Swift  |  Code: TS
# Songs included: 15  |  Missing: 0

TS_SCHEMA = {
    "TS_01": {
        "title":  "Anti-Hero",
        "artist": "Taylor Swift",
        "lyrics": """I have this thing where I get older, but just never wiser
Midnights become my afternoons
When my depression works the graveyard shift, all of the people
I've ghosted stand there in the room


I should not be left to my own devices
They come with prices and vices
I end up in crisis
(Tale as old as time)
I wake up screaming from dreaming
One day, I'll watch as you're leaving
'Cause you got tired of my scheming
(For the last time)


It's me, hi
I'm the problem, it's me
At teatime, everybody agrees
I'll stare directly at the sun, but never in the mirror
It must be exhausting always rooting for the anti-hero


Sometimes, I feel like everybody is a sexy baby
And I'm a monster on the hill
Too big to hang out, slowly lurching toward your favorite city
Pierced through the heart, but never killed


Did you hear my covert narcissism I disguise as altruism
Like some kind of congressman?
(A tale as old as time)
I wake up screaming from dreaming
One day, I'll watch as you're leaving
And life will lose all its meaning
(For the last time)


It's me, hi
I'm the problem, it's me (I'm the problem, it's me)
At teatime, everybody agrees
I'll stare directly at the sun, but never in the mirror
It must be exhausting always rooting for the anti-hero


I have this dream my daughter-in-law kills me for the money
She thinks I left them in the will
The family gathers 'round and reads it and then someone screams out
"She's laughing up at us from Hell"


It's me, hi
I'm the problem, it's me
It's me, hi
I'm the problem, it's me
It's me, hi
Everybody agrees, everybody agrees


It's me, hi (Hi)
I'm the problem, it's me (I'm the problem, it's me)
At teatime (Teatime), everybody agrees (Everybody agrees)
I'll stare directly at the sun, but never in the mirror
It must be exhausting always rooting for the anti-hero""",
    },
    "TS_02": {
        "title":  "Shake It Off",
        "artist": "Taylor Swift",
        "lyrics": """I stay out too late
Got nothin' in my brain
That's what people say, mm-mm
That's what people say, mm-mm
I go on too many dates (Haha)
But I can't make them stay
At least, that's what people say, mm-mm
That's what people say, mm-mm


But I keep cruisin'
Can't stop, won't stop movin'
It's like I got this music in my mind
Sayin', "It's gonna be alright"


'Cause the players gonna play, play, play, play, play
And the haters gonna hate, hate, hate, hate, hate
Baby, I'm just gonna shake, shake, shake, shake, shake
I shake it off, I shake it off
Heartbreakers gonna break, break, break, break, break
And the fakers gonna fake, fake, fake, fake, fake
Baby, I'm just gonna shake, shake, shake, shake, shake
I shake it off, I shake it off


I never miss a beat
I'm lightnin' on my feet
And that's what they don't see, mm-mm
That's what they don't see, mm-mm
I'm dancin' on my own (Dancin' on my own)
I make the moves up as I go (Moves up as I go)
And that's what they don't know, mm-mm
That's what they don't know, mm-mm


But I keep cruisin'
Can't stop, won't stop groovin'
It's like I got this music in my mind
Sayin', "It's gonna be alright"


'Cause the players gonna play, play, play, play, play
And the haters gonna hate, hate, hate, hate, hate
Baby, I'm just gonna shake, shake, shake, shake, shake
I shake it off, I shake it off
Heartbreakers gonna break, break, break, break, break
And the fakers gonna fake, fake, fake, fake, fake
Baby, I'm just gonna shake, shake, shake, shake, shake
I shake it off, I shake it off


I shake it off, I shake it off
I, I, I shake it off, I shake it off
I, I, I shake it off, I shake it off
I, I, I shake it off, I shake it off


Hey, hey, hey
Just think, while you've been gettin' down and out about the liars
And the dirty, dirty cheats of the world
You could've been gettin' down
To this sick beat


My ex-man brought his new girlfriend
She's like, "Oh my God," but I'm just gonna shake
And to the fella over there with the hella good hair
Won't you come on over, baby? We can shake, shake, shake
Yeah, oh-oh, oh


'Cause the players gonna play, play, play, play, play
And the haters gonna hate, hate, hate, hate, hate (Haters gonna hate)
Baby, I'm just gonna shake, shake, shake, shake, shake
I shake it off, I shake it off (Ha)
Heartbreakers gonna break, break, break, break, break (Mmm)
And the fakers gonna fake, fake, fake, fake, fake (They fake and fake and fake)
Baby, I'm just gonna shake, shake, shake, shake, shake
I shake it off, I shake it off (I, I)


I shake it off, I shake it off
I, I, I shake it off, I shake it off
I, I, I shake it off, I shake it off
I, I, I shake it off (Yeah), I shake it off
I shake it off, I shake it off
I, I, I shake it off, I shake it off (You got to)
I, I, I shake it off, I shake it off
I, I, I shake it off, I shake it off""",
    },
    "TS_03": {
        "title":  "Love Story (Taylor's Version)",
        "artist": "Taylor Swift",
        "lyrics": """We were both young when I first saw you
I close my eyes and the flashback starts
I'm standing there
On a balcony in summer air
See the lights, see the party, the ball gowns
See you make your way through the crowd
And say, "Hello"
Little did I know


That you were Romeo, you were throwing pebbles
And my daddy said, "Stay away from Juliet"
And I was crying on the staircase
Begging you, "Please don't go," and I said


Romeo, take me somewhere we can be alone
I'll be waiting, all there's left to do is run
You'll be the prince and I'll be the princess
It's a love story, baby, just say, "Yes"


So I sneak out to the garden to see you
We keep quiet 'cause we're dead if they knew
So close your eyes
Escape this town for a little while, oh, oh


'Cause you were Romeo, I was a scarlet letter
And my daddy said, "Stay away from Juliet"
But you were everything to me
I was begging you, "Please don't go," and I said


Romeo, take me somewhere we can be alone
I'll be waiting, all there's left to do is run
You'll be the prince and I'll be the princess
It's a love story, baby, just say, "Yes"
Romeo, save me, they're trying to tell me how to feel
This love is difficult, but it's real
Don't be afraid, we'll make it out of this mess
It's a love story, baby, just say, "Yes"


Oh, oh


But I got tired of waiting
Wondering if you were ever coming around
My faith in you was fading
When I met you on the outskirts of town and I said

"Romeo, save me, I've been feeling so alone
I keep waiting for you, but you never come
Is this in my head? I don't know what to think"
He knelt to the ground and pulled out a ring, and said
"Marry me, Juliet, you'll never have to be alone
I love you and that's all I really know
I talked to your dad, go pick out a white dress
It's a love story, baby, just say 'Yes'"


Oh, oh, oh
Oh, oh, oh
'Cause we were both young when I first saw you""",
    },
    "TS_04": {
        "title":  "Blank Space",
        "artist": "Taylor Swift",
        "lyrics": """Nice to meet you, where you been?
I could show you incredible things
Magic, madness, heaven, sin
Saw you there and I thought
"Oh, my God, look at that face
You look like my next mistake
Love's a game, wanna play?" Ayy
New money, suit and tie
I can read you like a magazine
Ain't it funny? Rumors fly
And I know you heard about me
So, hey, let's be friends
I'm dying to see how this one ends
Grab your passport and my hand
I can make the bad guys good for a weekend


So it's gonna be forever
Or it's gonna go down in flames?
You can tell me when it's over, mm
If the high was worth the pain
Got a long list of ex-lovers
They'll tell you I'm insane
'Cause you know I love the players
And you love the game
'Cause we're young and we're reckless
We'll take this way too far
It'll leave you breathless, mm
Or with a nasty scar
Got a long list of ex-lovers
They'll tell you I'm insane
But I've got a blank space, baby
And I'll write your name


Cherry lips, crystal skies
I could show you incredible things
Stolen kisses, pretty lies
You're the king, baby, I'm your queen
Find out what you want
Be that girl for a month
Wait, the worst is yet to come, oh, no
Screaming, crying, perfect storms
I can make all the tables turn
Rose garden filled with thorns
Keep you second guessing, like
"Oh, my God, who is she?"
I get drunk on jealousy
But you'll come back each time you leave
'Cause, darling, I'm a nightmare dressed like a daydream


So it's gonna be forever
Or it's gonna go down in flames?
You can tell me when it's over, mm
If the high was worth the pain
Got a long list of ex-lovers
They'll tell you I'm insane
'Cause you know I love the players
And you love the game
'Cause we're young and we're reckless (Oh)
We'll take this way too far
It'll leave you breathless (Oh-oh), mm
Or with a nasty scar
Got a long list of ex-lovers
They'll tell you I'm insane (Insane)
But I've got a blank space, baby
And I'll write your name


Boys only want love if it's torture
Don't say I didn't, say I didn't warn ya
Boys only want love if it's torture
Don't say I didn't, say I didn't warn ya


So it's gonna be forever
Or it's gonna go down in flames?
You can tell me when it's over (Over), mm
If the high was worth the pain
Got a long list of ex-lovers
They'll tell you I'm insane (I'm insane)
'Cause you know I love the players
And you love the game (And you love the game)
'Cause we're young and we're reckless (Yeah)
We'll take this way too far (Ooh)
It'll leave you breathless, mm
Or with a nasty scar (With a nasty scar)
Got a long list of ex-lovers
They'll tell you I'm insane
But I've got a blank space, baby
And I'll write your name""",
    },
    "TS_05": {
        "title":  "Style",
        "artist": "Taylor Swift",
        "lyrics": """Midnight
You come and pick me up, no headlights
Long drive
Could end in burning flames or paradise
Fade into view, oh
It's been a while since I have even heard from you
(Heard from you)


And I should just tell you to leave, 'cause I
Know exactly where it leads, but I
Watch us go 'round and 'round each time


You got that James Dean daydream look in your eye
And I got that red lip classic thing that you like
And when we go crashing down, we come back every time
'Cause we never go out of style, we never go out of style
You got that long hair, slicked back, white T-shirt
And I got that good-girl faith and a tight little skirt
And when we go crashing down, we come back every time
'Cause we never go out of style, we never go out of style


So it goes
He can't keep his wild eyes on the road, mm
Takes me home
The lights are off, he's taking off his coat, mm, yeah
I say, "I heard, oh
That you've been out and about with some other girl"
Some other girl


He says, "What you heard is true, but I
Can't stop thinking 'bout you and I"
I said, "I've been there too, a few times"


You got that James Dean daydream look in your eye
And I got that red lip classic thing that you like
And when we go crashing down, we come back every time
'Cause we never go out of style, we never go out of style
You got that long hair, slicked back, white T-shirt
And I got that good-girl faith and a tight little skirt (A tight little skirt)
And when we go crashing down, we come back every time
'Cause we never go out of style (We never go, we never go), we never go out of style


Take me home (Ah)
Just take me home (Ah)
Yeah, just take me home (Ah)
Oh-oh, woah-oh, oh (Out of style)


Oh, you got that James Dean daydream look in your eye
And I got that red lip classic thing that you like
And when we go crashing down (And when we go), we come back every time
'Cause we never go out of style, we never go out of style""",
    },
    "TS_06": {
        "title":  "Delicate",
        "artist": "Taylor Swift",
        "lyrics": """This ain't for the best
My reputation's never been worse, so
You must like me for me
We can't make
Any promises now, can we, babe?
But you can make me a drink


Dive bar on the East Side, where you at?
Phone lights up my nightstand in the black
Come here, you can meet me in the back
Dark jeans and your Nikes, look at you
Oh, damn, never seen that color blue
Just think of the fun things we could do


('Cause I like you) This ain't for the best
My reputation's never been worse, so
You must like me for me
(Yeah, I want you) We can't make
Any promises now, can we, babe?
But you can make me a drink


Is it cool that I said all that?
Is it chill that you're in my head?
'Cause I know that it's delicate (Delicate)
Is it cool that I said all that?
Is it too soon to do this yet?
'Cause I know that it's delicate


Isn't it? Isn't it? Isn't it? Isn't it?
Isn't it? Isn't it? Isn't it? Isn't it delicate?


Third floor on the West Side, me and you
Handsome, you're a mansion with a view
Do the girls back home touch you like I do?
Long night with your hands up in my hair
Echoes of your footsteps on the stairs
Stay here, honey, I don't wanna share


('Cause I like you) This ain't for the best
My reputation's never been worse, so
You must like me for me
(Yeah, I want you) We can't make
Any promises now, can we, babe?
But you can make me a drink


Is it cool that I said all that?
Is it chill that you're in my head?
'Cause I know that it's delicate (Delicate)
Is it cool that I said all that?
Is it too soon to do this yet?
'Cause I know that it's delicate


Isn't it? Isn't it? Isn't it? Isn't it?
Isn't it? Isn't it? Isn't it? Isn't it delicate?


Sometimes, I wonder, when you sleep
Are you ever dreaming of me?
Sometimes, when I look into your eyes
I pretend you're mine all the damn time


('Cause I like you)
Is it cool that I said all that?
Is it chill that you're in my head?
'Cause I know that it's delicate (Delicate)
(Yeah, I want you)
Is it cool that I said all that?
Is it too soon to do this yet?
'Cause I know that it's delicate (Delicate)
('Cause I like you)
Is it cool that I said all that? (Isn't it?)
Is it chill that you're in my head? (Isn't it? Isn't it?)
'Cause I know that it's delicate (Isn't it delicate?)
(Yeah, I want you)
Is it cool that I said all that? (Isn't it?)
Is it too soon to do this yet? (Isn't it? Isn't it?)
'Cause I know that it's delicate
Isn't it delicate?""",
    },
    "TS_07": {
        "title":  "cardigan",
        "artist": "Taylor Swift",
        "lyrics": """Vintage tee, brand new phone
High heels on cobblestones
When you are young, they assume you know nothing
Sequin smile, black lipstick
Sensual politics
When you are young, they assume you know nothing


But I knew you
Dancin' in your Levi's
Drunk under a streetlight, I
I knew you
Hand under my sweatshirt
Baby, kiss it better, I


And when I felt like I was an old cardigan
Under someone's bed
You put me on and said I was your favorite


A friend to all is a friend to none
Chase two girls, lose the one
When you are young, they assume you know nothing


But I knew you
Playing hide-and-seek and
Giving me your weekends, I
I knew you
Your heartbeat on the High Line
Once in twenty lifetimes, I


And when I felt like I was an old cardigan
Under someone's bed
You put me on and said I was your favorite


To kiss in cars and downtown bars
Was all we needed
You drew stars around my scars
But now I'm bleedin'


'Cause I knew you
Steppin' on the last train
Marked me like a bloodstain, I
I knew you
Tried to change the ending
Peter losing Wendy, I
I knew you
Leavin' like a father
Running like water, I
And when you are young, they assume you know nothing


But I knew you'd linger like a tattoo kiss
I knew you'd haunt all of my what-ifs
The smell of smoke would hang around this long
'Cause I knew everything when I was young
I knew I'd curse you for the longest time
Chasin' shadows in the grocery line
I knew you'd miss me once the thrill expired
And you'd be standin' in my front porch light
And I knew you'd come back to me
You'd come back to me
And you'd come back to me
And you'd come back


And when I felt like I was an old cardigan
Under someone's bed
You put me on and said I was your favorite""",
    },
    "TS_08": {
        "title":  "august",
        "artist": "Taylor Swift",
        "lyrics": """Salt air, and the rust on your door
I never needed anything more
Whispers of "Are you sure?"
"Never have I ever before"


But I can see us lost in the memory
August slipped away into a moment in time
'Cause it was never mine
And I can see us twisted in bedsheets
August sipped away like a bottle of wine
'Cause you were never mine


Your back beneath the sun
Wishin' I could write my name on it
Will you call when you're back at school?
I remember thinkin' I had you


But I can see us lost in the memory
August slipped away into a moment in time
'Cause it was never mine
And I can see us twisted in bedsheets
August sipped away like a bottle of wine
'Cause you were never mine


Back when we were still changin' for the better
Wanting was enough
For me, it was enough
To live for the hope of it all
Cancel plans just in case you'd call
And say, "Meet me behind the mall"
So much for summer love and saying "us"
'Cause you weren't mine to lose
You weren't mine to lose, no


But I can see us lost in the memory
August slipped away into a moment in time
'Cause it was never mine
And I can see us twisted in bedsheets
August sipped away like a bottle of wine
'Cause you were never mine


'Cause you were never mine
Never mine
But do you remember?
Remember when I pulled up and said "Get in the car"
And then canceled my plans just in case you'd call?
Back when I was livin' for the hope of it all, for the hope of it all
"Meet me behind the mall"
(Remember when I pulled up and said "Get in the car")
(And then canceled my plans just in case you'd call?)
(Back when I was livin' for the hope of it all, for the hope of it all)
("Meet me behind the mall")
Remember when I pulled up and said "Get in the car"
And then canceled my plans just in case you'd call?
Back when I was livin' for the hope of it all (For the hope of it all)
For the hope of it all, for the hope of it all
(For the hope of it all, for the hope of it all)""",
    },
    "TS_09": {
        "title":  "Lover",
        "artist": "Taylor Swift",
        "lyrics": """We could leave the Christmas lights up 'til January
And this is our place, we make the rules
And there's a dazzling haze, a mysterious way about you, dear
Have I known you twenty seconds or twenty years?


Can I go where you go?
Can we always be this close?
Forever and ever, ah
Take me out and take me home
You're my, my, my, my lover


We could let our friends crash in the living room
This is our place, we make the call
And I'm highly suspicious that everyone who sees you wants you
I've loved you three summers now, honey, but I want 'em all


Can I go where you go?
Can we always be this close?
Forever and ever, ah
Take me out and take me home (Forever and ever)
You're my, my, my, my lover


Ladies and gentlemen, will you please stand?
With every guitar string scar on my hand
I take this magnetic force of a man to be my lover
My heart's been borrowed and yours has been blue
All's well that ends well to end up with you
Swear to be overdramatic and true to my lover
And you'll save all your dirtiest jokes for me
And at every table, I'll save you a seat, lover


Can I go where you go?
Can we always be this close?
Forever and ever, ah
Take me out and take me home (Forever and ever)
You're my, my, my, my
Oh, you're my, my, my, my
Darling, you're my, my, my, my lover""",
    },
    "TS_10": {
        "title":  "All Too Well (10 Minute Version)",
        "artist": "Taylor Swift",
        "lyrics": """I walked through the door with you, the air was cold
But something 'bout it felt like home somehow
And I left my scarf there at your sister's house
And you've still got it in your drawer, even now


Oh, your sweet disposition and my wide-eyed gaze
We're singing in the car, getting lost upstate
Autumn leaves falling down like pieces into place
And I can picture it after all these days


And I know it's long gone and
That magic's not here no more
And I might be okay, but I'm not fine at all
Oh, oh, oh


'Cause there we are again on that little town street
You almost ran the red 'cause you were lookin' over at me
Wind in my hair, I was there
I remember it all too well


Photo album on the counter, your cheeks were turning red
You used to be a little kid with glasses in a twin-sized bed
And your mother's telling stories 'bout you on the tee-ball team
You taught me 'bout your past, thinking your future was me


And I know it's long gone and
There was nothing else I could do
And I forget about you long enough
To forget why I needed to


'Cause there we are again in the middle of the night
We're dancing ‘round the kitchen in the refrigerator light
Down the stairs, I was there
I remember it all too well, yeah


Well, maybe we got lost in translation
Maybe I asked for too much
But maybe this thing was a masterpiece
'Til you tore it all up
Running scared, I was there
I remember it all too well
And you call me up again
Just to break me like a promise
So casually cruel in the name of being honest
I'm a crumpled up piece of paper lying here
'Cause I remember it all, all, all
Too well


Time won't fly, it's like I'm paralyzed by it
I'd like to be my old self again, but I'm still trying to find it
After plaid shirt days and nights when you made me your own
Now, you mail back my things and I walk home alone
But you keep my old scarf from that very first week
'Cause it reminds you of innocence and it smells like me
You can't get rid of it
'Cause you remember it all too well, yeah


'Cause there we are again when I loved you so
Back before you lost the one real thing you've ever known
It was rare, I was there
I remember it all too well


Wind in my hair, you were there
You remember it all
Down the stairs, you were there
You remember it all
It was rare, I was there
I remember it all too well""",
    },
    "TS_11": {
        "title":  "22",
        "artist": "Taylor Swift",
        "lyrics": """It feels like a perfect night
To dress up like hipsters
And make fun of our exes
Uh-uh, uh-uh
It feels like a perfect night
For breakfast at midnight
To fall in love with strangers
Uh-uh, uh-uh


Yeah
We're happy, free, confused and lonely at the same time
It's miserable and magical, oh, yeah
Tonight's the night when we forget about the deadlines
It's time, oh-oh


I don't know about you
But I'm feeling twenty-two
Everything will be alright if
You keep me next to you
You don't know about me
But I'll bet you want to
Everything will be alright if
We just keep dancing like we're
Twenty-two, twenty-two


It seems like one of those nights
This place is too crowded
Too many cool kids
Uh-uh, uh-uh (Who's Taylor Swift, anyway? Ew)
It seems like one of those nights
We ditch the whole scene
And end up dreamin'
Instead of sleeping


Yeah
We're happy, free, confused and lonely in the best way
It's miserable and magical, oh, yeah
Tonight's the night when we forget about the heartbreaks
It's time, oh-oh


(Hey!) I don't know about you
But I'm feeling twenty-two
Everything will be alright if (Ooh)
You keep me next to you
You don't know about me
But I'll bet you want to
Everything will be alright if (Alright)
We just keep dancing like we're
Twenty-two (Oh-oh-oh-oh, oh), twenty-two (I don't know about you)
Twenty-two, twenty-two (Ooh)


It feels like one of those nights
We ditch the whole scene
It feels like one of those nights
We won't be sleepin'
It feels like one of those nights
You look like bad news
I gotta have you
I gotta have you (You)
Woah, ooh, yeah, eh-yeah


(Hey!) I don't know about you (I don't know about you)
But I'm feeling twenty-two
Everything will be alright if (Ooh)
You keep me next to you
You don't know about me (You don't know about me)
But I'll bet you want to
Everything will be alright if
We just keep dancing like we're (Dancing like we're twenty-two)
Twenty-two (Woah-oh), twenty-two (Dancing like)
Twenty-two (Yeah, yeah), twenty-two (Yeah, yeah, yeah)


It feels like one of those nights (Twenty-two)
We ditch the whole scene
It feels like one of those nights (Twenty-two)
We won't be sleeping
It feels like one of those nights (Twenty-two)
You look like bad news
I gotta have you
I gotta have you""",
    },
    "TS_12": {
        "title":  "Wildest Dreams",
        "artist": "Taylor Swift",
        "lyrics": """He said, "Let's get out of this town
Drive out of the city, away from the crowds"
I thought, "Heaven can't help me now"
Nothing lasts forever
But this is gonna take me down


He's so tall and handsome as hell
He's so bad, but he does it so well
I can see the end as it begins
My one condition is


Say you'll remember me
Standin' in a nice dress
Starin' at the sunset, babe
Red lips and rosy cheeks
Say you'll see me again
Even if it's just in your
Wildest dreams, ah, ha
Wildest dreams, ah, ha


I said, "No one has to know what we do"
His hands are in my hair, his clothes are in my room
And his voice is a familiar sound
Nothin' lasts forever
But this is gettin' good now


He's so tall and handsome as hell
He's so bad, but he does it so well
And when we've had our very last kiss
My last request is


Say you'll remember me
Standin' in a nice dress
Starin' at the sunset, babe
Red lips and rosy cheeks
Say you'll see me again
Even if it's just in your
Wildest dreams, ah, ha
Wildest dreams, ah, ha


You'll see me in hindsight
Tangled up with you all night
Burnin' it down
Someday, when you leave me
I bet these memories
Follow you around
You'll see me in hindsight
Tangled up with you all night
Burnin' (Burnin') it (It) down (Down)
Someday, when you leave me
I bet these memories
Follow (Follow) you (You) around
(Follow you around)


Say you'll remember me
Standing in a nice dress
Starin' at the sunset, babe
Red lips and rosy cheeks
Say you'll see me again
Even if it's just pretend


Say you'll remember me
Standin' in a nice dress
Starin' at the sunset, babe
Red lips and rosy cheeks
Say you'll see me again
Even if it's just in your (Just pretend, just pretend)
Wildest dreams, ah, ha (Ah)
In your wildest dreams, ah, ha
Even if it's just in your
In your wildest dreams, ah, ha
In your wildest dreams, ah, ha""",
    },
    "TS_13": {
        "title":  "Cruel Summer",
        "artist": "Taylor Swift",
        "lyrics": """(Yeah, yeah, yeah, yeah)


Fever dream high in the quiet of the night
You know that I caught it (Oh yeah, you're right, I want it)
Bad, bad boy, shiny toy with a price
You know that I bought it (Oh yeah, you're right, I want it)


Killing me slow, out the window
I'm always waiting for you to be waiting below
Devils roll the dice, angels roll their eyes
What doesn't kill me makes me want you more


And it's new, the shape of your body
It's blue, the feeling I've got
And it's ooh, woah-oh
It's a cruel summer
It's cool, that's what I tell 'em
No rules in breakable heaven
But ooh, woah-oh
It's a cruel summer with you


Hang your head low in the glow of the vending machine
I'm not dying (
Oh yeah, you're right, I want it
)
We say that we'll just screw it up in these trying times
We're not trying (Oh yeah, you're right, I want it)


So cut the headlights, summer's a knife
I'm always waiting for you just to cut to the bone
Devils roll the dice, angels roll their eyes
And if I bleed, you'll be the last to know, oh


It's new, the shape of your body
It's blue, the feeling I've got
And it's ooh, woah-oh
It's a cruel summer
It's cool, that's what I tell 'em
No rules in breakable heaven
But ooh, woah-oh
It's a cruel summer with you


I'm drunk in the back of the car
And I cried like a baby comin' home from the bar (Oh)
Said, "I'm fine," but it wasn't true
I don't wanna keep secrets just to keep you
And I snuck in through the garden gate
Every night that summer just to seal my fate (Oh)
And I scream, "For whatever it's worth
I love you, ain't that the worst thing you ever heard?"
He looks up, grinnin' like a devil


It's new, the shape of your body
It's blue, the feeling I've got
And it's ooh, woah-oh
It's a cruel summer
It's cool, that's what I tell 'em
No rules in breakable heaven
But ooh, woah-oh
It's a cruel summer with you


I'm drunk in the back of the car
And I cried like a baby comin' home from the bar (Oh)
Said, "I'm fine," but it wasn't true
I don't wanna keep secrets just to keep you
And I snuck in through the garden gate
Every night that summer just to seal my fate (Oh)
And I scream, "For whatever it's worth
I love you, ain't that the worst thing you ever heard?"
(Yeah, yeah, yeah, yeah)""",
    },
    "TS_14": {
        "title":  "The 1",
        "artist": "Taylor Swift",
        "lyrics": """I'm doing good, I'm on some new shit
Been saying "yes" instead of "no"
I thought I saw you at the bus stop, I didn't though
I hit the ground running each night
I hit the Sunday matinée
You know the greatest films of all time were never made


I guess you never know, never know
And if you wanted me, you really should've showed
And if you never bleed, you're never gonna grow
And it's alright now


But we were something, don't you think so?
Roaring twenties, tossing pennies in the pool
And if my wishes came true
It would've been you
In my defense, I have none
For never leaving well enough alone
But it would've been fun
If you would've been the one
(Ooh)


I have this dream you're doing cool shit
Having adventures on your own
You meet some woman on the internet and take her home
We never painted by the numbers, baby
But we were making it count
You know the greatest loves of all time are over now


I guess you never know, never know
And it's another day waking up alone


But we were something, don't you think so?
Roaring twenties, tossing pennies in the pool
And if my wishes came true
It would've been you
In my defense, I have none
For never leaving well enough alone
But it would've been fun
If you would've been the one


I, I, I persist and resist the temptation to ask you
If one thing had been different
Would everything be different today?


We were something, don't you think so?
Rosé flowing with your chosen family
And it would've been sweet
If it could've been me
In my defense, I have none
For digging up the grave another time
But it would've been fun
If you would've been the one
(Ooh)""",
    },
    "TS_15": {
        "title":  "Don't Blame Me",
        "artist": "Taylor Swift",
        "lyrics": """Don't blame me, love made me crazy
If it doesn't, you ain't doin' it right
Lord, save me, my drug is my baby
I'll be usin' for the rest of my life


I've been breakin' hearts a long time
And toyin' with them older guys
Just playthings for me to use
Somethin' happened for the first time
In the darkest little paradise
Shaking, pacin', I just need you


For you, I would cross the line
I would waste my time
I would lose my mind
They say, "She's gone too far this time"


Don't blame me, love made me crazy
If it doesn't, you ain't doin' it right
Lord, save me, my drug is my baby
I'll be usin' for the rest of my life
Don't blame me, love made me crazy
If it doesn't, you ain't doin' it right
Oh Lord, save me, my drug is my baby
I'll be usin' for the rest of my life


My name is whatever you decide and
I'm just gonna call you mine
I'm insane, but I'm your baby (Your baby)
Echoes (Echoes) of your name inside my mind
Halo hidin' my obsession
I once was poison ivy, but now, I'm your daisy


And, baby, for you, I (I) would (Would) fall from grace
Just (Just) to (To) touch your face
If (If) you (You) walk away
I'd beg ya on my knees to stay


Don't blame me, love made me crazy
If it doesn't, you ain't doin' it right
Lord, save me, my drug is my baby
I'll be usin' for the rest of my life (Yeah, ooh)
Don't blame me, love made me crazy
If it doesn't, you ain't doin' it right
Oh Lord, save me, my drug is my baby
I'll be usin' for the rest of my life


I get so high, oh
Every time you're, every time you're lovin' me
You're lovin' me
Trip of my life, oh
Every time you're, every time you're touchin' me
You're touchin' me
Every time you're, every time you're lovin' me


Oh Lord, save me, my drug is my baby
I'll be usin' for the rest of my life
(Usin' for the rest of my life, oh, woah)


Don't blame me, love made me crazy
If it doesn't, you ain't doin' it right (Doin' it right, no)
Lord, save me, my drug is my baby
I'll be usin' for the rest of my life (Oh)
Don't blame me, love made me crazy (Ooh)
If it doesn't, you ain't doin' it right (You ain't doin' it right)
Oh Lord, save me, my drug is my baby
I'll be usin' for the rest of my life (I'll be usin', I'll be usin')


I get so high, oh
Every time you're, every time you're lovin' me
You're lovin' me
Oh Lord, save me, my drug is my baby
I'll be usin' for the rest of my life""",
    },
}
